In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

### installing the package

In [2]:
!pip install yahooquery

Collecting yahooquery
  Downloading yahooquery-2.3.7-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.2 in /usr/local/lib/python3.10/dist-packages (from yahooquery) (4.12.3)
Collecting lxml<5.0.0,>=4.9.3 (from yahooquery)
  Downloading lxml-4.9.4-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Requirement already satisfied: pandas<3.0.0,>=2.0.3 in /usr/local/lib/python3.10/dist-packages (from yahooquery) (2.2.3)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in /usr/local/lib/python3.10/dist-packages (from yahooquery) (2.32.3)
Collecting requests-futures<2.0.0,>=1.0.1 (from yahooquery)
  Downloading requests_futures-1.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /usr/local/lib/python3.10/dist-packages (from yahooquery) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4<5.0.0,>=4.12.2->yahooquery) (2.6)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.3->yahooquery) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.3->yahooquery) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.3->yahooquery) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.3->yahooquery) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.31.0->yahooquery) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.31.0->yahooquery) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.31.0->yahooquery) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.31.0->yahooquery) (2025.1.31)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy>=1.22.4->pandas<3.0.0,>=2.0.3->yahooquery) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy>=1.22.4->pandas<3.0.0,>=2.0.3->yahooquery) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy>=1.22.4->pandas<3.0.0,>=2.0.3->yahooquery) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy>=1.22.4->pandas<3.0.0,>=2.0.3->yahooquery) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy>=1.22.4->pandas<3.0.0,>=2.0.3->yahooquery) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy>=1.22.4->pandas<3.0.0,>=2.0.3->yahooquery) (2.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0.3->yahooquery) (1.17.0)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.22.4->pandas<3.0.0,>=2.0.3->yahooquery) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.22.4->pandas<3.0.0,>=2.0.3->yahooquery) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy>=1.22.4->pandas<3.0.0,>=2.0.3->yahooquery) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy>=1.22.4->pandas<3.0.0,>=2.0.3->yahooquery) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy>=1.22.4->pandas<3.0.0,>=2.0.3->yahooquery) (2024.2.0)
Downloading yahooquery-2.3.7-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 1.8 MB/s eta 0:00:00
Downloading lxml-4.9.4-cp310-cp310-manylinux_2_28_x86_64.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 65.2 MB/s eta 0:00:00
Downloading requests_futures-1.0.2-py2.py3-none-any.whl (7.7 kB)
Installing collected packages: lxml, requests-futures, yahooquery
  Attempting uninstall: lxml
    Found existing installation: lxml 5.3.0
    Uninstalling lxml-5.3.0:
      Successfully uninstalled lxml-5.3.0
Successfully installed lxml-4.9.4 requests-futures-1.0.2 yahooquery-2.3.7

# importing the libraries

In [3]:
import pandas as pd
import yfinance as yf
import datetime
from datetime import date, timedelta

In [4]:
end_date = date.today()
start_date = end_date - timedelta(days=730)  # 2 years = 730 days

from yahooquery import Ticker
btc = Ticker('BTC-USD')

# Fetch historical data
data = btc.history(start=start_date.strftime('%Y-%m-%d'), end=end_date.strftime('%Y-%m-%d'), interval='1d')

# Reset index if needed and ensure correct column naming
data = data.reset_index()

# Filter data only for BTC-USD if 'symbol' column exists, if other BTC-USD, it removes them
if 'symbol' in data.columns:
    data = data[data['symbol'] == 'BTC-USD']

/usr/local/lib/python3.10/dist-packages/yahooquery/utils/__init__.py:1470: FutureWarning: 'S' is deprecated and will be removed in a future version. Please use 's' instead of 'S'.
  has_live_indice = index_utc[-1] >= last_trade - pd.Timedelta(2, "S")

In [5]:
data.head()

,symbol,date,open,high,low,close,volume,adjclose
0,BTC-USD,2023-03-01,23150.929688,23880.632812,23088.626953,23646.550781,24662841200,23646.550781
1,BTC-USD,2023-03-02,23647.019531,23739.138672,23245.021484,23475.466797,20386398516,23475.466797
2,BTC-USD,2023-03-03,23476.632812,23479.347656,22213.238281,22362.679688,26062404610,22362.679688
3,BTC-USD,2023-03-04,22362.923828,22405.177734,22198.980469,22353.349609,11166012913,22353.349609
4,BTC-USD,2023-03-05,22354.144531,22613.685547,22307.142578,22435.513672,13317001733,22435.513672

In [6]:
data.tail()

,symbol,date,open,high,low,close,volume,adjclose
726,BTC-USD,2025-02-24,96277.960938,96503.453125,91371.742188,91418.171875,44046480529,91418.171875
727,BTC-USD,2025-02-25,91437.117188,92511.078125,86008.234375,88736.171875,92139104128,88736.171875
728,BTC-USD,2025-02-26,88638.890625,89286.250000,82131.898438,84347.023438,64597492134,84347.023438
729,BTC-USD,2025-02-27,84076.859375,87000.781250,83144.960938,84704.226562,52659591954,84704.226562
730,BTC-USD,2025-02-28 13:27:00+00:00,84671.164062,84770.367188,78411.039062,80685.062500,82173378560,80685.062500

In [7]:
data.shape

(731, 8)

In [8]:
data.columns

Index(['symbol', 'date', 'open', 'high', 'low', 'close', 'volume', 'adjclose'], dtype='object')

In [9]:
import plotly.graph_objects as go
figure = go.Figure(data=[go.Candlestick(x=data['date'],
                                        open=data['open'], 
                                        high=data['high'],
                                        low=data['low'], 
                                        close=data['close'])])
figure.update_layout(title="Bitcoin Price Analysis", 
                     xaxis_rangeslider_visible=False)
figure.show()

In [10]:
#finding the correlation by selecting only numbers
correlation = data.select_dtypes(include=['number']).corr()
print(correlation["close"].sort_values(ascending=False))

close       1.000000
adjclose    1.000000
high        0.999257
low         0.998982
open        0.998025
volume      0.665623
Name: close, dtype: float64

In [11]:
!pip install autots

Collecting autots
  Downloading autots-0.6.19-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.10/dist-packages (from autots) (1.26.4)
Requirement already satisfied: pandas>=0.25.0 in /usr/local/lib/python3.10/dist-packages (from autots) (2.2.3)
Requirement already satisfied: statsmodels>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from autots) (0.14.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from autots) (1.2.2)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.6->autots) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.6->autots) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.6->autots) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.6->autots) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.6->autots) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.6->autots) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.0->autots) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.0->autots) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.0->autots) (2025.1)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->autots) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->autots) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->autots) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.10.0->autots) (1.0.1)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.10.0->autots) (24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.0->autots) (1.17.0)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.14.6->autots) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.14.6->autots) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy>=1.14.6->autots) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy>=1.14.6->autots) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy>=1.14.6->autots) (2024.2.0)
Downloading autots-0.6.19-py3-none-any.whl (971 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 971.7/971.7 kB 21.5 MB/s eta 0:00:00
Installing collected packages: autots
Successfully installed autots-0.6.19

In [12]:
from autots import AutoTS

# Ensure 'date' is in datetime format
data['date'] = pd.to_datetime(data['date'], utc=True)

# Convert all timestamps to timezone-naive (removes timezone info)
data['date'] = data['date'].dt.tz_localize(None)

model = AutoTS(forecast_length=30, frequency='infer', ensemble='simple')
model = model.fit(data, date_col='date', value_col='close', id_col=None)
prediction = model.predict()
forecast = prediction.forecast
print(forecast)

Using 1 cpus for n_jobs.
Data frequency is: D, used frequency is: D
Model Number: 1 with model AverageValueNaive in generation 0 of 25
Model Number: 2 with model AverageValueNaive in generation 0 of 25
Model Number: 3 with model AverageValueNaive in generation 0 of 25
Model Number: 4 with model DatepartRegression in generation 0 of 25
Model Number: 5 with model DatepartRegression in generation 0 of 25
Model Number: 6 with model DatepartRegression in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning:

Liblinear failed to converge, increase the number of iterations.

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

Model Number: 7 with model DatepartRegression in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 0.4242
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4160
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4155
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4123
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4146
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4104
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4076
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4043
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4039
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3987
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3967
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3954
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3968
Epoch 14/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3965
Epoch 15/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3913
Epoch 16/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3940
Epoch 17/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3895
Epoch 18/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3920
Epoch 19/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3911
Epoch 20/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3976
Epoch 21/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3903
Epoch 22/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3896
Epoch 23/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3937
Epoch 24/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3909
Epoch 25/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3920
Epoch 26/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3911
Epoch 27/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3903
Epoch 28/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3890
Epoch 29/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3893
Epoch 30/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3854
Epoch 31/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3918
Epoch 32/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3888
Epoch 33/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3885
Epoch 34/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3863
Epoch 35/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3860
Epoch 36/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3882
Epoch 37/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3901
Epoch 38/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3886
Epoch 39/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3881
Epoch 40/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3884
Epoch 41/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3856
Epoch 42/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3856
Epoch 43/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3842
Epoch 44/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3836
Epoch 45/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3861
Epoch 46/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3850
Epoch 47/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3853
Epoch 48/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3837
Epoch 49/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3830
Epoch 50/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3800
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 748ms/step
Model Number: 8 with model ETS in generation 0 of 25
Model Number: 9 with model ETS in generation 0 of 25
Model Number: 10 with model GLM in generation 0 of 25
Model Number: 11 with model GLM in generation 0 of 25
Model Number: 12 with model GLS in generation 0 of 25
Model Number: 13 with model GLS in generation 0 of 25
Model Number: 14 with model LastValueNaive in generation 0 of 25
Model Number: 15 with model LastValueNaive in generation 0 of 25
Model Number: 16 with model LastValueNaive in generation 0 of 25
Model Number: 17 with model LastValueNaive in generation 0 of 25
Model Number: 18 with model SeasonalNaive in generation 0 of 25
Model Number: 19 with model SeasonalNaive in generation 0 of 25
Model Number: 20 with model SeasonalNaive in generation 0 of 25
Model Number: 21 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 21 in generation 0: VAR
Model Number: 22 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 22 in generation 0: VAR
Model Number: 23 with model WindowRegression in generation 0 of 25
Model Number: 24 with model ConstantNaive in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

Model Number: 25 with model FBProphet in generation 0 of 25

13:30:27 - cmdstanpy - INFO - Chain [1] start processing
13:30:27 - cmdstanpy - INFO - Chain [1] done processing

Model Number: 26 with model DatepartRegression in generation 0 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 26 in generation 0: DatepartRegression
Model Number: 27 with model SeasonalNaive in generation 0 of 25
Model Number: 28 with model DatepartRegression in generation 0 of 25
Model Number: 29 with model ETS in generation 0 of 25
Model Number: 30 with model ARDL in generation 0 of 25
Model Number: 31 with model UnivariateMotif in generation 0 of 25
Model Number: 32 with model UnivariateMotif in generation 0 of 25
Model Number: 33 with model SectionalMotif in generation 0 of 25
Model Number: 34 with model SectionalMotif in generation 0 of 25
Model Number: 35 with model FBProphet in generation 0 of 25
Model Number: 36 with model SeasonalNaive in generation 0 of 25
Model Number: 37 with model DatepartRegression in generation 0 of 25
Model Number: 38 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 38 in generation 0: ARCH
Model Number: 39 with model Cassandra in generation 0 of 25
Model Number: 40 with model SeasonalityMotif in generation 0 of 25
Model Number: 41 with model Cassandra in generation 0 of 25
Model Number: 42 with model Cassandra in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 43 with model Cassandra in generation 0 of 25
Model Number: 44 with model SectionalMotif in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 45 with model FBProphet in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

Model Number: 46 with model ARDL in generation 0 of 25
Model Number: 47 with model FFT in generation 0 of 25
Model Number: 48 with model BasicLinearModel in generation 0 of 25
Template Eval Error: ValueError('matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 701 is different from 1966)') in model 48 in generation 0: BasicLinearModel
Model Number: 49 with model BasicLinearModel in generation 0 of 25
Model Number: 50 with model SeasonalityMotif in generation 0 of 25
Model Number: 51 with model BasicLinearModel in generation 0 of 25
Model Number: 52 with model ETS in generation 0 of 25
Model Number: 53 with model FBProphet in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

Model Number: 54 with model GLM in generation 0 of 25
Model Number: 55 with model UnivariateMotif in generation 0 of 25
Model Number: 56 with model ARDL in generation 0 of 25
Model Number: 57 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 57 in generation 0: ARCH
Model Number: 58 with model ConstantNaive in generation 0 of 25
Model Number: 59 with model LastValueNaive in generation 0 of 25
Model Number: 60 with model AverageValueNaive in generation 0 of 25
Model Number: 61 with model GLS in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 62 with model SeasonalNaive in generation 0 of 25
Model Number: 63 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 63 in generation 0: VAR
Model Number: 64 with model WindowRegression in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 65 with model DatepartRegression in generation 0 of 25
Model Number: 66 with model SectionalMotif in generation 0 of 25
Model Number: 67 with model RRVAR in generation 0 of 25
Model Number: 68 with model MetricMotif in generation 0 of 25
Model Number: 69 with model Cassandra in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

Model Number: 70 with model SeasonalityMotif in generation 0 of 25
Model Number: 71 with model FFT in generation 0 of 25
Model Number: 72 with model BasicLinearModel in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 73 with model AverageValueNaive in generation 0 of 25
Model Number: 74 with model GLS in generation 0 of 25
Model Number: 75 with model LastValueNaive in generation 0 of 25
Model Number: 76 with model GLM in generation 0 of 25
Model Number: 77 with model MetricMotif in generation 0 of 25
Model Number: 78 with model FBProphet in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

No anomalies detected.
Model Number: 79 with model FBProphet in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 80 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 80 in generation 0: VAR
Model Number: 81 with model SeasonalityMotif in generation 0 of 25
Model Number: 82 with model ETS in generation 0 of 25
Model Number: 83 with model FFT in generation 0 of 25
Model Number: 84 with model SeasonalityMotif in generation 0 of 25
Model Number: 85 with model AverageValueNaive in generation 0 of 25
Model Number: 86 with model GLM in generation 0 of 25
Template Eval Error: ValueError('operands could not be broadcast together with shapes (120,1) (30,1) ') in model 86 in generation 0: GLM
Model Number: 87 with model LastValueNaive in generation 0 of 25
Model Number: 88 with model ETS in generation 0 of 25
Model Number: 89 with model SeasonalNaive in generation 0 of 25
Model Number: 90 with model SeasonalityMotif in generation 0 of 25
Model Number: 91 with model FFT in generation 0 of 25
Model Number: 92 with model RRVAR in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 93 with model GLM in generation 0 of 25
Template Eval Error: ValueError('regression_type=user and no future_regressor passed') in model 93 in generation 0: GLM
Model Number: 94 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 94 in generation 0: VAR
Model Number: 95 with model SeasonalNaive in generation 0 of 25
Model Number: 96 with model ARDL in generation 0 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 96 in generation 0: ARDL
Model Number: 97 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 97 in generation 0: ARCH
Model Number: 98 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 98 in generation 0: ARCH
Model Number: 99 with model GLM in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 100 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 100 in generation 0: VAR
Model Number: 101 with model FBProphet in generation 0 of 25
Model Number: 102 with model ARDL in generation 0 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 102 in generation 0: ARDL
Model Number: 103 with model AverageValueNaive in generation 0 of 25
Model Number: 104 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 104 in generation 0: VAR
Model Number: 105 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 105 in generation 0: ARCH
Model Number: 106 with model SeasonalNaive in generation 0 of 25
Model Number: 107 with model LastValueNaive in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 108 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 108 in generation 0: VAR
Model Number: 109 with model FBProphet in generation 0 of 25
Model Number: 110 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 110 in generation 0: ARCH
Model Number: 111 with model BasicLinearModel in generation 0 of 25
Model Number: 112 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 112 in generation 0: VAR
Model Number: 113 with model ARDL in generation 0 of 25
Model Number: 114 with model AverageValueNaive in generation 0 of 25
Model Number: 115 with model GLS in generation 0 of 25
Model Number: 116 with model SeasonalNaive in generation 0 of 25
Model Number: 117 with model BasicLinearModel in generation 0 of 25
Model Number: 118 with model SectionalMotif in generation 0 of 25
Template Eval Error: Exception('Transformer PCA failed on fit from params ffill {\'0\': {\'whiten\': True, \'n_components\': 100}, \'1\': {\'model\': \'ElasticNet\', \'changepoint_spacing\': 5040, \'changepoint_distance_end\': 180, \'datepart_method\': \'simple\'}} with error ValueError("n_components=100 must be between 0 and min(n_samples, n_features)=1 with svd_solver=\'full\'")') in model 118 in generation 0: SectionalMotif
Model Number: 119 with model MetricMotif in generation 0 of 25
Model Number: 120 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 120 in generation 0: VAR
Model Number: 121 with model SeasonalNaive in generation 0 of 25
Model Number: 122 with model SeasonalityMotif in generation 0 of 25
Model Number: 123 with model FFT in generation 0 of 25
Model Number: 124 with model ARDL in generation 0 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 124 in generation 0: ARDL
Model Number: 125 with model FFT in generation 0 of 25
Model Number: 126 with model ETS in generation 0 of 25
Model Number: 127 with model SectionalMotif in generation 0 of 25
Model Number: 128 with model LastValueNaive in generation 0 of 25
Model Number: 129 with model UnivariateMotif in generation 0 of 25
Model Number: 130 with model UnivariateMotif in generation 0 of 25
Model Number: 131 with model GLS in generation 0 of 25
Model Number: 132 with model ARDL in generation 0 of 25
Model Number: 133 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 133 in generation 0: ARCH
Model Number: 134 with model VAR in generation 0 of 25
Template Eval Error: IndexError('tuple index out of range') in model 134 in generation 0: VAR
Model Number: 135 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 135 in generation 0: ARCH
Model Number: 136 with model UnivariateMotif in generation 0 of 25
Model Number: 137 with model DatepartRegression in generation 0 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 137 in generation 0: DatepartRegression
Model Number: 138 with model LastValueNaive in generation 0 of 25
Model Number: 139 with model SeasonalNaive in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 140 with model SeasonalityMotif in generation 0 of 25
Model Number: 141 with model LastValueNaive in generation 0 of 25
Model Number: 142 with model SeasonalityMotif in generation 0 of 25
Model Number: 143 with model FBProphet in generation 0 of 25
Template Eval Error: Exception("Transformer HolidayTransformer failed on fit from params ffill_mean_biased {'0': {'rows': 168, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'mean'}, '1': {'threshold': 0.7, 'splash_threshold': None, 'use_dayofmonth_holidays': True, 'use_wkdom_holidays': True, 'use_wkdeom_holidays': False, 'use_lunar_holidays': False, 'use_lunar_weekday': True, 'use_islamic_holidays': False, 'use_hebrew_holidays': False, 'use_hindu_holidays': False, 'anomaly_detector_params': {'method': 'rolling_zscore', 'method_params': {'distribution': 'norm', 'alpha': 0.05, 'rolling_periods': 28, 'center': False}, 'fillna': 'ffill', 'transform_dict': {'transformations': {'0': 'DatepartRegression'}, 'transformation_params': {'0': {'datepart_method': 'simple_3', 'regression_model': {'model': 'FastRidge', 'model_params': {}}}}}, 'isolated_only': False, 'on_inverse': False}, 'remove_excess_anomalies': False, 'impact': 'datepart_regression', 'regression_params': {'regression_model': {'model': 'ElasticNet', 'model_params': {'l1_ratio': 0.5, 'fit_intercept': True, 'selection': 'cyclic', 'max_iter': 1000}}, 'datepart_method': 'expanded_binarized', 'polynomial_degree': None, 'transform_dict': None, 'holiday_countries_used': False, 'lags': None, 'forward_lags': 2}}, '2': {'model': 'GLS', 'phi': 1, 'window': 365, 'transform_dict': None}, '3': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'mean'}, '4': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'max'}} with error ValueError('Found input variables with inconsistent numbers of samples: [1966, 701]')") in model 143 in generation 0: FBProphet
Model Number: 144 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 144 in generation 0: ARCH
Model Number: 145 with model ConstantNaive in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 146 with model GLM in generation 0 of 25
2025-01-30 00:00:00
2025-01-30 00:00:00
2025-01-30 00:00:00
Template Eval Error: ValueError('Model GLM returned improper forecast_length. Returned: 25 and requested: 30') in model 146 in generation 0: GLM
Model Number: 147 with model SeasonalityMotif in generation 0 of 25
Model Number: 148 with model ARDL in generation 0 of 25
Model Number: 149 with model ARDL in generation 0 of 25
Model Number: 150 with model ConstantNaive in generation 0 of 25
Model Number: 151 with model SeasonalityMotif in generation 0 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 152 with model ARDL in generation 0 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 152 in generation 0: ARDL
Model Number: 153 with model ConstantNaive in generation 0 of 25
Model Number: 154 with model FFT in generation 0 of 25
Model Number: 155 with model ETS in generation 0 of 25
Model Number: 156 with model GLS in generation 0 of 25
New Generation: 1 of 25
Model Number: 157 with model Cassandra in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 158 with model BasicLinearModel in generation 1 of 25
Model Number: 159 with model SeasonalNaive in generation 1 of 25
Model Number: 160 with model ETS in generation 1 of 25
Model Number: 161 with model GLM in generation 1 of 25
Model Number: 162 with model FFT in generation 1 of 25
Model Number: 163 with model SectionalMotif in generation 1 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params linear {'0': {'det_order': -1, 'k_ar_diff': 0}, '1': {'discretization': 'lower', 'n_bins': 50}, '2': {'lag_1': 7, 'method': 2}} with error ValueError('Coint only works on multivarate series')") in model 163 in generation 1: SectionalMotif
Model Number: 164 with model GLM in generation 1 of 25
Model Number: 165 with model FBProphet in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 166 with model UnivariateMotif in generation 1 of 25
Model Number: 167 with model ConstantNaive in generation 1 of 25
Model Number: 168 with model UnivariateMotif in generation 1 of 25
Model Number: 169 with model SeasonalityMotif in generation 1 of 25
Model Number: 170 with model GLS in generation 1 of 25
Model Number: 171 with model FFT in generation 1 of 25
Model Number: 172 with model LastValueNaive in generation 1 of 25
Model Number: 173 with model FFT in generation 1 of 25
Model Number: 174 with model SectionalMotif in generation 1 of 25
Model Number: 175 with model AverageValueNaive in generation 1 of 25
Model Number: 176 with model UnivariateMotif in generation 1 of 25
Model Number: 177 with model SeasonalityMotif in generation 1 of 25
Model Number: 178 with model SeasonalityMotif in generation 1 of 25
Model Number: 179 with model DatepartRegression in generation 1 of 25
Template Eval Error: Exception("Transformer FIRFilter failed on fit from params zero {'0': {'constraint_method': 'dampening', 'constraint_direction': 'upper', 'constraint_regularization': 1.0, 'constraint_value': 0.9999, 'bounds_only': False, 'fillna': None}, '1': {'rows': 1, 'lag': 2, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}, '2': {'numtaps': 128, 'cutoff_hz': 20, 'window': 'hamming', 'sampling_frequency': 7, 'on_transform': True, 'on_inverse': False}, '3': {'output_distribution': 'uniform', 'n_quantiles': 233}} with error ValueError('Invalid cutoff frequency: frequencies must be greater than 0 and less than fs/2.')") in model 179 in generation 1: DatepartRegression
Model Number: 180 with model SectionalMotif in generation 1 of 25
Model Number: 181 with model AverageValueNaive in generation 1 of 25
Model Number: 182 with model SeasonalNaive in generation 1 of 25
Model Number: 183 with model MetricMotif in generation 1 of 25
Model Number: 184 with model FFT in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

SVD did not converge, attempting more robust approach...
Template Eval Error: Exception("Transformer KalmanSmoothing failed on fit from params linear {'0': {'model_name': 'ucm_deterministic_trend', 'state_transition': [[1, 1], [0, 1]], 'process_noise': [[0.01, 0], [0, 0.01]], 'observation_model': [[1, 0]], 'observation_noise': 0.1, 'em_iter': 10, 'on_transform': True, 'on_inverse': False}, '1': {'model_name': 'factor', 'state_transition': [[1, 1, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 1, 0], [0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 1]], 'process_noise': [[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0]], 'observation_model': [[1, 0, 0, 0, 0, 0]], 'observation_noise': 0.04, 'em_iter': 30, 'on_transform': True, 'on_inverse': False}, '2': {'lag': 1, 'fill': 'bfill'}, '3': {'rolling_window': 0.05, 'n_tails': 0.1, 'n_future': 0.2, 'method': 'median', 'macro_micro': True}} with error LinAlgError('SVD did not converge')") in model 184 in generation 1: FFT
Model Number: 185 with model GLM in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/fast_kalman.py:1137: RuntimeWarning:

overflow encountered in cast

/usr/local/lib/python3.10/dist-packages/autots/tools/fast_kalman.py:1354: RuntimeWarning:

invalid value encountered in matmul

/usr/local/lib/python3.10/dist-packages/autots/tools/fast_kalman.py:1341: RuntimeWarning:

invalid value encountered in matmul

Model Number: 186 with model MetricMotif in generation 1 of 25
Model Number: 187 with model SectionalMotif in generation 1 of 25
2025-01-30 00:00:00
2025-01-30 00:00:00
2025-01-30 00:00:00
Template Eval Error: ValueError('Model SectionalMotif returned improper forecast_length. Returned: 25 and requested: 30') in model 187 in generation 1: SectionalMotif
Model Number: 188 with model GLM in generation 1 of 25
Template Eval Error: ValueError('The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.') in model 188 in generation 1: GLM
Model Number: 189 with model Cassandra in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 190 with model FBProphet in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 191 with model DatepartRegression in generation 1 of 25
Model Number: 192 with model SeasonalityMotif in generation 1 of 25
2025-01-30 00:00:00
2025-01-30 00:00:00
2025-01-30 00:00:00
Template Eval Error: ValueError('Model SeasonalityMotif returned improper forecast_length. Returned: 29 and requested: 30') in model 192 in generation 1: SeasonalityMotif
Model Number: 193 with model AverageValueNaive in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning:

Liblinear failed to converge, increase the number of iterations.

Model Number: 194 with model FBProphet in generation 1 of 25
Model Number: 195 with model MetricMotif in generation 1 of 25
Model Number: 196 with model FFT in generation 1 of 25
Model Number: 197 with model ConstantNaive in generation 1 of 25
Model Number: 198 with model UnivariateMotif in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 199 with model BasicLinearModel in generation 1 of 25
Model Number: 200 with model ConstantNaive in generation 1 of 25
Model Number: 201 with model ETS in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 202 with model DatepartRegression in generation 1 of 25
Model Number: 203 with model MetricMotif in generation 1 of 25
Model Number: 204 with model FBProphet in generation 1 of 25
Model Number: 205 with model SeasonalNaive in generation 1 of 25
Model Number: 206 with model FBProphet in generation 1 of 25
Model Number: 207 with model SeasonalNaive in generation 1 of 25
Model Number: 208 with model Cassandra in generation 1 of 25
Model Number: 209 with model LastValueNaive in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

Model Number: 210 with model AverageValueNaive in generation 1 of 25
Model Number: 211 with model WindowRegression in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

Model Number: 212 with model Cassandra in generation 1 of 25
Model Number: 213 with model FBProphet in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 214 with model FBProphet in generation 1 of 25
Model Number: 215 with model ARDL in generation 1 of 25
Model Number: 216 with model SeasonalityMotif in generation 1 of 25
Model Number: 217 with model ARDL in generation 1 of 25
Model Number: 218 with model ARDL in generation 1 of 25
Model Number: 219 with model FFT in generation 1 of 25
Model Number: 220 with model LastValueNaive in generation 1 of 25
Model Number: 221 with model FFT in generation 1 of 25
Model Number: 222 with model BasicLinearModel in generation 1 of 25
Model Number: 223 with model AverageValueNaive in generation 1 of 25
Model Number: 224 with model ETS in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 225 with model SeasonalNaive in generation 1 of 25
Model Number: 226 with model WindowRegression in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 227 with model ETS in generation 1 of 25
Model Number: 228 with model UnivariateMotif in generation 1 of 25
Model Number: 229 with model SeasonalNaive in generation 1 of 25
Model Number: 230 with model ARDL in generation 1 of 25
Model Number: 231 with model DatepartRegression in generation 1 of 25
Model Number: 232 with model LastValueNaive in generation 1 of 25
Model Number: 233 with model SectionalMotif in generation 1 of 25
Model Number: 234 with model ETS in generation 1 of 25
Model Number: 235 with model FFT in generation 1 of 25
Model Number: 236 with model SeasonalityMotif in generation 1 of 25
Model Number: 237 with model Cassandra in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 238 with model UnivariateMotif in generation 1 of 25
Model Number: 239 with model LastValueNaive in generation 1 of 25
Model Number: 240 with model ConstantNaive in generation 1 of 25
Model Number: 241 with model AverageValueNaive in generation 1 of 25
Model Number: 242 with model UnivariateMotif in generation 1 of 25
Model Number: 243 with model UnivariateMotif in generation 1 of 25
Model Number: 244 with model GLS in generation 1 of 25
Model Number: 245 with model DatepartRegression in generation 1 of 25
interpolating
Model Number: 246 with model AverageValueNaive in generation 1 of 25
Model Number: 247 with model FBProphet in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 248 with model GLM in generation 1 of 25
Model Number: 249 with model SectionalMotif in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 250 with model Cassandra in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 251 with model LastValueNaive in generation 1 of 25
Model Number: 252 with model FBProphet in generation 1 of 25
Model Number: 253 with model ConstantNaive in generation 1 of 25
Model Number: 254 with model LastValueNaive in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 255 with model GLM in generation 1 of 25
Model Number: 256 with model SeasonalityMotif in generation 1 of 25
Model Number: 257 with model ETS in generation 1 of 25
Model Number: 258 with model Cassandra in generation 1 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 259 with model ConstantNaive in generation 1 of 25
Model Number: 260 with model LastValueNaive in generation 1 of 25
Model Number: 261 with model UnivariateMotif in generation 1 of 25
New Generation: 2 of 25
Model Number: 262 with model Cassandra in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 263 with model DatepartRegression in generation 2 of 25
Template Eval Error: ValueError('Input X contains NaN.\nDecisionTreeRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values') in model 263 in generation 2: DatepartRegression
Model Number: 264 with model ConstantNaive in generation 2 of 25
Model Number: 265 with model DatepartRegression in generation 2 of 25
interpolating

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 266 with model Cassandra in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 267 with model ConstantNaive in generation 2 of 25
Model Number: 268 with model ConstantNaive in generation 2 of 25
Model Number: 269 with model WindowRegression in generation 2 of 25
Model Number: 270 with model LastValueNaive in generation 2 of 25
Model Number: 271 with model SectionalMotif in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 272 with model UnivariateMotif in generation 2 of 25
Model Number: 273 with model UnivariateMotif in generation 2 of 25
Model Number: 274 with model BasicLinearModel in generation 2 of 25
Model Number: 275 with model Cassandra in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 276 with model AverageValueNaive in generation 2 of 25
Model Number: 277 with model MetricMotif in generation 2 of 25
Model Number: 278 with model UnivariateMotif in generation 2 of 25
Model Number: 279 with model SeasonalityMotif in generation 2 of 25
Model Number: 280 with model ETS in generation 2 of 25
Model Number: 281 with model SeasonalityMotif in generation 2 of 25
Model Number: 282 with model ARDL in generation 2 of 25
Model Number: 283 with model UnivariateMotif in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 284 with model DatepartRegression in generation 2 of 25
Template Eval Error: IndexError('tuple index out of range') in model 284 in generation 2: DatepartRegression
Model Number: 285 with model UnivariateMotif in generation 2 of 25
Model Number: 286 with model AverageValueNaive in generation 2 of 25
Model Number: 287 with model SeasonalityMotif in generation 2 of 25
Model Number: 288 with model MetricMotif in generation 2 of 25
Model Number: 289 with model ARDL in generation 2 of 25
2025-01-30 00:00:00
Template Eval Error: Exception("Transformer RobustScaler failed on inverse from params ffill {'0': {'window': 100}, '1': {'output_distribution': 'uniform', 'n_quantiles': 233}, '2': {}, '3': {'mode': 'downscale', 'factor': 1, 'down_method': 'decimate', 'fill_method': 'pchip'}} with ValueError('Shape of passed values is (60, 1), indices imply (30, 1)')") in model 289 in generation 2: ARDL
Model Number: 290 with model UnivariateMotif in generation 2 of 25
Model Number: 291 with model GLM in generation 2 of 25
Model Number: 292 with model FBProphet in generation 2 of 25
Model Number: 293 with model SeasonalNaive in generation 2 of 25
Model Number: 294 with model MetricMotif in generation 2 of 25
Model Number: 295 with model AverageValueNaive in generation 2 of 25
Model Number: 296 with model ConstantNaive in generation 2 of 25
Model Number: 297 with model SeasonalityMotif in generation 2 of 25
Template Eval Error: ValueError('Model SeasonalityMotif returned NaN for one or more series. fail_on_forecast_nan=True') in model 297 in generation 2: SeasonalityMotif
Model Number: 298 with model ConstantNaive in generation 2 of 25
Model Number: 299 with model SectionalMotif in generation 2 of 25
Model Number: 300 with model SectionalMotif in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning:

Mean of empty slice.

/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:121: RuntimeWarning:

invalid value encountered in divide

Model Number: 301 with model FFT in generation 2 of 25
Model Number: 302 with model SectionalMotif in generation 2 of 25
Model Number: 303 with model AverageValueNaive in generation 2 of 25
Model Number: 304 with model Cassandra in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 305 with model ARDL in generation 2 of 25
Model Number: 306 with model LastValueNaive in generation 2 of 25
Model Number: 307 with model MetricMotif in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 308 with model FBProphet in generation 2 of 25
Model Number: 309 with model FBProphet in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

Model Number: 310 with model ARDL in generation 2 of 25
Model Number: 311 with model LastValueNaive in generation 2 of 25
Model Number: 312 with model FBProphet in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 313 with model FBProphet in generation 2 of 25
Model Number: 314 with model SectionalMotif in generation 2 of 25
Model Number: 315 with model UnivariateMotif in generation 2 of 25
Model Number: 316 with model SectionalMotif in generation 2 of 25
Model Number: 317 with model FFT in generation 2 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params rolling_mean_24 {'0': {'output_distribution': 'uniform', 'n_quantiles': 233}, '1': {'output_distribution': 'uniform', 'n_quantiles': 233}, '2': {'det_order': -1, 'k_ar_diff': 2}, '3': {'method': 'clip', 'std_threshold': 1, 'fillna': None}} with error ValueError('Coint only works on multivarate series')") in model 317 in generation 2: FFT
Model Number: 318 with model SeasonalNaive in generation 2 of 25
Model Number: 319 with model GLM in generation 2 of 25
Model Number: 320 with model AverageValueNaive in generation 2 of 25
Model Number: 321 with model Cassandra in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 322 with model BasicLinearModel in generation 2 of 25
Model Number: 323 with model DatepartRegression in generation 2 of 25
Model Number: 324 with model ARDL in generation 2 of 25
Model Number: 325 with model MetricMotif in generation 2 of 25
Model Number: 326 with model MetricMotif in generation 2 of 25
Model Number: 327 with model ETS in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 328 with model ConstantNaive in generation 2 of 25
Model Number: 329 with model ARDL in generation 2 of 25
Model Number: 330 with model FFT in generation 2 of 25
Model Number: 331 with model LastValueNaive in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 332 with model Cassandra in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 333 with model SeasonalityMotif in generation 2 of 25
Model Number: 334 with model FBProphet in generation 2 of 25
Model Number: 335 with model AverageValueNaive in generation 2 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params rolling_mean_24 {'0': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gbtree', 'max_depth': 2, 'eta': 0.3, 'min_child_weight': 1, 'subsample': 1, 'colsample_bylevel': 1, 'reg_alpha': 0, 'reg_lambda': 1, 'n_estimators': 10}, 'datepart_method': 'common_fourier'}, 'fillna': 'mean'}, '1': {'model': 'Tweedie', 'phi': 1, 'window': 30, 'transform_dict': None}, '2': {'method': 'rolling_zscore', 'method_params': {'distribution': 'norm', 'alpha': 0.01, 'rolling_periods': 300, 'center': False}, 'fillna': 'linear', 'transform_dict': {'fillna': 'quadratic', 'transformations': {'0': 'bkfilter', '1': 'bkfilter'}, 'transformation_params': {'0': {}, '1': {}}}, 'isolated_only': False, 'on_inverse': False}, '3': {}, '4': {}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 335 in generation 2: AverageValueNaive
Model Number: 336 with model LastValueNaive in generation 2 of 25
Model Number: 337 with model SeasonalNaive in generation 2 of 25
Model Number: 338 with model SeasonalityMotif in generation 2 of 25
Model Number: 339 with model SeasonalNaive in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 340 with model SeasonalityMotif in generation 2 of 25
Model Number: 341 with model WindowRegression in generation 2 of 25
Template Eval Error: XGBoostError('[13:31:58] /workspace/include/xgboost/objective.h:104: multioutput is not supported by current objective function\nStack trace:\n  [bt] (0) /usr/local/lib/python3.10/dist-packages/xgboost/lib/libxgboost.so(+0x48c70a) [0x7e149b8ae70a]\n  [bt] (1) /usr/local/lib/python3.10/dist-packages/xgboost/lib/libxgboost.so(+0x4bfee7) [0x7e149b8e1ee7]\n  [bt] (2) /usr/local/lib/python3.10/dist-packages/xgboost/lib/libxgboost.so(+0x4ccd7d) [0x7e149b8eed7d]\n  [bt] (3) /usr/local/lib/python3.10/dist-packages/xgboost/lib/libxgboost.so(+0x4c5268) [0x7e149b8e7268]\n  [bt] (4) /usr/local/lib/python3.10/dist-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x70) [0x7e149b583ef0]\n  [bt] (5) /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e) [0x7e15d8a14e2e]\n  [bt] (6) /lib/x86_64-linux-gnu/libffi.so.8(+0x4493) [0x7e15d8a11493]\n  [bt] (7) /usr/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0xa3e9) [0x7e15d8a3b3e9]\n  [bt] (8) /usr/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x9a00) [0x7e15d8a3aa00]\n\n') in model 341 in generation 2: WindowRegression
Model Number: 342 with model SeasonalityMotif in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 343 with model MetricMotif in generation 2 of 25
Model Number: 344 with model GLS in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 345 with model GLS in generation 2 of 25
Model Number: 346 with model FBProphet in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

Model Number: 347 with model SeasonalityMotif in generation 2 of 25
Model Number: 348 with model DatepartRegression in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning:

Liblinear failed to converge, increase the number of iterations.

Model Number: 349 with model AverageValueNaive in generation 2 of 25
Model Number: 350 with model ConstantNaive in generation 2 of 25
Model Number: 351 with model UnivariateMotif in generation 2 of 25
Model Number: 352 with model FFT in generation 2 of 25
Model Number: 353 with model MetricMotif in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 354 with model GLM in generation 2 of 25
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 354 in generation 2: GLM
Model Number: 355 with model MetricMotif in generation 2 of 25
Model Number: 356 with model SeasonalNaive in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/generalized_linear_model.py:308: DomainWarning:

The InversePower link function does not respect the domain of the Gamma family.

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

overflow encountered in square

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/links.py:325: RuntimeWarning:

divide by zero encountered in power

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:775: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/generalized_linear_model.py:898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/generalized_linear_model.py:1328: RuntimeWarning:

invalid value encountered in multiply

Model Number: 357 with model ETS in generation 2 of 25
Model Number: 358 with model UnivariateMotif in generation 2 of 25
Model Number: 359 with model ConstantNaive in generation 2 of 25
Model Number: 360 with model MetricMotif in generation 2 of 25
Model Number: 361 with model RRVAR in generation 2 of 25
Model Number: 362 with model UnivariateMotif in generation 2 of 25
Model Number: 363 with model SeasonalityMotif in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 364 with model ConstantNaive in generation 2 of 25
Model Number: 365 with model Cassandra in generation 2 of 25
Model Number: 366 with model MetricMotif in generation 2 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

New Generation: 3 of 25
Model Number: 367 with model GLM in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

Model Number: 368 with model Cassandra in generation 3 of 25
Model Number: 369 with model MetricMotif in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 370 with model ConstantNaive in generation 3 of 25
Model Number: 371 with model Cassandra in generation 3 of 25
Model Number: 372 with model RRVAR in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 373 with model FBProphet in generation 3 of 25
Model Number: 374 with model SectionalMotif in generation 3 of 25
Model Number: 375 with model SectionalMotif in generation 3 of 25
Model Number: 376 with model Cassandra in generation 3 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 376 in generation 3: Cassandra
Model Number: 377 with model FFT in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 378 with model SeasonalNaive in generation 3 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params ffill {'0': {}, '1': {}, '2': {'det_order': 1, 'k_ar_diff': 0}, '3': {}} with error ValueError('Coint only works on multivarate series')") in model 378 in generation 3: SeasonalNaive
Model Number: 379 with model BasicLinearModel in generation 3 of 25
Model Number: 380 with model UnivariateMotif in generation 3 of 25
Template Eval Error: ValueError('Model UnivariateMotif returned NaN for one or more series. fail_on_forecast_nan=True') in model 380 in generation 3: UnivariateMotif
Model Number: 381 with model MetricMotif in generation 3 of 25
Model Number: 382 with model GLS in generation 3 of 25
Model Number: 383 with model MetricMotif in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:49: RuntimeWarning:

invalid value encountered in reduce

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:553: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 384 with model SeasonalityMotif in generation 3 of 25
Model Number: 385 with model Cassandra in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 385 in generation 3: Cassandra
Model Number: 386 with model MetricMotif in generation 3 of 25
Model Number: 387 with model Cassandra in generation 3 of 25
Model Number: 388 with model ARDL in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 389 with model ETS in generation 3 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params ffill {'0': {'det_order': -1, 'k_ar_diff': 2}, '1': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 3, 'threshold_method': 'mean'}, '2': {}} with error ValueError('Coint only works on multivarate series')") in model 389 in generation 3: ETS
Model Number: 390 with model MetricMotif in generation 3 of 25
Model Number: 391 with model UnivariateMotif in generation 3 of 25
Model Number: 392 with model ConstantNaive in generation 3 of 25
Model Number: 393 with model LastValueNaive in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.655e+10, tolerance: 3.820e+07

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 394 with model LastValueNaive in generation 3 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params rolling_mean_24 {'0': {'lag_1': 96, 'method': 2}, '1': {'model': 'ElasticNet', 'changepoint_spacing': 28, 'changepoint_distance_end': 90, 'datepart_method': None}, '2': {'method': 'savgol_filter', 'method_args': {'window_length': 31, 'polyorder': 3, 'deriv': 0, 'mode': 'mirror'}}, '3': {'det_order': 1, 'k_ar_diff': 1}} with error ValueError('Coint only works on multivarate series')") in model 394 in generation 3: LastValueNaive
Model Number: 395 with model RRVAR in generation 3 of 25
Model Number: 396 with model ConstantNaive in generation 3 of 25
Model Number: 397 with model DatepartRegression in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 398 with model AverageValueNaive in generation 3 of 25
Model Number: 399 with model ETS in generation 3 of 25
Model Number: 400 with model FFT in generation 3 of 25
Model Number: 401 with model ARDL in generation 3 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 401 in generation 3: ARDL
Model Number: 402 with model ETS in generation 3 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params pchip {'0': {'rows': 1, 'lag': 2, 'method': 'multiplicative', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'mean'}, '1': {'part': 'trend', 'lamb': 4}, '2': {'method': 100}, '3': {'det_order': -1, 'k_ar_diff': 0}, '4': {}} with error ValueError('Coint only works on multivarate series')") in model 402 in generation 3: ETS
Model Number: 403 with model Cassandra in generation 3 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 403 in generation 3: Cassandra
Model Number: 404 with model SectionalMotif in generation 3 of 25
Model Number: 405 with model Cassandra in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Template Eval Error: ValueError('Multivariate Transformer not usable for this role.') in model 405 in generation 3: Cassandra
Model Number: 406 with model SectionalMotif in generation 3 of 25
Model Number: 407 with model MetricMotif in generation 3 of 25
Model Number: 408 with model GLS in generation 3 of 25
Model Number: 409 with model GLS in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 410 with model ETS in generation 3 of 25
Model Number: 411 with model MetricMotif in generation 3 of 25
Model Number: 412 with model MetricMotif in generation 3 of 25
Model Number: 413 with model UnivariateMotif in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 414 with model ETS in generation 3 of 25
Model Number: 415 with model ARDL in generation 3 of 25
Model Number: 416 with model LastValueNaive in generation 3 of 25
Model Number: 417 with model FFT in generation 3 of 25
Model Number: 418 with model ConstantNaive in generation 3 of 25
Model Number: 419 with model UnivariateMotif in generation 3 of 25
Model Number: 420 with model BasicLinearModel in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 421 with model SectionalMotif in generation 3 of 25
Model Number: 422 with model SeasonalNaive in generation 3 of 25
Model Number: 423 with model SeasonalNaive in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 424 with model FBProphet in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 425 with model UnivariateMotif in generation 3 of 25
Model Number: 426 with model MetricMotif in generation 3 of 25
Model Number: 427 with model SectionalMotif in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 428 with model BasicLinearModel in generation 3 of 25
Model Number: 429 with model AverageValueNaive in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 430 with model FBProphet in generation 3 of 25
Model Number: 431 with model SectionalMotif in generation 3 of 25
Model Number: 432 with model ConstantNaive in generation 3 of 25
Model Number: 433 with model ConstantNaive in generation 3 of 25
Model Number: 434 with model ConstantNaive in generation 3 of 25
Model Number: 435 with model ETS in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 436 with model LastValueNaive in generation 3 of 25
Model Number: 437 with model FBProphet in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 438 with model ConstantNaive in generation 3 of 25
Model Number: 439 with model SectionalMotif in generation 3 of 25
Template Eval Error: Exception("Transformer DatepartRegression failed on fit from params linear {'0': {'constant': 0, 'reintroduction_model': {'model': 'KNN', 'model_params': {'n_neighbors': 5, 'weights': 'uniform', 'p': 2, 'leaf_size': 30}, 'datepart_method': 'common_fourier'}, 'fillna': 'linear'}, '1': {}, '2': {'regression_model': {'model': 'ElasticNetwork', 'model_params': {'size': 64, 'l1': 0.0, 'l2': 0.0, 'epochs': 50, 'batch_size': 32, 'optimizer': 'rmsprop', 'loss': 'mse'}}, 'datepart_method': 'common_fourier', 'polynomial_degree': None, 'transform_dict': {'fillna': None, 'transformations': {'0': 'ClipOutliers'}, 'transformation_params': {'0': {'method': 'clip', 'std_threshold': 4}}}, 'holiday_countries_used': False, 'lags': None, 'forward_lags': 2}, '3': {'method': 'rolling_zscore', 'method_params': {'distribution': 'uniform', 'alpha': 0.05, 'rolling_periods': 28, 'center': False}, 'fillna': 'rolling_mean_24', 'transform_dict': {'fillna': 'linear', 'transformations': {'0': 'EWMAFilter', '1': 'LevelShiftTransformer'}, 'transformation_params': {'0': {'span': 10}, '1': {'window_size': 90, 'alpha': 3.0, 'grouping_forward_limit': 3, 'max_level_shifts': 5, 'alignment': 'average'}}}, 'isolated_only': False, 'on_inverse': False}} with error IndexError('tuple index out of range')") in model 439 in generation 3: SectionalMotif
Model Number: 440 with model LastValueNaive in generation 3 of 25
2025-01-30 00:00:00
2025-01-30 00:00:00
2025-01-30 00:00:00
Template Eval Error: ValueError('Model LastValueNaive returned improper forecast_length. Returned: 29 and requested: 30') in model 440 in generation 3: LastValueNaive
Model Number: 441 with model ConstantNaive in generation 3 of 25
Model Number: 442 with model SeasonalityMotif in generation 3 of 25
Model Number: 443 with model MetricMotif in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 444 with model SectionalMotif in generation 3 of 25
Model Number: 445 with model FBProphet in generation 3 of 25
Model Number: 446 with model AverageValueNaive in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 447 with model BasicLinearModel in generation 3 of 25
Model Number: 448 with model SeasonalityMotif in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 449 with model MetricMotif in generation 3 of 25
Model Number: 450 with model GLS in generation 3 of 25
Model Number: 451 with model DatepartRegression in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 452 with model FBProphet in generation 3 of 25
Model Number: 453 with model DatepartRegression in generation 3 of 25
Model Number: 454 with model ARDL in generation 3 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 454 in generation 3: ARDL
Model Number: 455 with model SeasonalNaive in generation 3 of 25
Model Number: 456 with model SeasonalityMotif in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 457 with model Cassandra in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 458 with model AverageValueNaive in generation 3 of 25
Model Number: 459 with model FBProphet in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 460 with model SeasonalityMotif in generation 3 of 25
Model Number: 461 with model UnivariateMotif in generation 3 of 25
Model Number: 462 with model ConstantNaive in generation 3 of 25
Model Number: 463 with model UnivariateMotif in generation 3 of 25
Model Number: 464 with model SeasonalityMotif in generation 3 of 25
2025-01-30 00:00:00
2025-01-30 00:00:00
2025-01-30 00:00:00
Template Eval Error: ValueError('Model SeasonalityMotif returned improper forecast_length. Returned: 26 and requested: 30') in model 464 in generation 3: SeasonalityMotif

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 465 with model FBProphet in generation 3 of 25
Model Number: 466 with model SeasonalityMotif in generation 3 of 25
Model Number: 467 with model DatepartRegression in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 468 with model ARDL in generation 3 of 25
Model Number: 469 with model Cassandra in generation 3 of 25
Model Number: 470 with model Cassandra in generation 3 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 471 with model SeasonalityMotif in generation 3 of 25
New Generation: 4 of 25
Model Number: 472 with model ETS in generation 4 of 25
Model Number: 473 with model LastValueNaive in generation 4 of 25
Model Number: 474 with model SeasonalNaive in generation 4 of 25
Model Number: 475 with model ETS in generation 4 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params zero {'0': {'output_distribution': 'uniform', 'n_quantiles': 233}, '1': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}, '2': {}} with error ValueError('BTCD only works on multivarate series')") in model 475 in generation 4: ETS
Model Number: 476 with model GLM in generation 4 of 25
Model Number: 477 with model SectionalMotif in generation 4 of 25
Model Number: 478 with model SectionalMotif in generation 4 of 25
Model Number: 479 with model Cassandra in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 480 with model WindowRegression in generation 4 of 25
Model Number: 481 with model LastValueNaive in generation 4 of 25
Model Number: 482 with model FFT in generation 4 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params time {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 0.9, 'first_value_only': False}, '1': {'det_order': -1, 'k_ar_diff': 1}, '2': {}, '3': {'lag_1': 1440, 'method': 'LastValue'}} with error ValueError('Coint only works on multivarate series')") in model 482 in generation 4: FFT
Model Number: 483 with model Cassandra in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 484 with model SeasonalityMotif in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 485 with model FBProphet in generation 4 of 25
Model Number: 486 with model SectionalMotif in generation 4 of 25
Model Number: 487 with model FBProphet in generation 4 of 25
No anomalies detected.

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 488 with model ConstantNaive in generation 4 of 25
Model Number: 489 with model BasicLinearModel in generation 4 of 25
Model Number: 490 with model GLM in generation 4 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params quadratic {'0': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}, '1': {'output_distribution': 'uniform', 'n_quantiles': 233}} with error ValueError('BTCD only works on multivarate series')") in model 490 in generation 4: GLM
Model Number: 491 with model ETS in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 492 with model UnivariateMotif in generation 4 of 25
Model Number: 493 with model LastValueNaive in generation 4 of 25
Model Number: 494 with model LastValueNaive in generation 4 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params ffill {'0': {}, '1': {'lag': 1, 'fill': 'bfill'}, '2': {}, '3': {'sigma': 2, 'rolling_window': 90, 'run_order': 'season_first', 'regression_params': {'regression_model': {'model': 'ElasticNet', 'model_params': {'l1_ratio': 0.5, 'fit_intercept': True, 'selection': 'cyclic', 'max_iter': 1000}}, 'datepart_method': 'expanded_binarized', 'polynomial_degree': None, 'transform_dict': {'fillna': None, 'transformations': {'0': 'EWMAFilter'}, 'transformation_params': {'0': {'span': 7}}}, 'holiday_countries_used': True, 'lags': None, 'forward_lags': None}, 'holiday_params': None, 'trend_method': 'rolling_mean'}, '4': {'det_order': -1, 'k_ar_diff': 2}, '5': {}} with error ValueError('Coint only works on multivarate series')") in model 494 in generation 4: LastValueNaive
Model Number: 495 with model FFT in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 496 with model Cassandra in generation 4 of 25
Model Number: 497 with model RRVAR in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 498 with model SeasonalityMotif in generation 4 of 25
Model Number: 499 with model ARDL in generation 4 of 25
Model Number: 500 with model FBProphet in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 501 with model FBProphet in generation 4 of 25
Model Number: 502 with model ConstantNaive in generation 4 of 25
Model Number: 503 with model UnivariateMotif in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 504 with model Cassandra in generation 4 of 25
Model Number: 505 with model AverageValueNaive in generation 4 of 25
Model Number: 506 with model SeasonalNaive in generation 4 of 25
Model Number: 507 with model SectionalMotif in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 508 with model SectionalMotif in generation 4 of 25
Model Number: 509 with model GLS in generation 4 of 25
Model Number: 510 with model SeasonalityMotif in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 511 with model UnivariateMotif in generation 4 of 25
Model Number: 512 with model MetricMotif in generation 4 of 25
Model Number: 513 with model AverageValueNaive in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 514 with model RRVAR in generation 4 of 25
Model Number: 515 with model ARDL in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 516 with model FFT in generation 4 of 25
Model Number: 517 with model AverageValueNaive in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 518 with model FBProphet in generation 4 of 25
Model Number: 519 with model BasicLinearModel in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 520 with model Cassandra in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 521 with model MetricMotif in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 522 with model FBProphet in generation 4 of 25
Model Number: 523 with model Cassandra in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

Model Number: 524 with model GLM in generation 4 of 25
Model Number: 525 with model UnivariateMotif in generation 4 of 25
Model Number: 526 with model UnivariateMotif in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 527 with model ConstantNaive in generation 4 of 25
Model Number: 528 with model GLS in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_regression.py:494: UserWarning:

One or more samples have no neighbors within specified radius; predicting NaN.

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

Model Number: 529 with model DatepartRegression in generation 4 of 25
interpolating
Template Eval Error: ValueError('Model DatepartRegression returned NaN for one or more series. fail_on_forecast_nan=True') in model 529 in generation 4: DatepartRegression
Model Number: 530 with model GLM in generation 4 of 25
Model Number: 531 with model DatepartRegression in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.168e+10, tolerance: 5.338e+06

Model Number: 532 with model MetricMotif in generation 4 of 25
Model Number: 533 with model GLM in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 534 with model SeasonalNaive in generation 4 of 25
Model Number: 535 with model FBProphet in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 536 with model BasicLinearModel in generation 4 of 25
Model Number: 537 with model ETS in generation 4 of 25
Model Number: 538 with model Cassandra in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 539 with model MetricMotif in generation 4 of 25
Model Number: 540 with model FBProphet in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 541 with model MetricMotif in generation 4 of 25
Model Number: 542 with model SectionalMotif in generation 4 of 25
Model Number: 543 with model UnivariateMotif in generation 4 of 25
Model Number: 544 with model SectionalMotif in generation 4 of 25
Model Number: 545 with model DatepartRegression in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 545 in generation 4: DatepartRegression
Model Number: 546 with model SectionalMotif in generation 4 of 25
Model Number: 547 with model ETS in generation 4 of 25
Model Number: 548 with model ConstantNaive in generation 4 of 25
Model Number: 549 with model SectionalMotif in generation 4 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 549 in generation 4: SectionalMotif
Model Number: 550 with model UnivariateMotif in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.45168e-24): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 551 with model ConstantNaive in generation 4 of 25
Model Number: 552 with model UnivariateMotif in generation 4 of 25
Model Number: 553 with model ConstantNaive in generation 4 of 25
Model Number: 554 with model SeasonalityMotif in generation 4 of 25
Model Number: 555 with model RRVAR in generation 4 of 25
Model Number: 556 with model ARDL in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 557 with model GLM in generation 4 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params ffill {'0': {'part': 'trend', 'lamb': 16}, '1': {'method': 'nonparametric', 'method_params': {'p': None, 'z_init': 2.0, 'z_limit': 12, 'z_step': 0.25, 'inverse': False, 'max_contamination': 0.25, 'mean_weight': 100, 'sd_weight': 200, 'anomaly_count_weight': 1.0}, 'fillna': 'mean', 'transform_dict': {'transformations': {'0': 'DatepartRegression'}, 'transformation_params': {'0': {'datepart_method': 'simple_3', 'regression_model': {'model': 'ElasticNet', 'model_params': {}}}}}, 'isolated_only': True, 'on_inverse': False}, '2': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 2}, '3': {}} with error ValueError('BTCD only works on multivarate series')") in model 557 in generation 4: GLM
Model Number: 558 with model FBProphet in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 559 with model ConstantNaive in generation 4 of 25
Model Number: 560 with model LastValueNaive in generation 4 of 25
Model Number: 561 with model LastValueNaive in generation 4 of 25
Model Number: 562 with model UnivariateMotif in generation 4 of 25
Model Number: 563 with model FBProphet in generation 4 of 25
No anomalies detected.

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 564 with model MetricMotif in generation 4 of 25
Model Number: 565 with model RRVAR in generation 4 of 25
Model Number: 566 with model UnivariateMotif in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 567 with model MetricMotif in generation 4 of 25
Model Number: 568 with model MetricMotif in generation 4 of 25
Model Number: 569 with model GLS in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 570 with model ARDL in generation 4 of 25
Model Number: 571 with model ConstantNaive in generation 4 of 25
Template Eval Error: ValueError('Model ConstantNaive returned improper forecast_length. Returned: 28 and requested: 30') in model 571 in generation 4: ConstantNaive
Model Number: 572 with model LastValueNaive in generation 4 of 25
Template Eval Error: ValueError('operands could not be broadcast together with shapes (150,1) (30,1) ') in model 572 in generation 4: LastValueNaive
Model Number: 573 with model BasicLinearModel in generation 4 of 25
Model Number: 574 with model MetricMotif in generation 4 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params ffill {'0': {'det_order': -1, 'k_ar_diff': 1}, '1': {'numtaps': 32, 'cutoff_hz': 0.5, 'window': 'hamming', 'sampling_frequency': 60, 'on_transform': True, 'on_inverse': False}, '2': {}, '3': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}, '4': {'lag': 1, 'fill': 'bfill'}} with error ValueError('Coint only works on multivarate series')") in model 574 in generation 4: MetricMotif
Model Number: 575 with model MetricMotif in generation 4 of 25
Model Number: 576 with model SeasonalityMotif in generation 4 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

New Generation: 5 of 25
Model Number: 577 with model BasicLinearModel in generation 5 of 25
Model Number: 578 with model FBProphet in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 579 with model GLM in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 580 with model MetricMotif in generation 5 of 25
Model Number: 581 with model BasicLinearModel in generation 5 of 25
Model Number: 582 with model UnivariateMotif in generation 5 of 25
Model Number: 583 with model ARDL in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 584 with model ETS in generation 5 of 25
Model Number: 585 with model SeasonalNaive in generation 5 of 25
Model Number: 586 with model ConstantNaive in generation 5 of 25
Model Number: 587 with model Cassandra in generation 5 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params rolling_mean_24 {'0': {'det_order': 0, 'k_ar_diff': 2}, '1': {'rows': 7}, '2': {'threshold': 0.9, 'splash_threshold': None, 'use_dayofmonth_holidays': True, 'use_wkdom_holidays': True, 'use_wkdeom_holidays': False, 'use_lunar_holidays': False, 'use_lunar_weekday': False, 'use_islamic_holidays': False, 'use_hebrew_holidays': False, 'use_hindu_holidays': False, 'anomaly_detector_params': {'method': 'zscore', 'method_params': {'distribution': 'norm', 'alpha': 0.05}, 'fillna': 'rolling_mean_24', 'transform_dict': {'fillna': 'pchip', 'transformations': {'0': 'FFTDecomposition'}, 'transformation_params': {'0': {'n_harmonics': 10, 'detrend': 'linear'}}}, 'isolated_only': False, 'on_inverse': False}, 'remove_excess_anomalies': True, 'impact': 'median_value', 'regression_params': {}}, '3': {}} with error ValueError('Coint only works on multivarate series')") in model 587 in generation 5: Cassandra
Model Number: 588 with model SeasonalNaive in generation 5 of 25
Model Number: 589 with model Cassandra in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 590 with model SeasonalNaive in generation 5 of 25
Model Number: 591 with model UnivariateMotif in generation 5 of 25
Model Number: 592 with model SeasonalityMotif in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 593 with model SeasonalityMotif in generation 5 of 25
Model Number: 594 with model LastValueNaive in generation 5 of 25
Model Number: 595 with model ARDL in generation 5 of 25
Model Number: 596 with model BasicLinearModel in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 597 with model SectionalMotif in generation 5 of 25
Model Number: 598 with model FBProphet in generation 5 of 25
Template Eval Error: Exception("Transformer StandardScaler failed on fit from params rolling_mean {'0': {'output_distribution': 'uniform', 'n_quantiles': 233}, '1': {'low': 6, 'high': 32, 'K': 1, 'lanczos_factor': True, 'return_diff': False, 'on_transform': True, 'on_inverse': False}, '2': {'lag_1': 12, 'method': 5}, '3': {}} with error ValueError('Shape of passed values is (699, 1), indices imply (701, 1)')") in model 598 in generation 5: FBProphet
Model Number: 599 with model Cassandra in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 600 with model LastValueNaive in generation 5 of 25
Model Number: 601 with model MetricMotif in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.159e+10, tolerance: 3.671e+07

Model Number: 602 with model DatepartRegression in generation 5 of 25
Model Number: 603 with model SectionalMotif in generation 5 of 25
Model Number: 604 with model MetricMotif in generation 5 of 25
Model Number: 605 with model MetricMotif in generation 5 of 25
Model Number: 606 with model SeasonalityMotif in generation 5 of 25
Model Number: 607 with model LastValueNaive in generation 5 of 25
Model Number: 608 with model ARDL in generation 5 of 25
Model Number: 609 with model DatepartRegression in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 610 with model SectionalMotif in generation 5 of 25
Model Number: 611 with model GLS in generation 5 of 25
Model Number: 612 with model SeasonalityMotif in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 613 with model Cassandra in generation 5 of 25
Model Number: 614 with model UnivariateMotif in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 615 with model UnivariateMotif in generation 5 of 25
Model Number: 616 with model MetricMotif in generation 5 of 25
Model Number: 617 with model Cassandra in generation 5 of 25
Template Eval Error: Exception('Transformer ChangepointDetrend failed on fit from params fake_date {\'0\': {}, \'1\': {\'lag\': 7, \'fill\': \'bfill\'}, \'2\': {\'model\': \'Poisson\', \'changepoint_spacing\': 6, \'changepoint_distance_end\': 180, \'datepart_method\': None}, \'3\': {}} with error ValueError("Some value(s) of y are out of the valid range of the loss \'HalfPoissonLoss\'.")') in model 617 in generation 5: Cassandra
Model Number: 618 with model BasicLinearModel in generation 5 of 25
Model Number: 619 with model SeasonalityMotif in generation 5 of 25
Template Eval Error: ValueError('Model SeasonalityMotif returned NaN for one or more series. fail_on_forecast_nan=True') in model 619 in generation 5: SeasonalityMotif
Model Number: 620 with model GLM in generation 5 of 25
Model Number: 621 with model SeasonalityMotif in generation 5 of 25
Model Number: 622 with model GLS in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning:

Mean of empty slice.

/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:121: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 623 with model ConstantNaive in generation 5 of 25
Model Number: 624 with model MetricMotif in generation 5 of 25
Model Number: 625 with model GLM in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 626 with model ETS in generation 5 of 25
Model Number: 627 with model SectionalMotif in generation 5 of 25
Model Number: 628 with model DatepartRegression in generation 5 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 628 in generation 5: DatepartRegression
Model Number: 629 with model FBProphet in generation 5 of 25
2025-01-30 00:00:00
2025-01-30 00:00:00
2025-01-30 00:00:00
Model Number: 630 with model ConstantNaive in generation 5 of 25
Model Number: 631 with model FBProphet in generation 5 of 25
Model Number: 632 with model UnivariateMotif in generation 5 of 25
Model Number: 633 with model SectionalMotif in generation 5 of 25
Model Number: 634 with model ARDL in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 635 with model BasicLinearModel in generation 5 of 25
Model Number: 636 with model GLM in generation 5 of 25
Model Number: 637 with model SeasonalityMotif in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 638 with model BasicLinearModel in generation 5 of 25
Model Number: 639 with model ConstantNaive in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_glm/glm.py:284: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

Model Number: 640 with model Cassandra in generation 5 of 25
Model Number: 641 with model ConstantNaive in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 642 with model GLM in generation 5 of 25
Model Number: 643 with model ConstantNaive in generation 5 of 25
Model Number: 644 with model UnivariateMotif in generation 5 of 25
Model Number: 645 with model UnivariateMotif in generation 5 of 25
Model Number: 646 with model LastValueNaive in generation 5 of 25
Model Number: 647 with model ConstantNaive in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 648 with model AverageValueNaive in generation 5 of 25
Model Number: 649 with model FBProphet in generation 5 of 25
Model Number: 650 with model SectionalMotif in generation 5 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 650 in generation 5: SectionalMotif
Model Number: 651 with model MetricMotif in generation 5 of 25
Model Number: 652 with model MetricMotif in generation 5 of 25
Model Number: 653 with model SectionalMotif in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 654 with model UnivariateMotif in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 655 with model ETS in generation 5 of 25
Template Eval Error: ValueError('Model ETS returned NaN for one or more series. fail_on_forecast_nan=True') in model 655 in generation 5: ETS
Model Number: 656 with model Cassandra in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 657 with model ARDL in generation 5 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 657 in generation 5: ARDL
Model Number: 658 with model SectionalMotif in generation 5 of 25
Model Number: 659 with model ConstantNaive in generation 5 of 25
Template Eval Error: Exception('Transformer PCA failed on fit from params ffill {\'0\': {\'whiten\': False, \'n_components\': 10}, \'1\': {\'lag\': 1, \'fill\': \'bfill\'}, \'2\': {\'n_harmonics\': 10, \'detrend\': \'linear\'}, \'3\': {\'constant\': 0, \'reintroduction_model\': {\'model\': \'KNN\', \'model_params\': {\'n_neighbors\': 5, \'weights\': \'uniform\', \'p\': 1.5, \'leaf_size\': 30}, \'datepart_method\': \'common_fourier_rw\'}, \'fillna\': \'mean\'}, \'4\': {\'constant\': 0, \'reintroduction_model\': None, \'fillna\': None}, \'5\': {\'rows\': 1, \'lag\': 1, \'method\': \'additive\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': 1, \'threshold_method\': \'mean\'}} with error ValueError("n_components=10 must be between 0 and min(n_samples, n_features)=1 with svd_solver=\'full\'")') in model 659 in generation 5: ConstantNaive
Model Number: 660 with model SeasonalityMotif in generation 5 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

New Generation: 6 of 25
Model Number: 661 with model Cassandra in generation 6 of 25
Model Number: 662 with model GLM in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 663 with model BasicLinearModel in generation 6 of 25
Template Eval Error: LinAlgError('SVD did not converge') in model 663 in generation 6: BasicLinearModel
Model Number: 664 with model Cassandra in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 665 with model ConstantNaive in generation 6 of 25
Model Number: 666 with model UnivariateMotif in generation 6 of 25
Model Number: 667 with model ETS in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_glm/glm.py:284: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 668 with model LastValueNaive in generation 6 of 25
Model Number: 669 with model UnivariateMotif in generation 6 of 25
Model Number: 670 with model Cassandra in generation 6 of 25
Model Number: 671 with model SectionalMotif in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 672 with model LastValueNaive in generation 6 of 25
Model Number: 673 with model SeasonalNaive in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 674 with model MetricMotif in generation 6 of 25
Model Number: 675 with model GLS in generation 6 of 25
Model Number: 676 with model UnivariateMotif in generation 6 of 25
Model Number: 677 with model SeasonalityMotif in generation 6 of 25
Model Number: 678 with model SeasonalityMotif in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 679 with model BasicLinearModel in generation 6 of 25
Template Eval Error: LinAlgError('SVD did not converge') in model 679 in generation 6: BasicLinearModel
Model Number: 680 with model SeasonalNaive in generation 6 of 25
Model Number: 681 with model Cassandra in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 682 with model DatepartRegression in generation 6 of 25
Model Number: 683 with model ConstantNaive in generation 6 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params nearest {'0': {}, '1': {'rows': 1, 'lag': 7, 'method': 'additive', 'strength': 0.5, 'first_value_only': False, 'threshold': None, 'threshold_method': 'mean'}, '2': {'det_order': 1, 'k_ar_diff': 0}, '3': {'window_size': 30, 'alpha': 1.8, 'grouping_forward_limit': 6, 'max_level_shifts': 40, 'alignment': 'average'}} with error ValueError('Coint only works on multivarate series')") in model 683 in generation 6: ConstantNaive
Model Number: 684 with model DatepartRegression in generation 6 of 25
Model Number: 685 with model UnivariateMotif in generation 6 of 25
Model Number: 686 with model MetricMotif in generation 6 of 25
Model Number: 687 with model AverageValueNaive in generation 6 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params zero {'0': {'rows': 168, 'lag': 84, 'method': 'additive', 'strength': 0.5, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gbtree', 'max_depth': 6, 'eta': 0.3, 'min_child_weight': 1, 'subsample': 1, 'colsample_bylevel': 1, 'reg_alpha': 0, 'reg_lambda': 1, 'n_estimators': 4}, 'datepart_method': [7, 365.25]}, 'fillna': 'linear'}, '2': {'lag': 1, 'fill': 'bfill'}, '3': {'discretization': 'lower', 'n_bins': 5}, '4': {}, '5': {}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 687 in generation 6: AverageValueNaive
Model Number: 688 with model GLM in generation 6 of 25
Model Number: 689 with model UnivariateMotif in generation 6 of 25
Model Number: 690 with model ConstantNaive in generation 6 of 25
Model Number: 691 with model Cassandra in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 692 with model SectionalMotif in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 693 with model ARDL in generation 6 of 25
Model Number: 694 with model ETS in generation 6 of 25
Model Number: 695 with model MetricMotif in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 696 with model SectionalMotif in generation 6 of 25
Model Number: 697 with model MetricMotif in generation 6 of 25
Model Number: 698 with model LastValueNaive in generation 6 of 25
Model Number: 699 with model LastValueNaive in generation 6 of 25
Model Number: 700 with model Cassandra in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Template Eval Error: ValueError('transformed data is all zeroes') in model 700 in generation 6: Cassandra
Model Number: 701 with model MetricMotif in generation 6 of 25
Model Number: 702 with model DatepartRegression in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Epoch 1/100

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 99.7553
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 99.4167
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 99.1913
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 99.0088
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 98.8486
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 98.6953
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 98.5572
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 98.4214
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 98.2854
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 98.1486
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 98.0108
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.8719
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97.7315
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.5897
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.4467
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.3066
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1951
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1952
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2064
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2183
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1926
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1989
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2225
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97.1914
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1930
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2274
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1905
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1927
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2060
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2137
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1923
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97.2010
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2191
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97.1916
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1957
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2243
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1909
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97.1930
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2089
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2107
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1926
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2039
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2161
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1920
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1986
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2213
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1912
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1933
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2264
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1905
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1926
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2064
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2129
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1922
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2014
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2183
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97.1916
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97.1962
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2234
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1908
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1930
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97.2093
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2100
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1926
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2044
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2153
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1919
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1991
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2204
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1912
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1938
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2255
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97.1904
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1926
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2068
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97.2121
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1922
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2019
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2173
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1915
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1967
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2225
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1908
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97.1929
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2097
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2090
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1925
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2049
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2142
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1919
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1997
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2193
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 97.1912
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1945
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2243
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1904
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1925
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2075
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.2108
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 97.1921
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step
Model Number: 703 with model ConstantNaive in generation 6 of 25
Model Number: 704 with model SeasonalNaive in generation 6 of 25
Model Number: 705 with model MetricMotif in generation 6 of 25
Model Number: 706 with model GLS in generation 6 of 25
Model Number: 707 with model FBProphet in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 708 with model GLS in generation 6 of 25
Model Number: 709 with model SeasonalityMotif in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 710 with model Cassandra in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 711 with model SeasonalityMotif in generation 6 of 25
Model Number: 712 with model MetricMotif in generation 6 of 25
Template Eval Error: ValueError('kth(=99) out of bounds (81)') in model 712 in generation 6: MetricMotif
Model Number: 713 with model MetricMotif in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 714 with model BasicLinearModel in generation 6 of 25
Model Number: 715 with model ETS in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 716 with model FBProphet in generation 6 of 25
Model Number: 717 with model GLS in generation 6 of 25
Template Eval Error: ValueError('operands could not be broadcast together with shapes (90,1) (30,1) ') in model 717 in generation 6: GLS
Model Number: 718 with model FBProphet in generation 6 of 25
Model Number: 719 with model LastValueNaive in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.677e+10, tolerance: 3.687e+07

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 720 with model BasicLinearModel in generation 6 of 25
Model Number: 721 with model UnivariateMotif in generation 6 of 25
Model Number: 722 with model SectionalMotif in generation 6 of 25
Model Number: 723 with model ConstantNaive in generation 6 of 25
Model Number: 724 with model UnivariateMotif in generation 6 of 25
Model Number: 725 with model FBProphet in generation 6 of 25
No anomalies detected.

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 726 with model LastValueNaive in generation 6 of 25
Model Number: 727 with model GLS in generation 6 of 25
2025-01-30 00:00:00
Template Eval Error: Exception("Transformer MaxAbsScaler failed on inverse from params nearest {'0': {'model': 'Tweedie', 'changepoint_spacing': 120, 'changepoint_distance_end': None, 'datepart_method': [7, 365.25]}, '1': {'low': 6, 'high': 364, 'K': 1, 'lanczos_factor': True, 'return_diff': True, 'on_transform': True, 'on_inverse': False}, '2': {'method': 'remove', 'std_threshold': 3.5, 'fillna': 'mean'}, '3': {}, '4': {'lag_1': 364, 'method': 'LastValue'}, '5': {'mode': 'downscale', 'factor': 1, 'down_method': 'mean', 'fill_method': 'linear'}} with ValueError('Shape of passed values is (28, 1), indices imply (30, 1)')") in model 727 in generation 6: GLS
Model Number: 728 with model SectionalMotif in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_glm/glm.py:284: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 729 with model FBProphet in generation 6 of 25
Model Number: 730 with model ConstantNaive in generation 6 of 25
Model Number: 731 with model SeasonalityMotif in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 732 with model FBProphet in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 733 with model Cassandra in generation 6 of 25
Model Number: 734 with model BasicLinearModel in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 735 with model SectionalMotif in generation 6 of 25
Model Number: 736 with model GLM in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/generalized_linear_model.py:308: DomainWarning:

The InversePower link function does not respect the domain of the Gamma family.

Model Number: 737 with model UnivariateMotif in generation 6 of 25
Model Number: 738 with model AverageValueNaive in generation 6 of 25
Model Number: 739 with model UnivariateMotif in generation 6 of 25
Model Number: 740 with model RRVAR in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 741 with model MetricMotif in generation 6 of 25
Model Number: 742 with model MetricMotif in generation 6 of 25
Model Number: 743 with model DatepartRegression in generation 6 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.242e+10, tolerance: 3.699e+07

Model Number: 744 with model ConstantNaive in generation 6 of 25
New Generation: 7 of 25
Model Number: 745 with model SectionalMotif in generation 7 of 25
Model Number: 746 with model SeasonalityMotif in generation 7 of 25
Model Number: 747 with model ConstantNaive in generation 7 of 25
Model Number: 748 with model LastValueNaive in generation 7 of 25
Model Number: 749 with model LastValueNaive in generation 7 of 25
Model Number: 750 with model GLM in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 751 with model MetricMotif in generation 7 of 25
Model Number: 752 with model UnivariateMotif in generation 7 of 25
Model Number: 753 with model ARDL in generation 7 of 25
Model Number: 754 with model ETS in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

Model Number: 755 with model SeasonalityMotif in generation 7 of 25
Model Number: 756 with model Cassandra in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 757 with model Cassandra in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 758 with model FBProphet in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 759 with model AverageValueNaive in generation 7 of 25
Model Number: 760 with model MetricMotif in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 761 with model MetricMotif in generation 7 of 25
Model Number: 762 with model BasicLinearModel in generation 7 of 25
Model Number: 763 with model DatepartRegression in generation 7 of 25
Template Eval Error: IndexError('tuple index out of range') in model 763 in generation 7: DatepartRegression
Model Number: 764 with model GLS in generation 7 of 25
Model Number: 765 with model Cassandra in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 766 with model AverageValueNaive in generation 7 of 25
Model Number: 767 with model MetricMotif in generation 7 of 25
Model Number: 768 with model AverageValueNaive in generation 7 of 25
Model Number: 769 with model FBProphet in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 770 with model SectionalMotif in generation 7 of 25
Model Number: 771 with model FBProphet in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 772 with model AverageValueNaive in generation 7 of 25
Model Number: 773 with model GLM in generation 7 of 25
Model Number: 774 with model GLM in generation 7 of 25
Model Number: 775 with model ConstantNaive in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Template Eval Error: ValueError('operands could not be broadcast together with shapes (60,1) (30,1) ') in model 775 in generation 7: ConstantNaive
Model Number: 776 with model LastValueNaive in generation 7 of 25
Model Number: 777 with model ETS in generation 7 of 25
Model Number: 778 with model MetricMotif in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 779 with model AverageValueNaive in generation 7 of 25
Model Number: 780 with model MetricMotif in generation 7 of 25
Model Number: 781 with model MetricMotif in generation 7 of 25
Model Number: 782 with model MetricMotif in generation 7 of 25
Model Number: 783 with model BasicLinearModel in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 784 with model FBProphet in generation 7 of 25
Template Eval Error: Exception('Transformer PCA failed on fit from params ffill {\'0\': {}, \'1\': {\'whiten\': False, \'n_components\': 10}, \'2\': {}, \'3\': {\'method\': \'rolling_zscore\', \'method_params\': {\'distribution\': \'uniform\', \'alpha\': 0.05, \'rolling_periods\': 28, \'center\': False}, \'fillna\': \'rolling_mean_24\', \'transform_dict\': {\'fillna\': \'linear\', \'transformations\': {\'0\': \'EWMAFilter\', \'1\': \'LevelShiftTransformer\'}, \'transformation_params\': {\'0\': {\'span\': 10}, \'1\': {\'window_size\': 90, \'alpha\': 3.0, \'grouping_forward_limit\': 3, \'max_level_shifts\': 5, \'alignment\': \'average\'}}}, \'isolated_only\': False, \'on_inverse\': False}} with error ValueError("n_components=10 must be between 0 and min(n_samples, n_features)=1 with svd_solver=\'full\'")') in model 784 in generation 7: FBProphet
Model Number: 785 with model ConstantNaive in generation 7 of 25
Model Number: 786 with model UnivariateMotif in generation 7 of 25
Model Number: 787 with model ARDL in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Model Number: 788 with model DatepartRegression in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning:

Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 789 with model GLM in generation 7 of 25
Model Number: 790 with model Cassandra in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 791 with model GLS in generation 7 of 25
Model Number: 792 with model SeasonalityMotif in generation 7 of 25
Model Number: 793 with model UnivariateMotif in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

Model Number: 794 with model SeasonalityMotif in generation 7 of 25
Model Number: 795 with model MetricMotif in generation 7 of 25
Model Number: 796 with model MetricMotif in generation 7 of 25
Model Number: 797 with model UnivariateMotif in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 798 with model SeasonalityMotif in generation 7 of 25
Model Number: 799 with model SeasonalityMotif in generation 7 of 25
Model Number: 800 with model ConstantNaive in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 801 with model Cassandra in generation 7 of 25
Model Number: 802 with model SectionalMotif in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 803 with model SectionalMotif in generation 7 of 25
Model Number: 804 with model BasicLinearModel in generation 7 of 25
Model Number: 805 with model DatepartRegression in generation 7 of 25
Template Eval Error: ValueError('Input X contains NaN.\nElasticNet does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values') in model 805 in generation 7: DatepartRegression
Model Number: 806 with model SectionalMotif in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 807 with model UnivariateMotif in generation 7 of 25
Model Number: 808 with model BasicLinearModel in generation 7 of 25
Model Number: 809 with model ConstantNaive in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 810 with model ConstantNaive in generation 7 of 25
Model Number: 811 with model FBProphet in generation 7 of 25
Model Number: 812 with model DatepartRegression in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.910e+09, tolerance: 5.451e+06

Model Number: 813 with model UnivariateMotif in generation 7 of 25
Model Number: 814 with model AverageValueNaive in generation 7 of 25
Model Number: 815 with model UnivariateMotif in generation 7 of 25
Model Number: 816 with model SectionalMotif in generation 7 of 25
Model Number: 817 with model SeasonalityMotif in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 818 with model BasicLinearModel in generation 7 of 25
Model Number: 819 with model ARDL in generation 7 of 25
Model Number: 820 with model SectionalMotif in generation 7 of 25
Template Eval Error: ValueError('Model SectionalMotif returned NaN for one or more series. fail_on_forecast_nan=True') in model 820 in generation 7: SectionalMotif
Model Number: 821 with model BasicLinearModel in generation 7 of 25
Model Number: 822 with model SeasonalityMotif in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:553: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 823 with model ConstantNaive in generation 7 of 25
Template Eval Error: ValueError('operands could not be broadcast together with shapes (60,1) (30,1) ') in model 823 in generation 7: ConstantNaive
Model Number: 824 with model MetricMotif in generation 7 of 25
Model Number: 825 with model ETS in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 826 with model MetricMotif in generation 7 of 25
Model Number: 827 with model SeasonalNaive in generation 7 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 828 with model Cassandra in generation 7 of 25
New Generation: 8 of 25
Model Number: 829 with model UnivariateMotif in generation 8 of 25
Model Number: 830 with model SectionalMotif in generation 8 of 25
Model Number: 831 with model BasicLinearModel in generation 8 of 25
Model Number: 832 with model FBProphet in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 833 with model SeasonalityMotif in generation 8 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params ffill {'0': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 2}, '1': {'method': 'rolling_zscore', 'method_params': {'distribution': 'uniform', 'alpha': 0.05, 'rolling_periods': 28, 'center': False}, 'fillna': 'rolling_mean_24', 'transform_dict': {'fillna': 'linear', 'transformations': {'0': 'EWMAFilter', '1': 'LevelShiftTransformer'}, 'transformation_params': {'0': {'span': 10}, '1': {'window_size': 90, 'alpha': 3.0, 'grouping_forward_limit': 3, 'max_level_shifts': 5, 'alignment': 'average'}}}, 'isolated_only': False, 'on_inverse': False}, '2': {'output_distribution': 'uniform', 'n_quantiles': 1000}, '3': {'decomp_type': 'STL', 'part': 'trend', 'seasonal': 7}} with error ValueError('BTCD only works on multivarate series')") in model 833 in generation 8: SeasonalityMotif
Model Number: 834 with model SeasonalityMotif in generation 8 of 25
Model Number: 835 with model SectionalMotif in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 836 with model LastValueNaive in generation 8 of 25
Model Number: 837 with model ConstantNaive in generation 8 of 25
Model Number: 838 with model MetricMotif in generation 8 of 25
Model Number: 839 with model MetricMotif in generation 8 of 25
Model Number: 840 with model BasicLinearModel in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 841 with model LastValueNaive in generation 8 of 25
Model Number: 842 with model Cassandra in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 843 with model UnivariateMotif in generation 8 of 25
Model Number: 844 with model LastValueNaive in generation 8 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params mean {'0': {'window_size': 7, 'alpha': 2.0, 'grouping_forward_limit': 2, 'max_level_shifts': 8, 'alignment': 'average'}, '1': {'constant': 0, 'reintroduction_model': {'model': 'SGD', 'model_params': {}, 'datepart_method': 'common_fourier'}, 'fillna': 'linear'}} with error ValueError('The number of classes has to be greater than one; got 1 class')") in model 844 in generation 8: LastValueNaive
Model Number: 845 with model Cassandra in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 846 with model LastValueNaive in generation 8 of 25
Model Number: 847 with model SeasonalityMotif in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Template Eval Error: ValueError('operands could not be broadcast together with shapes (150,1) (30,1) ') in model 847 in generation 8: SeasonalityMotif
Model Number: 848 with model ETS in generation 8 of 25
Model Number: 849 with model FBProphet in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 850 with model GLM in generation 8 of 25
Model Number: 851 with model Cassandra in generation 8 of 25
2025-01-30 00:00:00
2025-01-30 00:00:00
2025-01-30 00:00:00
Template Eval Error: KeyError("['changepoint_1'] not in index") in model 851 in generation 8: Cassandra
Model Number: 852 with model LastValueNaive in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 853 with model BasicLinearModel in generation 8 of 25
Model Number: 854 with model ARDL in generation 8 of 25
Model Number: 855 with model DatepartRegression in generation 8 of 25
Model Number: 856 with model SeasonalityMotif in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 857 with model SeasonalityMotif in generation 8 of 25
Model Number: 858 with model DatepartRegression in generation 8 of 25
Model Number: 859 with model MetricMotif in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning:

Liblinear failed to converge, increase the number of iterations.

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 860 with model FBProphet in generation 8 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params ffill {'0': {'rows': 7, 'lag': 1, 'method': 'additive', 'strength': 0.9, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}, '1': {'lag_1': 7, 'method': 'LastValue'}, '2': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': True, 'threshold': 3, 'threshold_method': 'max'}, '3': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 2}} with error ValueError('BTCD only works on multivarate series')") in model 860 in generation 8: FBProphet
Model Number: 861 with model SeasonalNaive in generation 8 of 25
Model Number: 862 with model SeasonalityMotif in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

Model Number: 863 with model MetricMotif in generation 8 of 25
Template Eval Error: ValueError('Shape of passed values is (30, 2), indices imply (30, 1)') in model 863 in generation 8: MetricMotif
Model Number: 864 with model MetricMotif in generation 8 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params quadratic {'0': {'method': 'remove', 'std_threshold': 4.5, 'fillna': 'mean'}, '1': {'mode': 'upscale', 'factor': 4, 'down_method': 'mean', 'fill_method': 'pchip'}, '2': {'algorithm': 'parallel', 'fun': 'logcosh', 'max_iter': 250, 'whiten': 'unit-variance'}, '3': {}, '4': {'det_order': -1, 'k_ar_diff': 0}} with error ValueError('Coint only works on multivarate series')") in model 864 in generation 8: MetricMotif
Model Number: 865 with model SectionalMotif in generation 8 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 865 in generation 8: SectionalMotif
Model Number: 866 with model FBProphet in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 867 with model ConstantNaive in generation 8 of 25
Model Number: 868 with model BasicLinearModel in generation 8 of 25
Model Number: 869 with model SectionalMotif in generation 8 of 25
Model Number: 870 with model DatepartRegression in generation 8 of 25
Model Number: 871 with model UnivariateMotif in generation 8 of 25
Model Number: 872 with model MetricMotif in generation 8 of 25
Model Number: 873 with model ConstantNaive in generation 8 of 25
Model Number: 874 with model ConstantNaive in generation 8 of 25
Model Number: 875 with model MetricMotif in generation 8 of 25
Model Number: 876 with model ConstantNaive in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 877 with model AverageValueNaive in generation 8 of 25
Model Number: 878 with model FBProphet in generation 8 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params quadratic {'0': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 1}, '1': {}, '2': {'fillna': 'linear', 'center': 'median'}} with error ValueError('BTCD only works on multivarate series')") in model 878 in generation 8: FBProphet
Model Number: 879 with model SeasonalNaive in generation 8 of 25
Model Number: 880 with model SectionalMotif in generation 8 of 25
Model Number: 881 with model SectionalMotif in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 882 with model Cassandra in generation 8 of 25
Model Number: 883 with model SectionalMotif in generation 8 of 25
Model Number: 884 with model SectionalMotif in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 885 with model LastValueNaive in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

Model Number: 886 with model MetricMotif in generation 8 of 25
Model Number: 887 with model ETS in generation 8 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params mean {'0': {'method': 'minmax', 'method_params': {'alpha': 0.03}, 'fillna': 'linear', 'transform_dict': None, 'isolated_only': False, 'on_inverse': False}, '1': {'det_order': -1, 'k_ar_diff': 2}, '2': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}, '3': {'theta_values': [0.8, 1.2]}, '4': {'part': 'trend', 'lamb': 129600}} with error ValueError('Coint only works on multivarate series')") in model 887 in generation 8: ETS
Model Number: 888 with model BasicLinearModel in generation 8 of 25
Model Number: 889 with model Cassandra in generation 8 of 25
Template Eval Error: TypeError('Cannot infer number of levels from empty list') in model 889 in generation 8: Cassandra
Model Number: 890 with model GLM in generation 8 of 25
Model Number: 891 with model SeasonalityMotif in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 892 with model SeasonalityMotif in generation 8 of 25
Model Number: 893 with model DatepartRegression in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.315e+09, tolerance: 1.929e+07

Model Number: 894 with model BasicLinearModel in generation 8 of 25
Model Number: 895 with model RRVAR in generation 8 of 25
Model Number: 896 with model MetricMotif in generation 8 of 25
Model Number: 897 with model ETS in generation 8 of 25
Model Number: 898 with model SeasonalNaive in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 899 with model SeasonalityMotif in generation 8 of 25
Model Number: 900 with model AverageValueNaive in generation 8 of 25
Model Number: 901 with model FBProphet in generation 8 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 901 in generation 8: FBProphet
Model Number: 902 with model SeasonalityMotif in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 903 with model GLS in generation 8 of 25
Model Number: 904 with model FFT in generation 8 of 25
Model Number: 905 with model ConstantNaive in generation 8 of 25
Model Number: 906 with model GLS in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Template Eval Error: ValueError('operands could not be broadcast together with shapes (60,1) (30,1) ') in model 906 in generation 8: GLS
Model Number: 907 with model Cassandra in generation 8 of 25
Template Eval Error: UnboundLocalError("local variable 'slope' referenced before assignment") in model 907 in generation 8: Cassandra
Model Number: 908 with model GLM in generation 8 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 909 with model SectionalMotif in generation 8 of 25
Model Number: 910 with model LastValueNaive in generation 8 of 25
Model Number: 911 with model BasicLinearModel in generation 8 of 25
Model Number: 912 with model ETS in generation 8 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params zero {'0': {'rows': 4}, '1': {'det_order': -1, 'k_ar_diff': 2}, '2': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}, '3': {'theta_values': [0.8, 1.2]}, '4': {'rows': 1, 'lag': 84, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '5': {'discretization': 'sklearn-kmeans', 'n_bins': 10}} with error ValueError('Coint only works on multivarate series')") in model 912 in generation 8: ETS

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

New Generation: 9 of 25
Model Number: 913 with model BasicLinearModel in generation 9 of 25
Model Number: 914 with model DatepartRegression in generation 9 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 914 in generation 9: DatepartRegression
Model Number: 915 with model SectionalMotif in generation 9 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params rolling_mean_24 {'0': {}, '1': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 2}, '2': {}} with error ValueError('BTCD only works on multivarate series')") in model 915 in generation 9: SectionalMotif
Model Number: 916 with model LastValueNaive in generation 9 of 25
Model Number: 917 with model Cassandra in generation 9 of 25
Template Eval Error: KeyError("['changepoint_1', 'changepoint_2'] not in index") in model 917 in generation 9: Cassandra
Model Number: 918 with model MetricMotif in generation 9 of 25
Model Number: 919 with model ConstantNaive in generation 9 of 25
Model Number: 920 with model Cassandra in generation 9 of 25
Model Number: 921 with model LastValueNaive in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 922 with model BasicLinearModel in generation 9 of 25
Model Number: 923 with model BasicLinearModel in generation 9 of 25
Model Number: 924 with model ETS in generation 9 of 25
Model Number: 925 with model BasicLinearModel in generation 9 of 25
Model Number: 926 with model AverageValueNaive in generation 9 of 25
Model Number: 927 with model LastValueNaive in generation 9 of 25
Model Number: 928 with model UnivariateMotif in generation 9 of 25
Model Number: 929 with model ConstantNaive in generation 9 of 25
Model Number: 930 with model AverageValueNaive in generation 9 of 25
Model Number: 931 with model ETS in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_fastica.py:583: UserWarning:

Ignoring n_components with whiten=False.

Model Number: 932 with model GLM in generation 9 of 25
Model Number: 933 with model AverageValueNaive in generation 9 of 25
Model Number: 934 with model SeasonalityMotif in generation 9 of 25
Model Number: 935 with model ETS in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 936 with model ConstantNaive in generation 9 of 25
Model Number: 937 with model LastValueNaive in generation 9 of 25
Model Number: 938 with model ETS in generation 9 of 25
Model Number: 939 with model Cassandra in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Template Eval Error: KeyError("['changepoint_1', 'changepoint_2'] not in index") in model 939 in generation 9: Cassandra
Model Number: 940 with model SectionalMotif in generation 9 of 25
Model Number: 941 with model ConstantNaive in generation 9 of 25
Model Number: 942 with model Cassandra in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 942 in generation 9: Cassandra
Model Number: 943 with model GLM in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 944 with model UnivariateMotif in generation 9 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params ffill {'0': {'det_order': 1, 'k_ar_diff': 1}, '1': {'span': 24}, '2': {}, '3': {'method': 0.3}, '4': {'lag': 1, 'fill': 'bfill'}, '5': {'mode': 'upscale', 'factor': 3, 'down_method': 'decimate', 'fill_method': 'pchip'}} with error ValueError('Coint only works on multivarate series')") in model 944 in generation 9: UnivariateMotif
Model Number: 945 with model GLS in generation 9 of 25
Model Number: 946 with model BasicLinearModel in generation 9 of 25
Model Number: 947 with model MetricMotif in generation 9 of 25
Model Number: 948 with model SeasonalNaive in generation 9 of 25
Model Number: 949 with model Cassandra in generation 9 of 25
Model Number: 950 with model MetricMotif in generation 9 of 25
Template Eval Error: Exception('Transformer PCA failed on fit from params mean {\'0\': {\'method\': \'minmax\', \'method_params\': {\'alpha\': 0.03}, \'fillna\': \'linear\', \'transform_dict\': None, \'isolated_only\': False, \'on_inverse\': False}, \'1\': {\'whiten\': True, \'n_components\': 4}, \'2\': {}, \'3\': {\'lag_1\': 2, \'method\': \'LastValue\'}, \'4\': {\'part\': \'trend\', \'lamb\': 129600}, \'5\': {\'algorithm\': \'parallel\', \'fun\': \'logcosh\', \'max_iter\': 100, \'whiten\': \'unit-variance\'}} with error ValueError("n_components=4 must be between 0 and min(n_samples, n_features)=1 with svd_solver=\'full\'")') in model 950 in generation 9: MetricMotif
Model Number: 951 with model UnivariateMotif in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 952 with model MetricMotif in generation 9 of 25
Model Number: 953 with model SectionalMotif in generation 9 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 953 in generation 9: SectionalMotif
Model Number: 954 with model Cassandra in generation 9 of 25
Template Eval Error: TypeError('Cannot infer number of levels from empty list') in model 954 in generation 9: Cassandra
Model Number: 955 with model LastValueNaive in generation 9 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params akima {'0': {'method': 'minmax', 'method_params': {'alpha': 0.03}, 'fillna': 'linear', 'transform_dict': None, 'isolated_only': False, 'on_inverse': False}, '1': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gblinear', 'max_depth': 6, 'eta': 0.003, 'min_child_weight': 10, 'subsample': 1, 'colsample_bylevel': 1, 'reg_alpha': 100, 'reg_lambda': 1, 'n_estimators': 4}, 'datepart_method': 'simple_2'}, 'fillna': 'mean'}, '2': {'rows': 4, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}, '3': {'lag_1': 2, 'method': 'LastValue'}, '4': {'part': 'trend', 'lamb': 129600}, '5': {}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 955 in generation 9: LastValueNaive
Model Number: 956 with model GLM in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

Model Number: 957 with model SeasonalityMotif in generation 9 of 25
Template Eval Error: Exception("Transformer FIRFilter failed on fit from params ffill {'0': {'window_size': 30, 'alpha': 3.5, 'grouping_forward_limit': 6, 'max_level_shifts': 3, 'alignment': 'average'}, '1': {'numtaps': 1024, 'cutoff_hz': 5, 'window': 'hann', 'sampling_frequency': 4, 'on_transform': True, 'on_inverse': False}, '2': {'output_distribution': 'uniform', 'n_quantiles': 1000}} with error ValueError('Invalid cutoff frequency: frequencies must be greater than 0 and less than fs/2.')") in model 957 in generation 9: SeasonalityMotif
Model Number: 958 with model AverageValueNaive in generation 9 of 25
Model Number: 959 with model SeasonalityMotif in generation 9 of 25
Model Number: 960 with model ARDL in generation 9 of 25
Model Number: 961 with model SeasonalNaive in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 962 with model MetricMotif in generation 9 of 25
Model Number: 963 with model DatepartRegression in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.858e+09, tolerance: 2.248e+06

Model Number: 964 with model DatepartRegression in generation 9 of 25
Model Number: 965 with model MetricMotif in generation 9 of 25
Template Eval Error: Exception('Transformer PCA failed on fit from params ffill_mean_biased {\'0\': {}, \'1\': {\'whiten\': True, \'n_components\': 4}, \'2\': {}, \'3\': {\'window_size\': 4, \'alpha\': 2.5, \'grouping_forward_limit\': 2, \'max_level_shifts\': 5, \'alignment\': \'average\'}, \'4\': {}} with error ValueError("n_components=4 must be between 0 and min(n_samples, n_features)=1 with svd_solver=\'full\'")') in model 965 in generation 9: MetricMotif
Model Number: 966 with model ConstantNaive in generation 9 of 25
Model Number: 967 with model ETS in generation 9 of 25
Model Number: 968 with model FBProphet in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 969 with model GLM in generation 9 of 25
Model Number: 970 with model SeasonalNaive in generation 9 of 25
Model Number: 971 with model MetricMotif in generation 9 of 25
Model Number: 972 with model UnivariateMotif in generation 9 of 25
Model Number: 973 with model BasicLinearModel in generation 9 of 25
Model Number: 974 with model SeasonalityMotif in generation 9 of 25
Model Number: 975 with model SectionalMotif in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 976 with model SectionalMotif in generation 9 of 25
Model Number: 977 with model SeasonalNaive in generation 9 of 25
Model Number: 978 with model Cassandra in generation 9 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params fake_date {'0': {'center': 'mean'}, '1': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}, '2': {'fixed': True, 'window': 60, 'macro_micro': False, 'center': False}, '3': {'lag_1': 12, 'method': 'LastValue'}} with error ValueError('BTCD only works on multivarate series')") in model 978 in generation 9: Cassandra
Model Number: 979 with model Cassandra in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

Template Eval Error: ValueError('transformed data is all zeroes') in model 979 in generation 9: Cassandra
Model Number: 980 with model FFT in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 981 with model AverageValueNaive in generation 9 of 25
Model Number: 982 with model LastValueNaive in generation 9 of 25
Model Number: 983 with model SectionalMotif in generation 9 of 25
Model Number: 984 with model MetricMotif in generation 9 of 25
Model Number: 985 with model FFT in generation 9 of 25
Model Number: 986 with model ETS in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_fastica.py:583: UserWarning:

Ignoring n_components with whiten=False.

Model Number: 987 with model Cassandra in generation 9 of 25
Model Number: 988 with model UnivariateMotif in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:49: RuntimeWarning:

invalid value encountered in reduce

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:553: RuntimeWarning:

invalid value encountered in divide

Template Eval Error: ValueError('Model UnivariateMotif returned NaN for one or more series. fail_on_forecast_nan=True') in model 988 in generation 9: UnivariateMotif
Model Number: 989 with model GLS in generation 9 of 25
Model Number: 990 with model ARDL in generation 9 of 25
Model Number: 991 with model GLS in generation 9 of 25
Model Number: 992 with model GLM in generation 9 of 25
Model Number: 993 with model FBProphet in generation 9 of 25
Model Number: 994 with model ConstantNaive in generation 9 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params ffill {'0': {'rows': 84, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'max'}, '1': {'rows': 7, 'lag': 7, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'mean'}, '2': {'constant': 0, 'reintroduction_model': {'model': 'SGD', 'model_params': {}, 'datepart_method': ['dayofweek', [365.25, 14]]}, 'fillna': 'linear'}, '3': {'window_size': 30, 'alpha': 2.0, 'grouping_forward_limit': 5, 'max_level_shifts': 30, 'alignment': 'last_value'}} with error ValueError('The number of classes has to be greater than one; got 1 class')") in model 994 in generation 9: ConstantNaive
Model Number: 995 with model Cassandra in generation 9 of 25
Model Number: 996 with model ARDL in generation 9 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

New Generation: 10 of 25
Model Number: 997 with model SectionalMotif in generation 10 of 25
Model Number: 998 with model BasicLinearModel in generation 10 of 25
Model Number: 999 with model BasicLinearModel in generation 10 of 25
Model Number: 1000 with model MetricMotif in generation 10 of 25
Model Number: 1001 with model FBProphet in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1002 with model GLS in generation 10 of 25
Model Number: 1003 with model AverageValueNaive in generation 10 of 25
Model Number: 1004 with model MetricMotif in generation 10 of 25
Model Number: 1005 with model LastValueNaive in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1006 with model BasicLinearModel in generation 10 of 25
Model Number: 1007 with model MetricMotif in generation 10 of 25
Model Number: 1008 with model LastValueNaive in generation 10 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params mean {'0': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 1}, '1': {}, '2': {'window_size': 90, 'alpha': 2.5, 'grouping_forward_limit': 4, 'max_level_shifts': 30, 'alignment': 'rolling_diff'}, '3': {'span': 28}} with error ValueError('BTCD only works on multivarate series')") in model 1008 in generation 10: LastValueNaive
Model Number: 1009 with model BasicLinearModel in generation 10 of 25
Model Number: 1010 with model AverageValueNaive in generation 10 of 25
Model Number: 1011 with model LastValueNaive in generation 10 of 25
Model Number: 1012 with model MetricMotif in generation 10 of 25
Model Number: 1013 with model ARDL in generation 10 of 25
Template Eval Error: ValueError("ARDL series close failed with error IndexError('tuple index out of range') exog train None and predict None") in model 1013 in generation 10: ARDL
Model Number: 1014 with model Cassandra in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1015 with model UnivariateMotif in generation 10 of 25
Model Number: 1016 with model Cassandra in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.649e+00, tolerance: 1.264e-02

Model Number: 1017 with model DatepartRegression in generation 10 of 25
Model Number: 1018 with model DatepartRegression in generation 10 of 25
interpolating
Model Number: 1019 with model ETS in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_regression.py:494: UserWarning:

One or more samples have no neighbors within specified radius; predicting NaN.

Model Number: 1020 with model BasicLinearModel in generation 10 of 25
Model Number: 1021 with model ETS in generation 10 of 25
Model Number: 1022 with model SectionalMotif in generation 10 of 25
Model Number: 1023 with model SectionalMotif in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1024 with model BasicLinearModel in generation 10 of 25
Model Number: 1025 with model UnivariateMotif in generation 10 of 25
Model Number: 1026 with model MetricMotif in generation 10 of 25
Model Number: 1027 with model BasicLinearModel in generation 10 of 25
Model Number: 1028 with model GLS in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1029 with model LastValueNaive in generation 10 of 25
Model Number: 1030 with model SectionalMotif in generation 10 of 25
Model Number: 1031 with model LastValueNaive in generation 10 of 25
Model Number: 1032 with model FBProphet in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1033 with model ETS in generation 10 of 25
Model Number: 1034 with model SectionalMotif in generation 10 of 25
Model Number: 1035 with model MetricMotif in generation 10 of 25
Model Number: 1036 with model FBProphet in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1037 with model BasicLinearModel in generation 10 of 25
Model Number: 1038 with model ConstantNaive in generation 10 of 25
Model Number: 1039 with model MetricMotif in generation 10 of 25
Model Number: 1040 with model ARDL in generation 10 of 25
Model Number: 1041 with model UnivariateMotif in generation 10 of 25
Model Number: 1042 with model ConstantNaive in generation 10 of 25
Model Number: 1043 with model LastValueNaive in generation 10 of 25
Model Number: 1044 with model GLS in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1045 with model BasicLinearModel in generation 10 of 25
Model Number: 1046 with model SectionalMotif in generation 10 of 25
Model Number: 1047 with model BasicLinearModel in generation 10 of 25
Template Eval Error: ValueError('matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 701 is different from 1966)') in model 1047 in generation 10: BasicLinearModel
Model Number: 1048 with model MetricMotif in generation 10 of 25
Model Number: 1049 with model SeasonalityMotif in generation 10 of 25
Model Number: 1050 with model SectionalMotif in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1051 with model SectionalMotif in generation 10 of 25
Template Eval Error: ValueError('operands could not be broadcast together with shapes (120,1) (30,1) ') in model 1051 in generation 10: SectionalMotif
Model Number: 1052 with model SeasonalityMotif in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Template Eval Error: ValueError('operands could not be broadcast together with shapes (150,1) (30,1) ') in model 1052 in generation 10: SeasonalityMotif
Model Number: 1053 with model ConstantNaive in generation 10 of 25
Model Number: 1054 with model UnivariateMotif in generation 10 of 25
Model Number: 1055 with model DatepartRegression in generation 10 of 25
Model Number: 1056 with model UnivariateMotif in generation 10 of 25
Model Number: 1057 with model MetricMotif in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1058 with model MetricMotif in generation 10 of 25
Model Number: 1059 with model Cassandra in generation 10 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

New Generation: 11 of 25
Model Number: 1060 with model MetricMotif in generation 11 of 25
Model Number: 1061 with model UnivariateMotif in generation 11 of 25
Model Number: 1062 with model SeasonalityMotif in generation 11 of 25
Model Number: 1063 with model MetricMotif in generation 11 of 25
Model Number: 1064 with model BasicLinearModel in generation 11 of 25
Model Number: 1065 with model LastValueNaive in generation 11 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1066 with model GLS in generation 11 of 25
Model Number: 1067 with model BasicLinearModel in generation 11 of 25
Model Number: 1068 with model LastValueNaive in generation 11 of 25
Model Number: 1069 with model SectionalMotif in generation 11 of 25
Model Number: 1070 with model UnivariateMotif in generation 11 of 25
Model Number: 1071 with model LastValueNaive in generation 11 of 25
Model Number: 1072 with model Cassandra in generation 11 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1073 with model FFT in generation 11 of 25
Model Number: 1074 with model BasicLinearModel in generation 11 of 25
Model Number: 1075 with model UnivariateMotif in generation 11 of 25
Model Number: 1076 with model LastValueNaive in generation 11 of 25
Model Number: 1077 with model LastValueNaive in generation 11 of 25
Model Number: 1078 with model GLS in generation 11 of 25
Model Number: 1079 with model MetricMotif in generation 11 of 25
Model Number: 1080 with model UnivariateMotif in generation 11 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1081 with model MetricMotif in generation 11 of 25
Template Eval Error: Exception("Transformer Detrend failed on fit from params zero {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': True, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'method': 'clip', 'std_threshold': 3, 'fillna': None}, '2': {'model': 'Linear', 'phi': 1, 'window': None, 'transform_dict': {'fillna': None, 'transformations': {'0': 'AnomalyRemoval'}, 'transformation_params': {'0': {'method': 'zscore', 'transform_dict': {'transformations': {'0': 'DatepartRegression'}, 'transformation_params': {'0': {'datepart_method': 'simple_3', 'regression_model': {'model': 'ElasticNet', 'model_params': {}}}}}, 'method_params': {'distribution': 'uniform', 'alpha': 0.05}}}}}, '3': {'mode': 'downscale', 'factor': 2, 'down_method': 'decimate', 'fill_method': 'pchip'}} with error ValueError('Input y contains NaN.')") in model 1081 in generation 11: MetricMotif
Model Number: 1082 with model SeasonalityMotif in generation 11 of 25
Model Number: 1083 with model BasicLinearModel in generation 11 of 25
Model Number: 1084 with model UnivariateMotif in generation 11 of 25
Model Number: 1085 with model UnivariateMotif in generation 11 of 25
Model Number: 1086 with model MetricMotif in generation 11 of 25
Model Number: 1087 with model ConstantNaive in generation 11 of 25
Model Number: 1088 with model SeasonalityMotif in generation 11 of 25
Model Number: 1089 with model LastValueNaive in generation 11 of 25
Model Number: 1090 with model UnivariateMotif in generation 11 of 25
Model Number: 1091 with model MetricMotif in generation 11 of 25
Model Number: 1092 with model Cassandra in generation 11 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1093 with model GLS in generation 11 of 25
Model Number: 1094 with model DatepartRegression in generation 11 of 25
Model Number: 1095 with model DatepartRegression in generation 11 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params zero {'0': {'numtaps': 128, 'cutoff_hz': 0.5, 'window': 'blackman', 'sampling_frequency': 364, 'on_transform': True, 'on_inverse': False}, '1': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 1}, '2': {'rows': 7, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'mean'}, '3': {'lag_1': 7, 'method': 20}} with error ValueError('BTCD only works on multivarate series')") in model 1095 in generation 11: DatepartRegression
Model Number: 1096 with model Cassandra in generation 11 of 25
Model Number: 1097 with model MetricMotif in generation 11 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1098 with model SectionalMotif in generation 11 of 25
Model Number: 1099 with model GLS in generation 11 of 25
Model Number: 1100 with model BasicLinearModel in generation 11 of 25
Model Number: 1101 with model LastValueNaive in generation 11 of 25
Model Number: 1102 with model AverageValueNaive in generation 11 of 25
Model Number: 1103 with model LastValueNaive in generation 11 of 25
Model Number: 1104 with model BasicLinearModel in generation 11 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

Model Number: 1105 with model MetricMotif in generation 11 of 25
Model Number: 1106 with model BasicLinearModel in generation 11 of 25
Template Eval Error: ValueError('Model BasicLinearModel returned improper forecast_length. Returned: 28 and requested: 30') in model 1106 in generation 11: BasicLinearModel
Model Number: 1107 with model SectionalMotif in generation 11 of 25
Model Number: 1108 with model LastValueNaive in generation 11 of 25
Model Number: 1109 with model ETS in generation 11 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1110 with model SectionalMotif in generation 11 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params akima {'0': {'decimals': 0, 'on_transform': True, 'on_inverse': True}, '1': {}, '2': {}, '3': {'lag': 7, 'fill': 'zero'}, '4': {'det_order': 0, 'k_ar_diff': 1}} with error ValueError('Coint only works on multivarate series')") in model 1110 in generation 11: SectionalMotif
Model Number: 1111 with model LastValueNaive in generation 11 of 25
Model Number: 1112 with model FBProphet in generation 11 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1113 with model ETS in generation 11 of 25
Model Number: 1114 with model DatepartRegression in generation 11 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.782e+09, tolerance: 2.227e+06

Model Number: 1115 with model Cassandra in generation 11 of 25
Model Number: 1116 with model SectionalMotif in generation 11 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1117 with model DatepartRegression in generation 11 of 25
Template Eval Error: InvalidParameterError("The 'alpha' parameter of MLPRegressor must be a float in the range [0, inf). Got None instead.") in model 1117 in generation 11: DatepartRegression
Model Number: 1118 with model DatepartRegression in generation 11 of 25
interpolating
Model Number: 1119 with model UnivariateMotif in generation 11 of 25
Model Number: 1120 with model ETS in generation 11 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_regression.py:494: UserWarning:

One or more samples have no neighbors within specified radius; predicting NaN.

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1121 with model MetricMotif in generation 11 of 25
Model Number: 1122 with model ConstantNaive in generation 11 of 25
New Generation: 12 of 25
Model Number: 1123 with model ETS in generation 12 of 25
Model Number: 1124 with model ARDL in generation 12 of 25
Template Eval Error: ValueError("ARDL series close failed with error ValueError('integer orders must be at least 1 when causal is True.') exog train             weekend  quarter      epoch  month_1  month_2  month_3  month_4  \\\ndate                                                                          \n2023-03-01        0        1  2460004.5      0.0      0.0      1.0      0.0   \n2023-03-02        0        1  2460005.5      0.0      0.0      1.0      0.0   \n2023-03-03        0        1  2460006.5      0.0      0.0      1.0      0.0   \n2023-03-04        1        1  2460007.5      0.0      0.0      1.0      0.0   \n2023-03-05        1        1  2460008.5      0.0      0.0      1.0      0.0   \n...             ...      ...        ...      ...      ...      ...      ...   \n2025-01-25        1        1  2460700.5      1.0      0.0      0.0      0.0   \n2025-01-26        1        1  2460701.5      1.0      0.0      0.0      0.0   \n2025-01-27        0        1  2460702.5      1.0      0.0      0.0      0.0   \n2025-01-28        0        1  2460703.5      1.0      0.0      0.0      0.0   \n2025-01-29        0        1  2460704.5      1.0      0.0      0.0      0.0   \n\n            month_5  month_6  month_7  ...  day_27  day_28  day_29  day_30  \\\ndate                                   ...                                   \n2023-03-01      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2023-03-02      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2023-03-03      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2023-03-04      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2023-03-05      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n...             ...      ...      ...  ...     ...     ...     ...     ...   \n2025-01-25      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-01-26      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-01-27      0.0      0.0      0.0  ...     1.0     0.0     0.0     0.0   \n2025-01-28      0.0      0.0      0.0  ...     0.0     1.0     0.0     0.0   \n2025-01-29      0.0      0.0      0.0  ...     0.0     0.0     1.0     0.0   \n\n            day_31  weekdayofmonth_1  weekdayofmonth_2  weekdayofmonth_3  \\\ndate                                                                       \n2023-03-01     0.0               1.0               0.0               0.0   \n2023-03-02     0.0               1.0               0.0               0.0   \n2023-03-03     0.0               1.0               0.0               0.0   \n2023-03-04     0.0               1.0               0.0               0.0   \n2023-03-05     0.0               1.0               0.0               0.0   \n...            ...               ...               ...               ...   \n2025-01-25     0.0               0.0               0.0               0.0   \n2025-01-26     0.0               0.0               0.0               0.0   \n2025-01-27     0.0               0.0               0.0               0.0   \n2025-01-28     0.0               0.0               0.0               0.0   \n2025-01-29     0.0               0.0               0.0               0.0   \n\n            weekdayofmonth_4  weekdayofmonth_5  \ndate                                            \n2023-03-01               0.0               0.0  \n2023-03-02               0.0               0.0  \n2023-03-03               0.0               0.0  \n2023-03-04               0.0               0.0  \n2023-03-05               0.0               0.0  \n...                      ...               ...  \n2025-01-25               1.0               0.0  \n2025-01-26               1.0               0.0  \n2025-01-27               1.0               0.0  \n2025-01-28               1.0               0.0  \n2025-01-29               0.0               1.0  \n\n[701 rows x 58 columns] and predict             weekend  quarter      epoch  month_1  month_2  month_3  month_4  \\\n2025-01-30        0        1  2460705.5      1.0      0.0      0.0      0.0   \n2025-01-31        0        1  2460706.5      1.0      0.0      0.0      0.0   \n2025-02-01        1        1  2460707.5      0.0      1.0      0.0      0.0   \n2025-02-02        1        1  2460708.5      0.0      1.0      0.0      0.0   \n2025-02-03        0        1  2460709.5      0.0      1.0      0.0      0.0   \n2025-02-04        0        1  2460710.5      0.0      1.0      0.0      0.0   \n2025-02-05        0        1  2460711.5      0.0      1.0      0.0      0.0   \n2025-02-06        0        1  2460712.5      0.0      1.0      0.0      0.0   \n2025-02-07        0        1  2460713.5      0.0      1.0      0.0      0.0   \n2025-02-08        1        1  2460714.5      0.0      1.0      0.0      0.0   \n2025-02-09        1        1  2460715.5      0.0      1.0      0.0      0.0   \n2025-02-10        0        1  2460716.5      0.0      1.0      0.0      0.0   \n2025-02-11        0        1  2460717.5      0.0      1.0      0.0      0.0   \n2025-02-12        0        1  2460718.5      0.0      1.0      0.0      0.0   \n2025-02-13        0        1  2460719.5      0.0      1.0      0.0      0.0   \n2025-02-14        0        1  2460720.5      0.0      1.0      0.0      0.0   \n2025-02-15        1        1  2460721.5      0.0      1.0      0.0      0.0   \n2025-02-16        1        1  2460722.5      0.0      1.0      0.0      0.0   \n2025-02-17        0        1  2460723.5      0.0      1.0      0.0      0.0   \n2025-02-18        0        1  2460724.5      0.0      1.0      0.0      0.0   \n2025-02-19        0        1  2460725.5      0.0      1.0      0.0      0.0   \n2025-02-20        0        1  2460726.5      0.0      1.0      0.0      0.0   \n2025-02-21        0        1  2460727.5      0.0      1.0      0.0      0.0   \n2025-02-22        1        1  2460728.5      0.0      1.0      0.0      0.0   \n2025-02-23        1        1  2460729.5      0.0      1.0      0.0      0.0   \n2025-02-24        0        1  2460730.5      0.0      1.0      0.0      0.0   \n2025-02-25        0        1  2460731.5      0.0      1.0      0.0      0.0   \n2025-02-26        0        1  2460732.5      0.0      1.0      0.0      0.0   \n2025-02-27        0        1  2460733.5      0.0      1.0      0.0      0.0   \n2025-02-28        0        1  2460734.5      0.0      1.0      0.0      0.0   \n\n            month_5  month_6  month_7  ...  day_27  day_28  day_29  day_30  \\\n2025-01-30      0.0      0.0      0.0  ...     0.0     0.0     0.0     1.0   \n2025-01-31      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-01      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-02      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-03      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-04      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-05      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-06      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-07      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-08      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-09      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-10      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-11      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-12      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-13      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-14      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-15      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-16      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-17      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-18      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-19      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-20      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-21      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-22      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-23      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-24      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-25      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-26      0.0      0.0      0.0  ...     0.0     0.0     0.0     0.0   \n2025-02-27      0.0      0.0      0.0  ...     1.0     0.0     0.0     0.0   \n2025-02-28      0.0      0.0      0.0  ...     0.0     1.0     0.0     0.0   \n\n            day_31  weekdayofmonth_1  weekdayofmonth_2  weekdayofmonth_3  \\\n2025-01-30     0.0               0.0               0.0               0.0   \n2025-01-31     1.0               0.0               0.0               0.0   \n2025-02-01     0.0               1.0               0.0               0.0   \n2025-02-02     0.0               1.0               0.0               0.0   \n2025-02-03     0.0               1.0               0.0               0.0   \n2025-02-04     0.0               1.0               0.0               0.0   \n2025-02-05     0.0               1.0               0.0               0.0   \n2025-02-06     0.0               1.0               0.0               0.0   \n2025-02-07     0.0               1.0               0.0               0.0   \n2025-02-08     0.0               0.0               1.0               0.0   \n2025-02-09     0.0               0.0               1.0               0.0   \n2025-02-10     0.0               0.0               1.0               0.0   \n2025-02-11     0.0               0.0               1.0               0.0   \n2025-02-12     0.0               0.0               1.0               0.0   \n2025-02-13     0.0               0.0               1.0               0.0   \n2025-02-14     0.0               0.0               1.0               0.0   \n2025-02-15     0.0               0.0               0.0               1.0   \n2025-02-16     0.0               0.0               0.0               1.0   \n2025-02-17     0.0               0.0               0.0               1.0   \n2025-02-18     0.0               0.0               0.0               1.0   \n2025-02-19     0.0               0.0               0.0               1.0   \n2025-02-20     0.0               0.0               0.0               1.0   \n2025-02-21     0.0               0.0               0.0               1.0   \n2025-02-22     0.0               0.0               0.0               0.0   \n2025-02-23     0.0               0.0               0.0               0.0   \n2025-02-24     0.0               0.0               0.0               0.0   \n2025-02-25     0.0               0.0               0.0               0.0   \n2025-02-26     0.0               0.0               0.0               0.0   \n2025-02-27     0.0               0.0               0.0               0.0   \n2025-02-28     0.0               0.0               0.0               0.0   \n\n            weekdayofmonth_4  weekdayofmonth_5  \n2025-01-30               0.0               1.0  \n2025-01-31               0.0               1.0  \n2025-02-01               0.0               0.0  \n2025-02-02               0.0               0.0  \n2025-02-03               0.0               0.0  \n2025-02-04               0.0               0.0  \n2025-02-05               0.0               0.0  \n2025-02-06               0.0               0.0  \n2025-02-07               0.0               0.0  \n2025-02-08               0.0               0.0  \n2025-02-09               0.0               0.0  \n2025-02-10               0.0               0.0  \n2025-02-11               0.0               0.0  \n2025-02-12               0.0               0.0  \n2025-02-13               0.0               0.0  \n2025-02-14               0.0               0.0  \n2025-02-15               0.0               0.0  \n2025-02-16               0.0               0.0  \n2025-02-17               0.0               0.0  \n2025-02-18               0.0               0.0  \n2025-02-19               0.0               0.0  \n2025-02-20               0.0               0.0  \n2025-02-21               0.0               0.0  \n2025-02-22               1.0               0.0  \n2025-02-23               1.0               0.0  \n2025-02-24               1.0               0.0  \n2025-02-25               1.0               0.0  \n2025-02-26               1.0               0.0  \n2025-02-27               1.0               0.0  \n2025-02-28               1.0               0.0  \n\n[30 rows x 58 columns]") in model 1124 in generation 12: ARDL
Model Number: 1125 with model ConstantNaive in generation 12 of 25
Model Number: 1126 with model MetricMotif in generation 12 of 25
Model Number: 1127 with model MetricMotif in generation 12 of 25
Model Number: 1128 with model DatepartRegression in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1129 with model BasicLinearModel in generation 12 of 25
Model Number: 1130 with model GLS in generation 12 of 25
Model Number: 1131 with model UnivariateMotif in generation 12 of 25
Model Number: 1132 with model LastValueNaive in generation 12 of 25
Model Number: 1133 with model Cassandra in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1134 with model GLS in generation 12 of 25
Model Number: 1135 with model UnivariateMotif in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1136 with model ETS in generation 12 of 25
Model Number: 1137 with model BasicLinearModel in generation 12 of 25
Model Number: 1138 with model Cassandra in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1139 with model DatepartRegression in generation 12 of 25
Model Number: 1140 with model LastValueNaive in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.812e+08, tolerance: 1.637e+05

Model Number: 1141 with model DatepartRegression in generation 12 of 25
Model Number: 1142 with model ConstantNaive in generation 12 of 25
Template Eval Error: Exception("Transformer FastICA failed on fit from params mean {'0': {'algorithm': 'deflation', 'fun': 'exp', 'max_iter': 250, 'whiten': False}, '1': {}, '2': {'method': 'butter', 'method_args': {'N': 5, 'btype': 'highpass', 'analog': False, 'output': 'sos', 'Wn': 0.0027472527472527475}}, '3': {}} with error ValueError('illegal value in 4th argument of internal gesdd')") in model 1142 in generation 12: ConstantNaive
Model Number: 1143 with model SeasonalityMotif in generation 12 of 25
Model Number: 1144 with model MetricMotif in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.087e+10, tolerance: 2.469e+06

/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_fastica.py:583: UserWarning:

Ignoring n_components with whiten=False.

/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_fastica.py:89: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1145 with model SectionalMotif in generation 12 of 25
Model Number: 1146 with model BasicLinearModel in generation 12 of 25
Model Number: 1147 with model ETS in generation 12 of 25
Template Eval Error: Exception('Transformer DatepartRegression failed on fit from params mean {\'0\': {\'regression_model\': {\'model\': \'MLP\', \'model_params\': {\'hidden_layer_sizes\': [72, 36, 72], \'max_iter\': 250, \'activation\': \'tanh\', \'solver\': \'lbfgs\', \'early_stopping\': False, \'learning_rate_init\': 0.001, \'alpha\': None}}, \'datepart_method\': [\'lunar_phase\'], \'polynomial_degree\': None, \'transform_dict\': {\'fillna\': None, \'transformations\': {\'0\': \'AnomalyRemoval\'}, \'transformation_params\': {\'0\': {\'method\': \'zscore\', \'transform_dict\': {\'transformations\': {\'0\': \'DatepartRegression\'}, \'transformation_params\': {\'0\': {\'datepart_method\': \'simple_3\', \'regression_model\': {\'model\': \'ElasticNet\', \'model_params\': {}}}}}, \'method_params\': {\'distribution\': \'uniform\', \'alpha\': 0.05}}}}, \'holiday_countries_used\': False, \'lags\': None, \'forward_lags\': None}, \'1\': {\'rows\': 1, \'lag\': 1, \'method\': \'multiplicative\', \'strength\': 1.0, \'first_value_only\': True, \'threshold\': None, \'threshold_method\': \'max\'}, \'2\': {\'rows\': 1, \'lag\': 1, \'method\': \'additive\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': 1, \'threshold_method\': \'max\'}, \'3\': {}, \'4\': {\'part\': \'trend\', \'lamb\': 129600}} with error InvalidParameterError("The \'alpha\' parameter of MLPRegressor must be a float in the range [0, inf). Got None instead.")') in model 1147 in generation 12: ETS
Model Number: 1148 with model SeasonalityMotif in generation 12 of 25
Model Number: 1149 with model DatepartRegression in generation 12 of 25
Model Number: 1150 with model LastValueNaive in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1151 with model MetricMotif in generation 12 of 25
2025-01-30 00:00:00
2025-01-30 00:00:00
2025-01-30 00:00:00
Template Eval Error: ValueError('Model MetricMotif returned improper forecast_length. Returned: 25 and requested: 30') in model 1151 in generation 12: MetricMotif
Model Number: 1152 with model Cassandra in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1153 with model SectionalMotif in generation 12 of 25
Model Number: 1154 with model Cassandra in generation 12 of 25
Model Number: 1155 with model UnivariateMotif in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1156 with model GLS in generation 12 of 25
Model Number: 1157 with model UnivariateMotif in generation 12 of 25
Model Number: 1158 with model BasicLinearModel in generation 12 of 25
Model Number: 1159 with model SectionalMotif in generation 12 of 25
Model Number: 1160 with model UnivariateMotif in generation 12 of 25
Model Number: 1161 with model ConstantNaive in generation 12 of 25
Template Eval Error: ValueError('operands could not be broadcast together with shapes (90,1) (30,1) ') in model 1161 in generation 12: ConstantNaive
Model Number: 1162 with model DatepartRegression in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1163 with model DatepartRegression in generation 12 of 25
Model Number: 1164 with model GLS in generation 12 of 25
Model Number: 1165 with model ETS in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1166 with model DatepartRegression in generation 12 of 25
Model Number: 1167 with model BasicLinearModel in generation 12 of 25
Model Number: 1168 with model BasicLinearModel in generation 12 of 25
Model Number: 1169 with model Cassandra in generation 12 of 25
Model Number: 1170 with model ARDL in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1171 with model LastValueNaive in generation 12 of 25
Model Number: 1172 with model LastValueNaive in generation 12 of 25
Model Number: 1173 with model DatepartRegression in generation 12 of 25
Model Number: 1174 with model MetricMotif in generation 12 of 25
Template Eval Error: ValueError('operands could not be broadcast together with shapes (150,1) (30,1) ') in model 1174 in generation 12: MetricMotif
Model Number: 1175 with model FBProphet in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.074e-01, tolerance: 8.308e-03

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1176 with model LastValueNaive in generation 12 of 25
Model Number: 1177 with model Cassandra in generation 12 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1178 with model ConstantNaive in generation 12 of 25
Model Number: 1179 with model AverageValueNaive in generation 12 of 25
Model Number: 1180 with model BasicLinearModel in generation 12 of 25
Model Number: 1181 with model BasicLinearModel in generation 12 of 25
Model Number: 1182 with model BasicLinearModel in generation 12 of 25
Model Number: 1183 with model FBProphet in generation 12 of 25
Model Number: 1184 with model MetricMotif in generation 12 of 25
Model Number: 1185 with model BasicLinearModel in generation 12 of 25
New Generation: 13 of 25
Model Number: 1186 with model LastValueNaive in generation 13 of 25
Model Number: 1187 with model AverageValueNaive in generation 13 of 25
Model Number: 1188 with model BasicLinearModel in generation 13 of 25
Template Eval Error: ValueError('operands could not be broadcast together with shapes (90,1) (30,1) ') in model 1188 in generation 13: BasicLinearModel
Model Number: 1189 with model GLS in generation 13 of 25
Model Number: 1190 with model UnivariateMotif in generation 13 of 25
Model Number: 1191 with model UnivariateMotif in generation 13 of 25
Model Number: 1192 with model GLS in generation 13 of 25
Model Number: 1193 with model GLS in generation 13 of 25
Model Number: 1194 with model ConstantNaive in generation 13 of 25
Model Number: 1195 with model LastValueNaive in generation 13 of 25
Model Number: 1196 with model UnivariateMotif in generation 13 of 25
Model Number: 1197 with model GLS in generation 13 of 25
Model Number: 1198 with model DatepartRegression in generation 13 of 25
Model Number: 1199 with model SectionalMotif in generation 13 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params rolling_mean {'0': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}, '1': {'model': 'Linear', 'changepoint_spacing': 180, 'changepoint_distance_end': 6, 'datepart_method': None}, '2': {'rows': 7, 'lag': 1, 'method': 'additive', 'strength': 0.5, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}} with error ValueError('BTCD only works on multivarate series')") in model 1199 in generation 13: SectionalMotif
Model Number: 1200 with model LastValueNaive in generation 13 of 25
Model Number: 1201 with model Cassandra in generation 13 of 25
Model Number: 1202 with model BasicLinearModel in generation 13 of 25
Model Number: 1203 with model UnivariateMotif in generation 13 of 25
Model Number: 1204 with model SeasonalityMotif in generation 13 of 25
Model Number: 1205 with model SectionalMotif in generation 13 of 25
Model Number: 1206 with model ETS in generation 13 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1207 with model ConstantNaive in generation 13 of 25
Model Number: 1208 with model MetricMotif in generation 13 of 25
Model Number: 1209 with model DatepartRegression in generation 13 of 25
Model Number: 1210 with model Cassandra in generation 13 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.547e+08, tolerance: 1.544e+05

Model Number: 1211 with model SeasonalityMotif in generation 13 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1212 with model MetricMotif in generation 13 of 25
Model Number: 1213 with model UnivariateMotif in generation 13 of 25
Model Number: 1214 with model FBProphet in generation 13 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1215 with model SectionalMotif in generation 13 of 25
Model Number: 1216 with model BasicLinearModel in generation 13 of 25
Model Number: 1217 with model Cassandra in generation 13 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1218 with model BasicLinearModel in generation 13 of 25
Model Number: 1219 with model BasicLinearModel in generation 13 of 25
Model Number: 1220 with model FBProphet in generation 13 of 25
2025-01-30 00:00:00
2025-01-30 00:00:00
2025-01-30 00:00:00
Model Number: 1221 with model BasicLinearModel in generation 13 of 25
Model Number: 1222 with model ARDL in generation 13 of 25
Model Number: 1223 with model GLS in generation 13 of 25
Model Number: 1224 with model BasicLinearModel in generation 13 of 25
Model Number: 1225 with model GLS in generation 13 of 25
Model Number: 1226 with model LastValueNaive in generation 13 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1227 with model BasicLinearModel in generation 13 of 25
Model Number: 1228 with model Cassandra in generation 13 of 25
Model Number: 1229 with model DatepartRegression in generation 13 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1230 with model BasicLinearModel in generation 13 of 25
Model Number: 1231 with model LastValueNaive in generation 13 of 25
Model Number: 1232 with model LastValueNaive in generation 13 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params rolling_mean_24 {'0': {'det_order': 1, 'k_ar_diff': 0}, '1': {'det_order': -1, 'k_ar_diff': 0}, '2': {}, '3': {'threshold': 0.9, 'splash_threshold': None, 'use_dayofmonth_holidays': True, 'use_wkdom_holidays': True, 'use_wkdeom_holidays': False, 'use_lunar_holidays': False, 'use_lunar_weekday': False, 'use_islamic_holidays': False, 'use_hebrew_holidays': False, 'use_hindu_holidays': True, 'anomaly_detector_params': {'method': 'rolling_zscore', 'method_params': {'distribution': 'chi2', 'alpha': 0.05, 'rolling_periods': 28, 'center': True}, 'fillna': 'linear', 'transform_dict': {'transformations': {'0': 'DatepartRegression'}, 'transformation_params': {'0': {'datepart_method': 'simple_3', 'regression_model': {'model': 'DecisionTree', 'model_params': {'max_depth': None, 'min_samples_split': 0.1}}}}}, 'isolated_only': True, 'on_inverse': False}, 'remove_excess_anomalies': True, 'impact': 'anomaly_score', 'regression_params': {}}} with error ValueError('Coint only works on multivarate series')") in model 1232 in generation 13: LastValueNaive
Model Number: 1233 with model LastValueNaive in generation 13 of 25
Model Number: 1234 with model MetricMotif in generation 13 of 25
Model Number: 1235 with model BasicLinearModel in generation 13 of 25
Template Eval Error: ValueError('matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 701 is different from 1966)') in model 1235 in generation 13: BasicLinearModel
Model Number: 1236 with model LastValueNaive in generation 13 of 25
Model Number: 1237 with model ConstantNaive in generation 13 of 25
Model Number: 1238 with model GLS in generation 13 of 25
Model Number: 1239 with model Cassandra in generation 13 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 1239 in generation 13: Cassandra
Model Number: 1240 with model LastValueNaive in generation 13 of 25
Model Number: 1241 with model LastValueNaive in generation 13 of 25
Model Number: 1242 with model AverageValueNaive in generation 13 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1243 with model GLS in generation 13 of 25
Model Number: 1244 with model ETS in generation 13 of 25
Model Number: 1245 with model BasicLinearModel in generation 13 of 25
Model Number: 1246 with model BasicLinearModel in generation 13 of 25
Model Number: 1247 with model MetricMotif in generation 13 of 25
Model Number: 1248 with model ConstantNaive in generation 13 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

New Generation: 14 of 25
Model Number: 1249 with model SeasonalityMotif in generation 14 of 25
Model Number: 1250 with model SeasonalityMotif in generation 14 of 25
Template Eval Error: Exception('Transformer PCA failed on fit from params ffill {\'0\': {\'decimals\': 0, \'on_transform\': True, \'on_inverse\': True}, \'1\': {\'rows\': 7}, \'2\': {\'whiten\': False, \'n_components\': 100}, \'3\': {\'n_harmonics\': -0.95, \'detrend\': \'quadratic\'}} with error ValueError("n_components=100 must be between 0 and min(n_samples, n_features)=1 with svd_solver=\'full\'")') in model 1250 in generation 14: SeasonalityMotif
Model Number: 1251 with model BasicLinearModel in generation 14 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params quadratic {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'mean'}, '1': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 1}, '2': {}} with error ValueError('BTCD only works on multivarate series')") in model 1251 in generation 14: BasicLinearModel
Model Number: 1252 with model SeasonalityMotif in generation 14 of 25
Model Number: 1253 with model GLS in generation 14 of 25
Model Number: 1254 with model MetricMotif in generation 14 of 25
Model Number: 1255 with model SeasonalityMotif in generation 14 of 25
Model Number: 1256 with model BasicLinearModel in generation 14 of 25
Model Number: 1257 with model ConstantNaive in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

Model Number: 1258 with model Cassandra in generation 14 of 25
Model Number: 1259 with model BasicLinearModel in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1260 with model BasicLinearModel in generation 14 of 25
Model Number: 1261 with model SectionalMotif in generation 14 of 25
Model Number: 1262 with model LastValueNaive in generation 14 of 25
Model Number: 1263 with model GLS in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1264 with model LastValueNaive in generation 14 of 25
Model Number: 1265 with model MetricMotif in generation 14 of 25
Model Number: 1266 with model AverageValueNaive in generation 14 of 25
Model Number: 1267 with model ETS in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1268 with model UnivariateMotif in generation 14 of 25
Model Number: 1269 with model DatepartRegression in generation 14 of 25
Model Number: 1270 with model Cassandra in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1271 with model GLS in generation 14 of 25
Model Number: 1272 with model MetricMotif in generation 14 of 25
Model Number: 1273 with model DatepartRegression in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1274 with model BasicLinearModel in generation 14 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params quadratic {'0': {'decimals': 0, 'on_transform': True, 'on_inverse': True}, '1': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 1}} with error ValueError('BTCD only works on multivarate series')") in model 1274 in generation 14: BasicLinearModel
Model Number: 1275 with model BasicLinearModel in generation 14 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1275 in generation 14: BasicLinearModel
Model Number: 1276 with model MetricMotif in generation 14 of 25
Model Number: 1277 with model BasicLinearModel in generation 14 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1277 in generation 14: BasicLinearModel
Model Number: 1278 with model MetricMotif in generation 14 of 25
Model Number: 1279 with model Cassandra in generation 14 of 25
Model Number: 1280 with model Cassandra in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

Model Number: 1281 with model ConstantNaive in generation 14 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params zero {'0': {'numtaps': 1024, 'cutoff_hz': 0.1, 'window': 'hamming', 'sampling_frequency': 28, 'on_transform': True, 'on_inverse': False}, '1': {'lag': 1, 'fill': 'zero'}, '2': {'method': 'butter', 'method_args': {'N': 5, 'btype': 'highpass', 'analog': False, 'output': 'sos', 'Wn': 0.0027472527472527475}}, '3': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gbtree', 'max_depth': 3, 'eta': 0.3, 'min_child_weight': 0.5, 'subsample': 1, 'colsample_bylevel': 1, 'reg_alpha': 0, 'reg_lambda': 1, 'n_estimators': 10}, 'datepart_method': 'simple_binarized'}, 'fillna': 'ffill'}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 1281 in generation 14: ConstantNaive
Model Number: 1282 with model LastValueNaive in generation 14 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params rolling_mean_24 {'0': {'method': 'savgol_filter', 'method_args': {'window_length': 7, 'polyorder': 2, 'deriv': 0, 'mode': 'mirror'}}, '1': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gbtree', 'max_depth': 3, 'eta': 0.003, 'min_child_weight': 1, 'subsample': 1, 'colsample_bylevel': 0.9, 'reg_alpha': 0, 'reg_lambda': 1, 'n_estimators': 10}, 'datepart_method': 'expanded'}, 'fillna': 'pchip'}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 1282 in generation 14: LastValueNaive
Model Number: 1283 with model MetricMotif in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1284 with model GLS in generation 14 of 25
Model Number: 1285 with model SectionalMotif in generation 14 of 25
Model Number: 1286 with model MetricMotif in generation 14 of 25
Model Number: 1287 with model FBProphet in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1288 with model ETS in generation 14 of 25
Model Number: 1289 with model UnivariateMotif in generation 14 of 25
Model Number: 1290 with model ETS in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1291 with model Cassandra in generation 14 of 25
Model Number: 1292 with model MetricMotif in generation 14 of 25
Model Number: 1293 with model UnivariateMotif in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1294 with model BasicLinearModel in generation 14 of 25
Model Number: 1295 with model BasicLinearModel in generation 14 of 25
Model Number: 1296 with model GLS in generation 14 of 25
Model Number: 1297 with model GLS in generation 14 of 25
Model Number: 1298 with model DatepartRegression in generation 14 of 25
Model Number: 1299 with model BasicLinearModel in generation 14 of 25
Model Number: 1300 with model SectionalMotif in generation 14 of 25
Template Eval Error: Exception("Transformer Detrend failed on fit from params rolling_mean_24 {'0': {'output_distribution': 'uniform', 'n_quantiles': 233}, '1': {'method': 'clip', 'std_threshold': 2, 'fillna': None}, '2': {}, '3': {'model': 'Poisson', 'phi': 1, 'window': 90, 'transform_dict': {'fillna': None, 'transformations': {'0': 'bkfilter'}, 'transformation_params': {'0': {}}}}} with error ValueError('Found input variables with inconsistent numbers of samples: [90, 701]')") in model 1300 in generation 14: SectionalMotif
Model Number: 1301 with model FBProphet in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1302 with model SectionalMotif in generation 14 of 25
Model Number: 1303 with model LastValueNaive in generation 14 of 25
Model Number: 1304 with model ARDL in generation 14 of 25
Model Number: 1305 with model DatepartRegression in generation 14 of 25
Model Number: 1306 with model Cassandra in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.768e+09, tolerance: 2.225e+06

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1307 with model AverageValueNaive in generation 14 of 25
Model Number: 1308 with model UnivariateMotif in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1309 with model GLS in generation 14 of 25
Model Number: 1310 with model ETS in generation 14 of 25
Model Number: 1311 with model FBProphet in generation 14 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

New Generation: 15 of 25
Model Number: 1312 with model GLS in generation 15 of 25
Model Number: 1313 with model BasicLinearModel in generation 15 of 25
Model Number: 1314 with model Cassandra in generation 15 of 25
Model Number: 1315 with model Cassandra in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1316 with model GLS in generation 15 of 25
Model Number: 1317 with model ConstantNaive in generation 15 of 25
Model Number: 1318 with model LastValueNaive in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1319 with model SeasonalityMotif in generation 15 of 25
Model Number: 1320 with model LastValueNaive in generation 15 of 25
Model Number: 1321 with model GLS in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1322 with model BasicLinearModel in generation 15 of 25
Model Number: 1323 with model SeasonalityMotif in generation 15 of 25
Model Number: 1324 with model AverageValueNaive in generation 15 of 25
Model Number: 1325 with model Cassandra in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1326 with model MetricMotif in generation 15 of 25
Model Number: 1327 with model AverageValueNaive in generation 15 of 25
Model Number: 1328 with model DatepartRegression in generation 15 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1328 in generation 15: DatepartRegression
Model Number: 1329 with model Cassandra in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1330 with model GLS in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1331 with model FBProphet in generation 15 of 25
Model Number: 1332 with model DatepartRegression in generation 15 of 25
Model Number: 1333 with model GLS in generation 15 of 25
Model Number: 1334 with model Cassandra in generation 15 of 25
Model Number: 1335 with model ARDL in generation 15 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params pchip {'0': {}, '1': {'model': 'Linear', 'changepoint_spacing': 180, 'changepoint_distance_end': 6, 'datepart_method': None}, '2': {}, '3': {'det_order': 0, 'k_ar_diff': 2}} with error ValueError('Coint only works on multivarate series')") in model 1335 in generation 15: ARDL
Model Number: 1336 with model LastValueNaive in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1337 with model BasicLinearModel in generation 15 of 25
Model Number: 1338 with model BasicLinearModel in generation 15 of 25
Model Number: 1339 with model FBProphet in generation 15 of 25
Model Number: 1340 with model MetricMotif in generation 15 of 25
Model Number: 1341 with model AverageValueNaive in generation 15 of 25
Model Number: 1342 with model LastValueNaive in generation 15 of 25
Model Number: 1343 with model LastValueNaive in generation 15 of 25
Model Number: 1344 with model ConstantNaive in generation 15 of 25
Model Number: 1345 with model MetricMotif in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1346 with model DatepartRegression in generation 15 of 25
Model Number: 1347 with model BasicLinearModel in generation 15 of 25
Model Number: 1348 with model DatepartRegression in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.040e+10, tolerance: 2.394e+06

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.797e+00, tolerance: 1.263e-02

Model Number: 1349 with model BasicLinearModel in generation 15 of 25
Model Number: 1350 with model Cassandra in generation 15 of 25
Model Number: 1351 with model LastValueNaive in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1352 with model BasicLinearModel in generation 15 of 25
Model Number: 1353 with model BasicLinearModel in generation 15 of 25
Model Number: 1354 with model SectionalMotif in generation 15 of 25
Model Number: 1355 with model ETS in generation 15 of 25
Model Number: 1356 with model AverageValueNaive in generation 15 of 25
Model Number: 1357 with model AverageValueNaive in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

Model Number: 1358 with model SeasonalityMotif in generation 15 of 25
Model Number: 1359 with model AverageValueNaive in generation 15 of 25
Model Number: 1360 with model GLS in generation 15 of 25
Model Number: 1361 with model ARDL in generation 15 of 25
Model Number: 1362 with model FBProphet in generation 15 of 25
No anomalies detected.

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1363 with model Cassandra in generation 15 of 25
Model Number: 1364 with model UnivariateMotif in generation 15 of 25
Model Number: 1365 with model Cassandra in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1366 with model BasicLinearModel in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1367 with model AverageValueNaive in generation 15 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params mean {'0': {'method': 'minmax', 'method_params': {'alpha': 0.03}, 'fillna': 'linear', 'transform_dict': None, 'isolated_only': False, 'on_inverse': False}, '1': {'discretization': 'center', 'n_bins': 50}, '2': {}, '3': {'det_order': 1, 'k_ar_diff': 1}, '4': {'part': 'trend', 'lamb': 129600}} with error ValueError('Coint only works on multivarate series')") in model 1367 in generation 15: AverageValueNaive
Model Number: 1368 with model BasicLinearModel in generation 15 of 25
Model Number: 1369 with model BasicLinearModel in generation 15 of 25
Model Number: 1370 with model ARDL in generation 15 of 25
Model Number: 1371 with model AverageValueNaive in generation 15 of 25
Model Number: 1372 with model Cassandra in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1373 with model Cassandra in generation 15 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Template Eval Error: KeyError("['changepoint_1'] not in index") in model 1373 in generation 15: Cassandra
Model Number: 1374 with model SeasonalityMotif in generation 15 of 25
New Generation: 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1375 with model FBProphet in generation 16 of 25
No anomalies detected.
Model Number: 1376 with model FBProphet in generation 16 of 25
Model Number: 1377 with model Cassandra in generation 16 of 25
Model Number: 1378 with model SectionalMotif in generation 16 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1378 in generation 16: SectionalMotif
Model Number: 1379 with model MetricMotif in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1380 with model GLS in generation 16 of 25
Model Number: 1381 with model ETS in generation 16 of 25
Model Number: 1382 with model Cassandra in generation 16 of 25
Model Number: 1383 with model BasicLinearModel in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

SVD did not converge, attempting more robust approach...
Template Eval Error: Exception("Transformer KalmanSmoothing failed on fit from params ffill {'0': {}, '1': {'model_name': 'ucm_deterministictrend_seasonal7', 'state_transition': [[1, 1, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0], [0, 0, -1, -1, -1, -1, -1, -1]], 'process_noise': [[0.001, 0, 0, 0, 0, 0, 0, 0], [0, 0.001, 0, 0, 0, 0, 0, 0], [0, 0, 0.001, 0, 0, 0, 0, 0], [0, 0, 0, 0.001, 0, 0, 0, 0], [0, 0, 0, 0, 0.001, 0, 0, 0], [0, 0, 0, 0, 0, 0.001, 0, 0], [0, 0, 0, 0, 0, 0, 0.001, 0], [0, 0, 0, 0, 0, 0, 0, 0]], 'observation_model': [[1, 0, 1, 1, 1, 1, 1, 1]], 'observation_noise': 0.1, 'em_iter': 30, 'on_transform': True, 'on_inverse': False}, '2': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'max'}} with error LinAlgError('SVD did not converge')") in model 1383 in generation 16: BasicLinearModel
Model Number: 1384 with model GLS in generation 16 of 25
Model Number: 1385 with model AverageValueNaive in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/fast_kalman.py:1137: RuntimeWarning:

overflow encountered in cast

/usr/local/lib/python3.10/dist-packages/autots/tools/fast_kalman.py:1143: RuntimeWarning:

overflow encountered in cast

/usr/local/lib/python3.10/dist-packages/autots/tools/fast_kalman.py:1354: RuntimeWarning:

invalid value encountered in matmul

/usr/local/lib/python3.10/dist-packages/autots/tools/fast_kalman.py:1341: RuntimeWarning:

invalid value encountered in matmul

Model Number: 1386 with model ETS in generation 16 of 25
Model Number: 1387 with model DatepartRegression in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.510e+10, tolerance: 3.482e+07

Model Number: 1388 with model BasicLinearModel in generation 16 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1388 in generation 16: BasicLinearModel
Model Number: 1389 with model UnivariateMotif in generation 16 of 25
Model Number: 1390 with model MetricMotif in generation 16 of 25
Model Number: 1391 with model GLS in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1392 with model BasicLinearModel in generation 16 of 25
Model Number: 1393 with model BasicLinearModel in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1394 with model ETS in generation 16 of 25
Model Number: 1395 with model LastValueNaive in generation 16 of 25
Model Number: 1396 with model Cassandra in generation 16 of 25
Template Eval Error: ValueError('seasonality is_month_start creation error') in model 1396 in generation 16: Cassandra
Model Number: 1397 with model BasicLinearModel in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1398 with model DatepartRegression in generation 16 of 25
Model Number: 1399 with model SeasonalityMotif in generation 16 of 25
Template Eval Error: Exception("Transformer Detrend failed on fit from params fake_date {'0': {}, '1': {'model': 'Tweedie', 'phi': 1, 'window': 90, 'transform_dict': {'fillna': None, 'transformations': {'0': 'EWMAFilter'}, 'transformation_params': {'0': {'span': 2}}}}} with error ValueError('Found input variables with inconsistent numbers of samples: [90, 701]')") in model 1399 in generation 16: SeasonalityMotif
Model Number: 1400 with model Cassandra in generation 16 of 25
Template Eval Error: ValueError('seasonality is_month_start creation error') in model 1400 in generation 16: Cassandra
Model Number: 1401 with model ConstantNaive in generation 16 of 25
Model Number: 1402 with model Cassandra in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1403 with model BasicLinearModel in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

13:35:03 - cmdstanpy - ERROR - Chain [1] error: error during processing Operation not permitted

Template Eval Error: ValueError('matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 701 is different from 1966)') in model 1403 in generation 16: BasicLinearModel
Model Number: 1404 with model FBProphet in generation 16 of 25
Model Number: 1405 with model GLS in generation 16 of 25
Model Number: 1406 with model DatepartRegression in generation 16 of 25
Model Number: 1407 with model SectionalMotif in generation 16 of 25
Model Number: 1408 with model AverageValueNaive in generation 16 of 25
Model Number: 1409 with model MetricMotif in generation 16 of 25
Model Number: 1410 with model AverageValueNaive in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1411 with model MetricMotif in generation 16 of 25
Model Number: 1412 with model GLS in generation 16 of 25
Model Number: 1413 with model ConstantNaive in generation 16 of 25
Model Number: 1414 with model Cassandra in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1415 with model AverageValueNaive in generation 16 of 25
Model Number: 1416 with model MetricMotif in generation 16 of 25
Model Number: 1417 with model ConstantNaive in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1418 with model ETS in generation 16 of 25
Model Number: 1419 with model DatepartRegression in generation 16 of 25
Model Number: 1420 with model LastValueNaive in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.916e+06, tolerance: 5.953e+02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1421 with model GLS in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1422 with model UnivariateMotif in generation 16 of 25
Model Number: 1423 with model UnivariateMotif in generation 16 of 25
Model Number: 1424 with model MetricMotif in generation 16 of 25
Model Number: 1425 with model AverageValueNaive in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1426 with model Cassandra in generation 16 of 25
Model Number: 1427 with model SeasonalityMotif in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1428 with model BasicLinearModel in generation 16 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1428 in generation 16: BasicLinearModel
Model Number: 1429 with model AverageValueNaive in generation 16 of 25
Model Number: 1430 with model SeasonalityMotif in generation 16 of 25
Model Number: 1431 with model AverageValueNaive in generation 16 of 25
Model Number: 1432 with model SectionalMotif in generation 16 of 25
Model Number: 1433 with model AverageValueNaive in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1434 with model Cassandra in generation 16 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 1435 with model SectionalMotif in generation 16 of 25
Model Number: 1436 with model MetricMotif in generation 16 of 25
Model Number: 1437 with model AverageValueNaive in generation 16 of 25
New Generation: 17 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

Model Number: 1438 with model GLS in generation 17 of 25
Model Number: 1439 with model AverageValueNaive in generation 17 of 25
Model Number: 1440 with model Cassandra in generation 17 of 25
Model Number: 1441 with model Cassandra in generation 17 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

Model Number: 1442 with model AverageValueNaive in generation 17 of 25
Model Number: 1443 with model MetricMotif in generation 17 of 25
Model Number: 1444 with model Cassandra in generation 17 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Template Eval Error: ValueError('Only gave one variable to VAR') in model 1444 in generation 17: Cassandra
Model Number: 1445 with model DatepartRegression in generation 17 of 25
Template Eval Error: IndexError('tuple index out of range') in model 1445 in generation 17: DatepartRegression
Model Number: 1446 with model GLS in generation 17 of 25
Model Number: 1447 with model LastValueNaive in generation 17 of 25
Model Number: 1448 with model SectionalMotif in generation 17 of 25
Model Number: 1449 with model MetricMotif in generation 17 of 25
Model Number: 1450 with model AverageValueNaive in generation 17 of 25
Model Number: 1451 with model ETS in generation 17 of 25
Model Number: 1452 with model LastValueNaive in generation 17 of 25
Model Number: 1453 with model MetricMotif in generation 17 of 25
Model Number: 1454 with model ConstantNaive in generation 17 of 25
Model Number: 1455 with model AverageValueNaive in generation 17 of 25
Model Number: 1456 with model GLS in generation 17 of 25
Model Number: 1457 with model FBProphet in generation 17 of 25
No anomalies detected.
Model Number: 1458 with model ETS in generation 17 of 25
Model Number: 1459 with model AverageValueNaive in generation 17 of 25
Model Number: 1460 with model BasicLinearModel in generation 17 of 25
Model Number: 1461 with model GLS in generation 17 of 25
Model Number: 1462 with model DatepartRegression in generation 17 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

Model Number: 1463 with model Cassandra in generation 17 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.576e+00, tolerance: 1.265e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1464 with model BasicLinearModel in generation 17 of 25
Model Number: 1465 with model ETS in generation 17 of 25
Model Number: 1466 with model LastValueNaive in generation 17 of 25
Model Number: 1467 with model BasicLinearModel in generation 17 of 25
Model Number: 1468 with model ETS in generation 17 of 25
Model Number: 1469 with model Cassandra in generation 17 of 25
Model Number: 1470 with model BasicLinearModel in generation 17 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1470 in generation 17: BasicLinearModel
Model Number: 1471 with model BasicLinearModel in generation 17 of 25
Model Number: 1472 with model FBProphet in generation 17 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1473 with model MetricMotif in generation 17 of 25
Model Number: 1474 with model Cassandra in generation 17 of 25
Model Number: 1475 with model DatepartRegression in generation 17 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1475 in generation 17: DatepartRegression
Model Number: 1476 with model AverageValueNaive in generation 17 of 25
Model Number: 1477 with model BasicLinearModel in generation 17 of 25
Model Number: 1478 with model AverageValueNaive in generation 17 of 25
Model Number: 1479 with model Cassandra in generation 17 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

Model Number: 1480 with model Cassandra in generation 17 of 25
Model Number: 1481 with model FBProphet in generation 17 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

13:35:30 - cmdstanpy - ERROR - Chain [1] error: error during processing Operation not permitted

Model Number: 1482 with model UnivariateMotif in generation 17 of 25
Model Number: 1483 with model GLS in generation 17 of 25
Model Number: 1484 with model ETS in generation 17 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1485 with model SectionalMotif in generation 17 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1485 in generation 17: SectionalMotif
Model Number: 1486 with model SectionalMotif in generation 17 of 25
Model Number: 1487 with model ETS in generation 17 of 25
Model Number: 1488 with model GLS in generation 17 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1489 with model BasicLinearModel in generation 17 of 25
Model Number: 1490 with model DatepartRegression in generation 17 of 25
Model Number: 1491 with model BasicLinearModel in generation 17 of 25
Model Number: 1492 with model ETS in generation 17 of 25
Model Number: 1493 with model Cassandra in generation 17 of 25
Model Number: 1494 with model MetricMotif in generation 17 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Template Eval Error: Exception("Transformer BTCD failed on fit from params ffill {'0': {}, '1': {}, '2': {'model_name': 'spline', 'state_transition': [[2, -1], [1, 0]], 'process_noise': [[1, 0], [0, 0]], 'observation_model': [[1, 0]], 'observation_noise': 0.1, 'em_iter': 10, 'on_transform': True, 'on_inverse': False}, '3': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}} with error ValueError('BTCD only works on multivarate series')") in model 1494 in generation 17: MetricMotif
Model Number: 1495 with model UnivariateMotif in generation 17 of 25
Model Number: 1496 with model AverageValueNaive in generation 17 of 25
Model Number: 1497 with model AverageValueNaive in generation 17 of 25
Model Number: 1498 with model GLS in generation 17 of 25
Model Number: 1499 with model UnivariateMotif in generation 17 of 25
Template Eval Error: Exception("Transformer DatepartRegression failed on fit from params mean {'0': {'regression_model': {'model': 'KNN', 'model_params': {'n_neighbors': 10, 'weights': 'uniform', 'p': 1, 'leaf_size': 30}}, 'datepart_method': 'expanded_binarized', 'polynomial_degree': None, 'transform_dict': {'fillna': None, 'transformations': {'0': 'bkfilter'}, 'transformation_params': {'0': {}}}, 'holiday_countries_used': True, 'lags': None, 'forward_lags': 2}, '1': {'model': 'Linear', 'changepoint_spacing': 180, 'changepoint_distance_end': 6, 'datepart_method': None}, '2': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}, '3': {}, '4': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'mean'}, '5': {'model': 'Linear', 'changepoint_spacing': 5040, 'changepoint_distance_end': 5040, 'datepart_method': None}} with error ValueError('Found input variables with inconsistent numbers of samples: [1966, 701]')") in model 1499 in generation 17: UnivariateMotif
Model Number: 1500 with model GLS in generation 17 of 25
New Generation: 18 of 25
Model Number: 1501 with model AverageValueNaive in generation 18 of 25
Model Number: 1502 with model BasicLinearModel in generation 18 of 25
Model Number: 1503 with model UnivariateMotif in generation 18 of 25
Model Number: 1504 with model BasicLinearModel in generation 18 of 25
Model Number: 1505 with model LastValueNaive in generation 18 of 25
Model Number: 1506 with model UnivariateMotif in generation 18 of 25
Model Number: 1507 with model LastValueNaive in generation 18 of 25
Model Number: 1508 with model Cassandra in generation 18 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1509 with model LastValueNaive in generation 18 of 25
Model Number: 1510 with model AverageValueNaive in generation 18 of 25
Model Number: 1511 with model Cassandra in generation 18 of 25
Model Number: 1512 with model Cassandra in generation 18 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Template Eval Error: UnboundLocalError("local variable 'slope' referenced before assignment") in model 1512 in generation 18: Cassandra
Model Number: 1513 with model GLS in generation 18 of 25
Template Eval Error: ValueError('operands could not be broadcast together with shapes (120,1) (30,1) ') in model 1513 in generation 18: GLS
Model Number: 1514 with model AverageValueNaive in generation 18 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params ffill {'0': {'method': 'minmax', 'method_params': {'alpha': 0.03}, 'fillna': 'linear', 'transform_dict': None, 'isolated_only': False, 'on_inverse': False}, '1': {'model': 'Linear', 'changepoint_spacing': 180, 'changepoint_distance_end': 6, 'datepart_method': None}, '2': {}, '3': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 2}} with error ValueError('BTCD only works on multivarate series')") in model 1514 in generation 18: AverageValueNaive
Model Number: 1515 with model BasicLinearModel in generation 18 of 25
Model Number: 1516 with model SeasonalityMotif in generation 18 of 25
Model Number: 1517 with model DatepartRegression in generation 18 of 25
Model Number: 1518 with model FBProphet in generation 18 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.119e+10, tolerance: 2.531e+06

Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1518 in generation 18: FBProphet
Model Number: 1519 with model GLS in generation 18 of 25
Model Number: 1520 with model ConstantNaive in generation 18 of 25
Model Number: 1521 with model LastValueNaive in generation 18 of 25
Model Number: 1522 with model DatepartRegression in generation 18 of 25
Template Eval Error: ValueError('Input X contains NaN.\nAdaBoostRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values') in model 1522 in generation 18: DatepartRegression
Model Number: 1523 with model AverageValueNaive in generation 18 of 25
Model Number: 1524 with model LastValueNaive in generation 18 of 25
Model Number: 1525 with model GLS in generation 18 of 25
Model Number: 1526 with model AverageValueNaive in generation 18 of 25
Model Number: 1527 with model SeasonalityMotif in generation 18 of 25
Model Number: 1528 with model GLS in generation 18 of 25
Model Number: 1529 with model DatepartRegression in generation 18 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1529 in generation 18: DatepartRegression
Model Number: 1530 with model GLS in generation 18 of 25
Model Number: 1531 with model AverageValueNaive in generation 18 of 25
Model Number: 1532 with model Cassandra in generation 18 of 25
Model Number: 1533 with model MetricMotif in generation 18 of 25
Template Eval Error: Exception('Transformer PCA failed on fit from params zero {\'0\': {\'whiten\': False, \'n_components\': 10}, \'1\': {\'lag\': 1, \'fill\': \'bfill\'}, \'2\': {\'regression_model\': {\'model\': \'SVM\', \'model_params\': {\'C\': 1.0, \'tol\': 0.0001, \'loss\': \'squared_epsilon_insensitive\', \'max_iter\': 500}}, \'datepart_method\': \'common_fourier_rw\', \'polynomial_degree\': None, \'transform_dict\': {\'fillna\': None, \'transformations\': {\'0\': \'EWMAFilter\'}, \'transformation_params\': {\'0\': {\'span\': 2}}}, \'holiday_countries_used\': False, \'lags\': None, \'forward_lags\': None}} with error ValueError("n_components=10 must be between 0 and min(n_samples, n_features)=1 with svd_solver=\'full\'")') in model 1533 in generation 18: MetricMotif
Model Number: 1534 with model ARDL in generation 18 of 25
Model Number: 1535 with model LastValueNaive in generation 18 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1536 with model BasicLinearModel in generation 18 of 25
Model Number: 1537 with model ARDL in generation 18 of 25
Model Number: 1538 with model BasicLinearModel in generation 18 of 25
Model Number: 1539 with model SectionalMotif in generation 18 of 25
Model Number: 1540 with model DatepartRegression in generation 18 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.093e+10, tolerance: 3.569e+07

Model Number: 1541 with model BasicLinearModel in generation 18 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params cubic {'0': {'det_order': 0, 'k_ar_diff': 0}, '1': {'window_size': 14, 'alpha': 2.0, 'grouping_forward_limit': 3, 'max_level_shifts': 5, 'alignment': 'rolling_diff_3nn'}, '2': {'n_harmonics': 10, 'detrend': 'quadratic'}} with error ValueError('Coint only works on multivarate series')") in model 1541 in generation 18: BasicLinearModel
Model Number: 1542 with model ETS in generation 18 of 25
Model Number: 1543 with model DatepartRegression in generation 18 of 25
Model Number: 1544 with model FBProphet in generation 18 of 25
No anomalies detected.
Model Number: 1545 with model SectionalMotif in generation 18 of 25
Model Number: 1546 with model GLS in generation 18 of 25
Model Number: 1547 with model LastValueNaive in generation 18 of 25
Model Number: 1548 with model BasicLinearModel in generation 18 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1548 in generation 18: BasicLinearModel
Model Number: 1549 with model LastValueNaive in generation 18 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1550 with model ETS in generation 18 of 25
Model Number: 1551 with model ConstantNaive in generation 18 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Template Eval Error: Exception("Transformer HolidayTransformer failed on fit from params quadratic {'0': {'threshold': 0.9, 'splash_threshold': None, 'use_dayofmonth_holidays': True, 'use_wkdom_holidays': False, 'use_wkdeom_holidays': False, 'use_lunar_holidays': True, 'use_lunar_weekday': False, 'use_islamic_holidays': False, 'use_hebrew_holidays': True, 'use_hindu_holidays': False, 'anomaly_detector_params': {'method': 'zscore', 'method_params': {'distribution': 'norm', 'alpha': 0.1}, 'fillna': 'fake_date', 'transform_dict': None, 'isolated_only': False, 'on_inverse': False}, 'remove_excess_anomalies': True, 'impact': 'regression', 'regression_params': {}}, '1': {'rows': 1, 'lag': 84, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}} with error ValueError('operands could not be broadcast together with shapes (701,1) (693,1) ')") in model 1551 in generation 18: ConstantNaive
Model Number: 1552 with model AverageValueNaive in generation 18 of 25
Model Number: 1553 with model FBProphet in generation 18 of 25
Model Number: 1554 with model MetricMotif in generation 18 of 25
Model Number: 1555 with model Cassandra in generation 18 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1556 with model GLS in generation 18 of 25
Model Number: 1557 with model AverageValueNaive in generation 18 of 25
Model Number: 1558 with model GLS in generation 18 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Template Eval Error: ValueError('operands could not be broadcast together with shapes (120,1) (30,1) ') in model 1558 in generation 18: GLS
Model Number: 1559 with model AverageValueNaive in generation 18 of 25
Model Number: 1560 with model BasicLinearModel in generation 18 of 25
Model Number: 1561 with model MetricMotif in generation 18 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params zero {'0': {'mode': 'downscale', 'factor': 3, 'down_method': 'decimate', 'fill_method': 'linear'}, '1': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}, '2': {}, '3': {'det_order': 1, 'k_ar_diff': 0}} with error ValueError('BTCD only works on multivarate series')") in model 1561 in generation 18: MetricMotif
Model Number: 1562 with model BasicLinearModel in generation 18 of 25
Model Number: 1563 with model Cassandra in generation 18 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

New Generation: 19 of 25
Model Number: 1564 with model FBProphet in generation 19 of 25
Model Number: 1565 with model UnivariateMotif in generation 19 of 25
Model Number: 1566 with model BasicLinearModel in generation 19 of 25
Model Number: 1567 with model GLS in generation 19 of 25
Model Number: 1568 with model BasicLinearModel in generation 19 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params cubic {'0': {'rows': 7, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {}, '2': {'det_order': 0, 'k_ar_diff': 1}} with error ValueError('Coint only works on multivarate series')") in model 1568 in generation 19: BasicLinearModel
Model Number: 1569 with model AverageValueNaive in generation 19 of 25
Model Number: 1570 with model MetricMotif in generation 19 of 25
Model Number: 1571 with model MetricMotif in generation 19 of 25
Model Number: 1572 with model DatepartRegression in generation 19 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.797e+00, tolerance: 1.263e-02

Model Number: 1573 with model DatepartRegression in generation 19 of 25
Model Number: 1574 with model ARDL in generation 19 of 25
Model Number: 1575 with model BasicLinearModel in generation 19 of 25
Model Number: 1576 with model AverageValueNaive in generation 19 of 25
Model Number: 1577 with model Cassandra in generation 19 of 25
Model Number: 1578 with model UnivariateMotif in generation 19 of 25
Model Number: 1579 with model GLS in generation 19 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1580 with model BasicLinearModel in generation 19 of 25
Model Number: 1581 with model GLS in generation 19 of 25
Model Number: 1582 with model UnivariateMotif in generation 19 of 25
Model Number: 1583 with model FBProphet in generation 19 of 25
Model Number: 1584 with model FBProphet in generation 19 of 25
Model Number: 1585 with model ETS in generation 19 of 25
Model Number: 1586 with model AverageValueNaive in generation 19 of 25
Model Number: 1587 with model ETS in generation 19 of 25
Model Number: 1588 with model MetricMotif in generation 19 of 25
Template Eval Error: IndexError('index 655 is out of bounds for axis 0 with size 350') in model 1588 in generation 19: MetricMotif
Model Number: 1589 with model MetricMotif in generation 19 of 25
Model Number: 1590 with model AverageValueNaive in generation 19 of 25
Model Number: 1591 with model DatepartRegression in generation 19 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1592 with model LastValueNaive in generation 19 of 25
Model Number: 1593 with model FBProphet in generation 19 of 25
Model Number: 1594 with model DatepartRegression in generation 19 of 25
Epoch 1/50

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

44/44 ━━━━━━━━━━━━━━━━━━━━ 6s 24ms/step - loss: 0.0447
Epoch 2/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0388
Epoch 3/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0393
Epoch 4/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0399
Epoch 5/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0400
Epoch 6/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0399
Epoch 7/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0395
Epoch 8/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0390
Epoch 9/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0388
Epoch 10/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0384
Epoch 11/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0388
Epoch 12/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0382
Epoch 13/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0382
Epoch 14/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0382
Epoch 15/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0375
Epoch 16/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0374
Epoch 17/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0379
Epoch 18/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0374
Epoch 19/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0374
Epoch 20/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0372
Epoch 21/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0374
Epoch 22/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0374
Epoch 23/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0371
Epoch 24/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0372
Epoch 25/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0371
Epoch 26/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0374
Epoch 27/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0376
Epoch 28/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0372
Epoch 29/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0371
Epoch 30/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0372
Epoch 31/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0374
Epoch 32/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0369
Epoch 33/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0371
Epoch 34/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0374
Epoch 35/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0374
Epoch 36/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0372
Epoch 37/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0370
Epoch 38/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0366
Epoch 39/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0371
Epoch 40/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0370
Epoch 41/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0367
Epoch 42/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0366
Epoch 43/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0361
Epoch 44/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0368
Epoch 45/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0371
Epoch 46/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0366
Epoch 47/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0365
Epoch 48/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0362
Epoch 49/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0367
Epoch 50/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0363
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 408ms/step
Model Number: 1595 with model AverageValueNaive in generation 19 of 25
Model Number: 1596 with model GLS in generation 19 of 25
Model Number: 1597 with model GLS in generation 19 of 25
Model Number: 1598 with model Cassandra in generation 19 of 25
Template Eval Error: KeyError("['changepoint_1', 'changepoint_2'] not in index") in model 1598 in generation 19: Cassandra
Model Number: 1599 with model UnivariateMotif in generation 19 of 25
Model Number: 1600 with model GLS in generation 19 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1601 with model UnivariateMotif in generation 19 of 25
Model Number: 1602 with model ConstantNaive in generation 19 of 25
Model Number: 1603 with model BasicLinearModel in generation 19 of 25
Model Number: 1604 with model LastValueNaive in generation 19 of 25
Model Number: 1605 with model AverageValueNaive in generation 19 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1606 with model BasicLinearModel in generation 19 of 25
Model Number: 1607 with model SeasonalityMotif in generation 19 of 25
Model Number: 1608 with model AverageValueNaive in generation 19 of 25
Model Number: 1609 with model Cassandra in generation 19 of 25
Model Number: 1610 with model FBProphet in generation 19 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1611 with model SeasonalityMotif in generation 19 of 25
Model Number: 1612 with model MetricMotif in generation 19 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 1613 with model Cassandra in generation 19 of 25
Model Number: 1614 with model GLS in generation 19 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1615 with model GLS in generation 19 of 25
Model Number: 1616 with model Cassandra in generation 19 of 25
Model Number: 1617 with model GLS in generation 19 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1618 with model DatepartRegression in generation 19 of 25
Model Number: 1619 with model Cassandra in generation 19 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.633e+00, tolerance: 1.547e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1620 with model GLS in generation 19 of 25
Model Number: 1621 with model SectionalMotif in generation 19 of 25
Template Eval Error: ValueError('kth(=100) out of bounds (67)') in model 1621 in generation 19: SectionalMotif
Model Number: 1622 with model AverageValueNaive in generation 19 of 25
Model Number: 1623 with model ARDL in generation 19 of 25
Model Number: 1624 with model BasicLinearModel in generation 19 of 25
Model Number: 1625 with model BasicLinearModel in generation 19 of 25
Model Number: 1626 with model DatepartRegression in generation 19 of 25
Template Eval Error: InvalidParameterError("The 'alpha' parameter of MLPRegressor must be a float in the range [0, inf). Got None instead.") in model 1626 in generation 19: DatepartRegression
New Generation: 20 of 25
Model Number: 1627 with model ARDL in generation 20 of 25
Model Number: 1628 with model BasicLinearModel in generation 20 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1628 in generation 20: BasicLinearModel
Model Number: 1629 with model GLS in generation 20 of 25
Model Number: 1630 with model FBProphet in generation 20 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1630 in generation 20: FBProphet
Model Number: 1631 with model BasicLinearModel in generation 20 of 25
Model Number: 1632 with model SeasonalityMotif in generation 20 of 25
Model Number: 1633 with model GLS in generation 20 of 25
Model Number: 1634 with model GLS in generation 20 of 25
Model Number: 1635 with model AverageValueNaive in generation 20 of 25
Model Number: 1636 with model LastValueNaive in generation 20 of 25
Model Number: 1637 with model Cassandra in generation 20 of 25
Model Number: 1638 with model DatepartRegression in generation 20 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.503e-02, tolerance: 5.884e-03

Model Number: 1639 with model Cassandra in generation 20 of 25
Model Number: 1640 with model GLS in generation 20 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1641 with model Cassandra in generation 20 of 25
Model Number: 1642 with model ETS in generation 20 of 25
Model Number: 1643 with model LastValueNaive in generation 20 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1644 with model AverageValueNaive in generation 20 of 25
Model Number: 1645 with model GLS in generation 20 of 25
Model Number: 1646 with model ARDL in generation 20 of 25
Model Number: 1647 with model Cassandra in generation 20 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params time {'0': {'fixed': True, 'window': 2, 'macro_micro': False, 'center': False}, '1': {'model': 'Linear', 'changepoint_spacing': 180, 'changepoint_distance_end': 6, 'datepart_method': None}, '2': {'det_order': 0, 'k_ar_diff': 2}} with error ValueError('Coint only works on multivarate series')") in model 1647 in generation 20: Cassandra
Model Number: 1648 with model ARDL in generation 20 of 25
2025-01-30 00:00:00
2025-01-30 00:00:00
2025-01-30 00:00:00
Template Eval Error: ValueError('operands could not be broadcast together with shapes (86,1) (30,1) ') in model 1648 in generation 20: ARDL
Model Number: 1649 with model LastValueNaive in generation 20 of 25
Model Number: 1650 with model Cassandra in generation 20 of 25
Model Number: 1651 with model MetricMotif in generation 20 of 25
Model Number: 1652 with model Cassandra in generation 20 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1653 with model BasicLinearModel in generation 20 of 25
Model Number: 1654 with model GLS in generation 20 of 25
Template Eval Error: ValueError('zero-size array to reduction operation maximum which has no identity') in model 1654 in generation 20: GLS
Model Number: 1655 with model DatepartRegression in generation 20 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1655 in generation 20: DatepartRegression
Model Number: 1656 with model FBProphet in generation 20 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning:

Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1657 with model AverageValueNaive in generation 20 of 25
Model Number: 1658 with model DatepartRegression in generation 20 of 25
Model Number: 1659 with model BasicLinearModel in generation 20 of 25
Model Number: 1660 with model AverageValueNaive in generation 20 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.074e+10, tolerance: 2.439e+06

Model Number: 1661 with model Cassandra in generation 20 of 25
Model Number: 1662 with model Cassandra in generation 20 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1663 with model AverageValueNaive in generation 20 of 25
Model Number: 1664 with model LastValueNaive in generation 20 of 25
Model Number: 1665 with model Cassandra in generation 20 of 25
Template Eval Error: UnboundLocalError("local variable 'slope' referenced before assignment") in model 1665 in generation 20: Cassandra
Model Number: 1666 with model ARDL in generation 20 of 25
Model Number: 1667 with model DatepartRegression in generation 20 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1667 in generation 20: DatepartRegression
Model Number: 1668 with model AverageValueNaive in generation 20 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.52133e-25): result may not be accurate.

New Generation: 21 of 25
Model Number: 1669 with model BasicLinearModel in generation 21 of 25
Model Number: 1670 with model GLS in generation 21 of 25
Model Number: 1671 with model GLS in generation 21 of 25
Model Number: 1672 with model Cassandra in generation 21 of 25
Model Number: 1673 with model ARDL in generation 21 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1674 with model Cassandra in generation 21 of 25
Model Number: 1675 with model GLS in generation 21 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1676 with model LastValueNaive in generation 21 of 25
Model Number: 1677 with model BasicLinearModel in generation 21 of 25
Model Number: 1678 with model Cassandra in generation 21 of 25
Model Number: 1679 with model Cassandra in generation 21 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1680 with model GLS in generation 21 of 25
Model Number: 1681 with model LastValueNaive in generation 21 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params rolling_mean_24 {'0': {'output_distribution': 'uniform', 'n_quantiles': 20}, '1': {'low': 6, 'high': 364, 'K': 1, 'lanczos_factor': False, 'return_diff': True, 'on_transform': True, 'on_inverse': False}, '2': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'mean'}, '3': {'det_order': 0, 'k_ar_diff': 0}, '4': {'lag': 1, 'fill': 'bfill'}} with error ValueError('Coint only works on multivarate series')") in model 1681 in generation 21: LastValueNaive
Model Number: 1682 with model DatepartRegression in generation 21 of 25
Model Number: 1683 with model LastValueNaive in generation 21 of 25
Model Number: 1684 with model AverageValueNaive in generation 21 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.424e+10, tolerance: 3.652e+07

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.252e+10, tolerance: 3.702e+07

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1685 with model DatepartRegression in generation 21 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1685 in generation 21: DatepartRegression
Model Number: 1686 with model DatepartRegression in generation 21 of 25
Model Number: 1687 with model BasicLinearModel in generation 21 of 25
Model Number: 1688 with model ARDL in generation 21 of 25
Model Number: 1689 with model DatepartRegression in generation 21 of 25
Template Eval Error: IndexError('tuple index out of range') in model 1689 in generation 21: DatepartRegression
Model Number: 1690 with model Cassandra in generation 21 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1691 with model AverageValueNaive in generation 21 of 25
Model Number: 1692 with model Cassandra in generation 21 of 25
Model Number: 1693 with model LastValueNaive in generation 21 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1694 with model GLS in generation 21 of 25
Model Number: 1695 with model Cassandra in generation 21 of 25
Model Number: 1696 with model BasicLinearModel in generation 21 of 25
Model Number: 1697 with model ETS in generation 21 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1698 with model AverageValueNaive in generation 21 of 25
Model Number: 1699 with model AverageValueNaive in generation 21 of 25
Model Number: 1700 with model AverageValueNaive in generation 21 of 25
Model Number: 1701 with model GLS in generation 21 of 25
Model Number: 1702 with model Cassandra in generation 21 of 25
Model Number: 1703 with model FBProphet in generation 21 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1704 with model BasicLinearModel in generation 21 of 25
Model Number: 1705 with model BasicLinearModel in generation 21 of 25
Model Number: 1706 with model AverageValueNaive in generation 21 of 25
Model Number: 1707 with model SeasonalityMotif in generation 21 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params rolling_mean {'0': {'det_order': 0, 'k_ar_diff': 2}, '1': {'model': 'Linear', 'changepoint_spacing': 180, 'changepoint_distance_end': 6, 'datepart_method': None}, '2': {}} with error ValueError('Coint only works on multivarate series')") in model 1707 in generation 21: SeasonalityMotif
Model Number: 1708 with model BasicLinearModel in generation 21 of 25
Model Number: 1709 with model GLS in generation 21 of 25
Model Number: 1710 with model LastValueNaive in generation 21 of 25
New Generation: 22 of 25
Model Number: 1711 with model DatepartRegression in generation 22 of 25
Model Number: 1712 with model GLS in generation 22 of 25
Model Number: 1713 with model LastValueNaive in generation 22 of 25
Model Number: 1714 with model AverageValueNaive in generation 22 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params rolling_mean_24 {'0': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}, '1': {'lag_1': 7, 'method': 20}, '2': {}, '3': {'lag_1': 2, 'method': 'LastValue'}} with error ValueError('BTCD only works on multivarate series')") in model 1714 in generation 22: AverageValueNaive
Model Number: 1715 with model AverageValueNaive in generation 22 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params rolling_mean_24 {'0': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}, '1': {'model': 'Linear', 'changepoint_spacing': 180, 'changepoint_distance_end': 6, 'datepart_method': None}, '2': {}} with error ValueError('BTCD only works on multivarate series')") in model 1715 in generation 22: AverageValueNaive
Model Number: 1716 with model Cassandra in generation 22 of 25
Model Number: 1717 with model GLS in generation 22 of 25
Model Number: 1718 with model FBProphet in generation 22 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1719 with model AverageValueNaive in generation 22 of 25
Model Number: 1720 with model ARDL in generation 22 of 25
Model Number: 1721 with model Cassandra in generation 22 of 25
Model Number: 1722 with model BasicLinearModel in generation 22 of 25
Model Number: 1723 with model ETS in generation 22 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1724 with model Cassandra in generation 22 of 25
Model Number: 1725 with model LastValueNaive in generation 22 of 25
Template Eval Error: Exception('Transformer HolidayTransformer failed on fit from params piecewise_polynomial {\'0\': {\'decimals\': 0, \'on_transform\': True, \'on_inverse\': True}, \'1\': {\'threshold\': 0.7, \'splash_threshold\': None, \'use_dayofmonth_holidays\': True, \'use_wkdom_holidays\': True, \'use_wkdeom_holidays\': False, \'use_lunar_holidays\': False, \'use_lunar_weekday\': False, \'use_islamic_holidays\': False, \'use_hebrew_holidays\': False, \'use_hindu_holidays\': False, \'anomaly_detector_params\': {\'method\': \'zscore\', \'method_params\': {\'distribution\': \'norm\', \'alpha\': 0.05}, \'fillna\': \'ffill\', \'transform_dict\': {\'fillna\': \'ffill\', \'transformations\': {\'0\': \'AnomalyRemoval\', \'1\': \'RollingMeanTransformer\'}, \'transformation_params\': {\'0\': {\'method\': \'zscore\', \'method_params\': {\'distribution\': \'gamma\', \'alpha\': 0.05}, \'fillna\': \'linear\', \'transform_dict\': {\'fillna\': \'ffill\', \'transformations\': {\'0\': \'AlignLastValue\', \'1\': \'Round\'}, \'transformation_params\': {\'0\': {\'rows\': 4, \'lag\': 84, \'method\': \'additive\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': None, \'threshold_method\': \'max\'}, \'1\': {\'decimals\': 1, \'on_transform\': True, \'on_inverse\': False}}}, \'isolated_only\': False, \'on_inverse\': False}, \'1\': {\'fixed\': True, \'window\': 12, \'macro_micro\': True, \'center\': True}}}, \'isolated_only\': False, \'on_inverse\': False}, \'remove_excess_anomalies\': True, \'impact\': \'median_value\', \'regression_params\': {}}, \'2\': {}, \'3\': {\'rows\': 1, \'lag\': 1, \'method\': \'additive\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': 1, \'threshold_method\': \'max\'}} with error TypeError("ufunc \'invert\' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule \'\'safe\'\'")') in model 1725 in generation 22: LastValueNaive
Model Number: 1726 with model ARDL in generation 22 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 1726 in generation 22: ARDL
Model Number: 1727 with model BasicLinearModel in generation 22 of 25
Model Number: 1728 with model AverageValueNaive in generation 22 of 25
Model Number: 1729 with model BasicLinearModel in generation 22 of 25
Model Number: 1730 with model LastValueNaive in generation 22 of 25
Model Number: 1731 with model BasicLinearModel in generation 22 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1732 with model ETS in generation 22 of 25
Model Number: 1733 with model BasicLinearModel in generation 22 of 25
Model Number: 1734 with model BasicLinearModel in generation 22 of 25
Model Number: 1735 with model Cassandra in generation 22 of 25
Model Number: 1736 with model Cassandra in generation 22 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1737 with model Cassandra in generation 22 of 25
Model Number: 1738 with model AverageValueNaive in generation 22 of 25
Model Number: 1739 with model AverageValueNaive in generation 22 of 25
Model Number: 1740 with model Cassandra in generation 22 of 25
Model Number: 1741 with model Cassandra in generation 22 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

Model Number: 1742 with model Cassandra in generation 22 of 25
Model Number: 1743 with model DatepartRegression in generation 22 of 25
Template Eval Error: InvalidParameterError("The 'alpha' parameter of MLPRegressor must be a float in the range [0, inf). Got None instead.") in model 1743 in generation 22: DatepartRegression
Model Number: 1744 with model BasicLinearModel in generation 22 of 25
Model Number: 1745 with model BasicLinearModel in generation 22 of 25
Model Number: 1746 with model LastValueNaive in generation 22 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1747 with model BasicLinearModel in generation 22 of 25
Model Number: 1748 with model BasicLinearModel in generation 22 of 25
Model Number: 1749 with model AverageValueNaive in generation 22 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Template Eval Error: ValueError('operands could not be broadcast together with shapes (90,1) (30,1) ') in model 1749 in generation 22: AverageValueNaive
Model Number: 1750 with model GLS in generation 22 of 25
Model Number: 1751 with model LastValueNaive in generation 22 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:2418: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations. Duality gap: 47170799608.81956, tolerance: 75814034.572927

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1752 with model LastValueNaive in generation 22 of 25
New Generation: 23 of 25
Model Number: 1753 with model GLS in generation 23 of 25
2025-01-30 00:00:00
2025-01-30 00:00:00
2025-01-30 00:00:00
Model Number: 1754 with model LastValueNaive in generation 23 of 25
Model Number: 1755 with model DatepartRegression in generation 23 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1755 in generation 23: DatepartRegression
Model Number: 1756 with model MetricMotif in generation 23 of 25
Model Number: 1757 with model GLS in generation 23 of 25
Model Number: 1758 with model BasicLinearModel in generation 23 of 25
Model Number: 1759 with model BasicLinearModel in generation 23 of 25
Model Number: 1760 with model AverageValueNaive in generation 23 of 25
Model Number: 1761 with model AverageValueNaive in generation 23 of 25
Model Number: 1762 with model LastValueNaive in generation 23 of 25
Model Number: 1763 with model GLS in generation 23 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Template Eval Error: ValueError('operands could not be broadcast together with shapes (60,1) (30,1) ') in model 1763 in generation 23: GLS
Model Number: 1764 with model BasicLinearModel in generation 23 of 25
Model Number: 1765 with model AverageValueNaive in generation 23 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params ffill_mean_biased {'0': {}, '1': {'det_order': 0, 'k_ar_diff': 2}, '2': {}, '3': {'method': 'zscore', 'method_params': {'distribution': 'norm', 'alpha': 0.05}, 'fillna': 'ffill', 'transform_dict': None, 'isolated_only': True, 'on_inverse': False}, '4': {'part': 'trend', 'lamb': 129600}} with error ValueError('Coint only works on multivarate series')") in model 1765 in generation 23: AverageValueNaive
Model Number: 1766 with model AverageValueNaive in generation 23 of 25
Model Number: 1767 with model AverageValueNaive in generation 23 of 25
Model Number: 1768 with model LastValueNaive in generation 23 of 25
Model Number: 1769 with model Cassandra in generation 23 of 25
Model Number: 1770 with model BasicLinearModel in generation 23 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1771 with model Cassandra in generation 23 of 25
Model Number: 1772 with model DatepartRegression in generation 23 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1772 in generation 23: DatepartRegression
Model Number: 1773 with model BasicLinearModel in generation 23 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1774 with model FBProphet in generation 23 of 25
Model Number: 1775 with model Cassandra in generation 23 of 25
Model Number: 1776 with model Cassandra in generation 23 of 25
Template Eval Error: Exception('Transformer CenterSplit failed on fit from params rolling_mean_24 {\'0\': {\'fillna\': \'mean\', \'center\': \'zero\'}, \'1\': {\'rows\': 1, \'lag\': 1, \'method\': \'multiplicative\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': 1, \'threshold_method\': \'max\'}, \'2\': {\'fillna\': \'akima\', \'center\': \'median\'}, \'3\': {\'sigma\': 2, \'rolling_window\': 90, \'run_order\': \'season_first\', \'regression_params\': {\'regression_model\': {\'model\': \'ElasticNet\', \'model_params\': {\'l1_ratio\': 0.5, \'fit_intercept\': True, \'selection\': \'cyclic\', \'max_iter\': 1000}}, \'datepart_method\': [\'dayofweek\', 365.25], \'polynomial_degree\': None, \'transform_dict\': {\'fillna\': None, \'transformations\': {\'0\': \'bkfilter\'}, \'transformation_params\': {\'0\': {}}}, \'holiday_countries_used\': False, \'lags\': None, \'forward_lags\': 2}, \'holiday_params\': None, \'trend_method\': \'local_linear\'}, \'4\': {\'model\': \'Linear\', \'changepoint_spacing\': 360, \'changepoint_distance_end\': 5040, \'datepart_method\': None}} with error ValueError("columns overlap but no suffix specified: Index([\'close_lltmicro\'], dtype=\'object\')")') in model 1776 in generation 23: Cassandra
Model Number: 1777 with model SeasonalityMotif in generation 23 of 25
Model Number: 1778 with model DatepartRegression in generation 23 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.246e+10, tolerance: 3.702e+07

Model Number: 1779 with model ARDL in generation 23 of 25
Model Number: 1780 with model Cassandra in generation 23 of 25
Model Number: 1781 with model FBProphet in generation 23 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1782 with model BasicLinearModel in generation 23 of 25
Model Number: 1783 with model ARDL in generation 23 of 25
Template Eval Error: ValueError("ARDL series close failed with error ValueError('The number of regressors (1105) including deterministics, lags of the endog, lags of the exogenous, and fixed regressors is larger than the sample available for estimation (697).') exog train              dp0  dp1        dp2  dp3  dp4  dp5  dp6  dp7  dp8  dp9  ...  \\\ndate                                                                 ...   \n2023-03-01   1.0  0.0  2460004.5  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   \n2023-03-02   2.0  0.0  2460005.5  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   \n2023-03-03   3.0  0.0  2460006.5  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   \n2023-03-04   4.0  1.0  2460007.5  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   \n2023-03-05   5.0  1.0  2460008.5  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...   \n...          ...  ...        ...  ...  ...  ...  ...  ...  ...  ...  ...   \n2025-01-25  25.0  1.0  2460700.5  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-01-26  26.0  1.0  2460701.5  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-01-27  27.0  0.0  2460702.5  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-01-28  28.0  0.0  2460703.5  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-01-29  29.0  0.0  2460704.5  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   \n\n            dp265  dp266  dp267  dp268  dp269  dp270  dp271  dp272  dp273  \\\ndate                                                                        \n2023-03-01    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2023-03-02    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2023-03-03    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0   \n2023-03-04    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0   \n2023-03-05    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n...           ...    ...    ...    ...    ...    ...    ...    ...    ...   \n2025-01-25    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0   \n2025-01-26    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-01-27    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-01-28    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-01-29    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n\n            dp274  \ndate               \n2023-03-01    0.0  \n2023-03-02    0.0  \n2023-03-03    0.0  \n2023-03-04    0.0  \n2023-03-05    1.0  \n...           ...  \n2025-01-25    0.0  \n2025-01-26    1.0  \n2025-01-27    0.0  \n2025-01-28    0.0  \n2025-01-29    0.0  \n\n[701 rows x 275 columns] and predict              dp0  dp1        dp2  dp3  dp4  dp5  dp6  dp7  dp8  dp9  ...  \\\n2025-01-30  30.0  0.0  2460705.5  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-01-31  31.0  0.0  2460706.5  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-01   1.0  1.0  2460707.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-02   2.0  1.0  2460708.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-03   3.0  0.0  2460709.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-04   4.0  0.0  2460710.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-05   5.0  0.0  2460711.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-06   6.0  0.0  2460712.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-07   7.0  0.0  2460713.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-08   8.0  1.0  2460714.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-09   9.0  1.0  2460715.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-10  10.0  0.0  2460716.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-11  11.0  0.0  2460717.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-12  12.0  0.0  2460718.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-13  13.0  0.0  2460719.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-14  14.0  0.0  2460720.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-15  15.0  1.0  2460721.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-16  16.0  1.0  2460722.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-17  17.0  0.0  2460723.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-18  18.0  0.0  2460724.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-19  19.0  0.0  2460725.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-20  20.0  0.0  2460726.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-21  21.0  0.0  2460727.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-22  22.0  1.0  2460728.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-23  23.0  1.0  2460729.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-24  24.0  0.0  2460730.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-25  25.0  0.0  2460731.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-26  26.0  0.0  2460732.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-27  27.0  0.0  2460733.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n2025-02-28  28.0  0.0  2460734.5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...   \n\n            dp265  dp266  dp267  dp268  dp269  dp270  dp271  dp272  dp273  \\\n2025-01-30    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-01-31    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0   \n2025-02-01    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0   \n2025-02-02    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-03    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-04    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-05    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-06    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-07    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0   \n2025-02-08    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0   \n2025-02-09    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-10    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-11    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-12    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-13    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-14    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0   \n2025-02-15    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0   \n2025-02-16    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-17    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-18    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-19    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-20    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-21    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0   \n2025-02-22    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0   \n2025-02-23    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-24    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-25    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-26    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-27    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   \n2025-02-28    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0   \n\n            dp274  \n2025-01-30    0.0  \n2025-01-31    0.0  \n2025-02-01    0.0  \n2025-02-02    1.0  \n2025-02-03    0.0  \n2025-02-04    0.0  \n2025-02-05    0.0  \n2025-02-06    0.0  \n2025-02-07    0.0  \n2025-02-08    0.0  \n2025-02-09    1.0  \n2025-02-10    0.0  \n2025-02-11    0.0  \n2025-02-12    0.0  \n2025-02-13    0.0  \n2025-02-14    0.0  \n2025-02-15    0.0  \n2025-02-16    1.0  \n2025-02-17    0.0  \n2025-02-18    0.0  \n2025-02-19    0.0  \n2025-02-20    0.0  \n2025-02-21    0.0  \n2025-02-22    0.0  \n2025-02-23    1.0  \n2025-02-24    0.0  \n2025-02-25    0.0  \n2025-02-26    0.0  \n2025-02-27    0.0  \n2025-02-28    0.0  \n\n[30 rows x 275 columns]") in model 1783 in generation 23: ARDL
Model Number: 1784 with model GLS in generation 23 of 25
Model Number: 1785 with model AverageValueNaive in generation 23 of 25
Model Number: 1786 with model DatepartRegression in generation 23 of 25
Model Number: 1787 with model Cassandra in generation 23 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.074e+10, tolerance: 2.439e+06

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1788 with model GLS in generation 23 of 25
Model Number: 1789 with model BasicLinearModel in generation 23 of 25
Model Number: 1790 with model BasicLinearModel in generation 23 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params pchip {'0': {'det_order': 1, 'k_ar_diff': 0}, '1': {'fillna': 'ffill', 'center': 'zero'}, '2': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}, '3': {}} with error ValueError('Coint only works on multivarate series')") in model 1790 in generation 23: BasicLinearModel
Model Number: 1791 with model Cassandra in generation 23 of 25
Model Number: 1792 with model Cassandra in generation 23 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1793 with model BasicLinearModel in generation 23 of 25
Model Number: 1794 with model Cassandra in generation 23 of 25
Template Eval Error: ValueError('Model Cassandra returned NaN for one or more series. fail_on_forecast_nan=True') in model 1794 in generation 23: Cassandra
New Generation: 24 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1795 with model DatepartRegression in generation 24 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.439e+07, tolerance: 1.159e+04

Model Number: 1796 with model BasicLinearModel in generation 24 of 25
Model Number: 1797 with model LastValueNaive in generation 24 of 25
Model Number: 1798 with model LastValueNaive in generation 24 of 25

13:37:33 - cmdstanpy - ERROR - Chain [1] error: error during processing Operation not permitted

Model Number: 1799 with model FBProphet in generation 24 of 25
Model Number: 1800 with model GLS in generation 24 of 25
Model Number: 1801 with model AverageValueNaive in generation 24 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1802 with model DatepartRegression in generation 24 of 25
Model Number: 1803 with model BasicLinearModel in generation 24 of 25
Model Number: 1804 with model Cassandra in generation 24 of 25
Template Eval Error: TypeError('Cannot infer number of levels from empty list') in model 1804 in generation 24: Cassandra
Model Number: 1805 with model Cassandra in generation 24 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1806 with model BasicLinearModel in generation 24 of 25
Model Number: 1807 with model Cassandra in generation 24 of 25
Model Number: 1808 with model BasicLinearModel in generation 24 of 25
Model Number: 1809 with model BasicLinearModel in generation 24 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Template Eval Error: ValueError('operands could not be broadcast together with shapes (150,1) (30,1) ') in model 1809 in generation 24: BasicLinearModel
Model Number: 1810 with model Cassandra in generation 24 of 25
Model Number: 1811 with model BasicLinearModel in generation 24 of 25
Model Number: 1812 with model GLS in generation 24 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1813 with model GLS in generation 24 of 25
Model Number: 1814 with model BasicLinearModel in generation 24 of 25
2025-01-30 00:00:00
2025-01-30 00:00:00
2025-01-30 00:00:00
Template Eval Error: ValueError('Model BasicLinearModel returned improper forecast_length. Returned: 26 and requested: 30') in model 1814 in generation 24: BasicLinearModel
Model Number: 1815 with model ARDL in generation 24 of 25
Model Number: 1816 with model Cassandra in generation 24 of 25

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.10/dist-packages/autots/models/cassandra.py:629: RuntimeWarning:

invalid value encountered in greater

Model Number: 1817 with model AverageValueNaive in generation 24 of 25
Model Number: 1818 with model ARDL in generation 24 of 25
Model Number: 1819 with model DatepartRegression in generation 24 of 25
Model Number: 1820 with model LastValueNaive in generation 24 of 25
Model Number: 1821 with model BasicLinearModel in generation 24 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.073e+10, tolerance: 2.434e+06

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1822 with model FBProphet in generation 24 of 25
Model Number: 1823 with model ARDL in generation 24 of 25
Model Number: 1824 with model AverageValueNaive in generation 24 of 25
Model Number: 1825 with model BasicLinearModel in generation 24 of 25
Model Number: 1826 with model Cassandra in generation 24 of 25
Model Number: 1827 with model Cassandra in generation 24 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1828 with model ARDL in generation 24 of 25
Model Number: 1829 with model ARDL in generation 24 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params fake_date {'0': {'constant': 0, 'reintroduction_model': {'model': 'SGD', 'model_params': {}, 'datepart_method': 'simple_2'}, 'fillna': 'ffill'}} with error ValueError('The number of classes has to be greater than one; got 1 class')") in model 1829 in generation 24: ARDL
Model Number: 1830 with model ETS in generation 24 of 25
Model Number: 1831 with model BasicLinearModel in generation 24 of 25
Model Number: 1832 with model GLS in generation 24 of 25

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1833 with model LastValueNaive in generation 24 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params linear {'0': {'model_name': 'local linear hidden state with seasonal 7', 'state_transition': [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]], 'process_noise': [[0.16000000000000003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1e-08, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], 'observation_model': [[1, 1, 0, 0, 0, 0, 0, 0]], 'observation_noise': 0.04, 'em_iter': 10, 'on_transform': True, 'on_inverse': False}, '1': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'base_score': 0.5, 'booster': 'gbtree', 'colsample_bylevel': 0.692, 'learning_rate': 0.022, 'max_bin': 256, 'max_depth': 14, 'max_leaves': 0, 'min_child_weight': 0.024, 'n_estimators': 162}, 'datepart_method': 'simple_binarized'}, 'fillna': None}, '2': {}, '3': {'lag_1': 2, 'method': 'LastValue'}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 1833 in generation 24: LastValueNaive
Model Number: 1834 with model ARDL in generation 24 of 25
Model Number: 1835 with model AverageValueNaive in generation 24 of 25
Model Number: 1836 with model GLS in generation 24 of 25
New Generation: 25 of 25
Model Number: 1837 with model BasicLinearModel in generation 25 of 25
Model Number: 1838 with model AverageValueNaive in generation 25 of 25
Model Number: 1839 with model FBProphet in generation 25 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1839 in generation 25: FBProphet
Model Number: 1840 with model AverageValueNaive in generation 25 of 25
Model Number: 1841 with model ARDL in generation 25 of 25
Model Number: 1842 with model FBProphet in generation 25 of 25

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1842 in generation 25: FBProphet
Model Number: 1843 with model FBProphet in generation 25 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1843 in generation 25: FBProphet
Model Number: 1844 with model GLS in generation 25 of 25
Model Number: 1845 with model ARDL in generation 25 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1846 with model GLS in generation 25 of 25
Model Number: 1847 with model Cassandra in generation 25 of 25
Model Number: 1848 with model GLS in generation 25 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1849 with model DatepartRegression in generation 25 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1849 in generation 25: DatepartRegression
Model Number: 1850 with model LastValueNaive in generation 25 of 25
Model Number: 1851 with model AverageValueNaive in generation 25 of 25
Template Eval Error: Exception('Transformer ChangepointDetrend failed on fit from params zero {\'0\': {\'center\': \'median\'}, \'1\': {\'rows\': 1, \'lag\': 1, \'method\': \'additive\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': None, \'threshold_method\': \'max\'}, \'2\': {\'model\': \'Gamma\', \'changepoint_spacing\': 360, \'changepoint_distance_end\': 60, \'datepart_method\': None}, \'3\': {\'constant\': 1, \'reintroduction_model\': {\'model\': \'xgboost\', \'model_params\': {\'booster\': \'gbtree\', \'max_depth\': 6, \'eta\': 0.003, \'min_child_weight\': 10, \'subsample\': 1, \'colsample_bylevel\': 0.7, \'reg_alpha\': 0, \'reg_lambda\': 0.2}, \'datepart_method\': \'simple_binarized\'}, \'fillna\': \'linear\'}, \'4\': {\'model_name\': \'randomly generated\', \'state_transition\': [[0.0, 0.827744240836561, 0.0], [0.0, -0.9999767701296165, 0.0], [0.0, 0.0, 0.0]], \'process_noise\': [[0.004, 0.0, 0.0], [0.0, 0.012, 0.0], [0.0, 0.0, 0.005]], \'observation_model\': [[-1.1788115862637654, -1.0502683055727, -0.801274348223473]], \'observation_noise\': 1.1357703017994603, \'em_iter\': 30, \'on_transform\': True, \'on_inverse\': False}} with error ValueError("Some value(s) of y are out of the valid range of the loss \'HalfGammaLoss\'.")') in model 1851 in generation 25: AverageValueNaive
Model Number: 1852 with model BasicLinearModel in generation 25 of 25
Model Number: 1853 with model LastValueNaive in generation 25 of 25
Model Number: 1854 with model Cassandra in generation 25 of 25
Model Number: 1855 with model LastValueNaive in generation 25 of 25
Model Number: 1856 with model ETS in generation 25 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1857 with model ARDL in generation 25 of 25
Model Number: 1858 with model AverageValueNaive in generation 25 of 25
Model Number: 1859 with model ARDL in generation 25 of 25
Model Number: 1860 with model LastValueNaive in generation 25 of 25
Model Number: 1861 with model Cassandra in generation 25 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 1862 with model ARDL in generation 25 of 25
Model Number: 1863 with model Cassandra in generation 25 of 25
Model Number: 1864 with model LastValueNaive in generation 25 of 25
Model Number: 1865 with model UnivariateMotif in generation 25 of 25

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Template Eval Error: ValueError('operands could not be broadcast together with shapes (150,1) (30,1) ') in model 1865 in generation 25: UnivariateMotif
Model Number: 1866 with model ARDL in generation 25 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 1866 in generation 25: ARDL
Model Number: 1867 with model BasicLinearModel in generation 25 of 25
Model Number: 1868 with model AverageValueNaive in generation 25 of 25
Model Number: 1869 with model ARDL in generation 25 of 25
Model Number: 1870 with model ARDL in generation 25 of 25
Model Number: 1871 with model AverageValueNaive in generation 25 of 25
Template Eval Error: ValueError('operands could not be broadcast together with shapes (90,1) (30,1) ') in model 1871 in generation 25: AverageValueNaive
Model Number: 1872 with model LastValueNaive in generation 25 of 25
Model Number: 1873 with model Cassandra in generation 25 of 25
Model Number: 1874 with model BasicLinearModel in generation 25 of 25
Template Eval Error: Exception('Transformer PCA failed on fit from params zero {\'0\': {\'rows\': 1, \'lag\': 7, \'method\': \'multiplicative\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': 10, \'threshold_method\': \'mean\'}, \'1\': {\'model\': \'Linear\', \'changepoint_spacing\': 180, \'changepoint_distance_end\': 6, \'datepart_method\': None}, \'2\': {\'whiten\': False, \'n_components\': 10}, \'3\': {\'rows\': 168, \'lag\': 1, \'method\': \'additive\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': 1, \'threshold_method\': \'max\'}, \'4\': {\'rows\': 1, \'lag\': 1, \'method\': \'additive\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': 10, \'threshold_method\': \'max\'}} with error ValueError("n_components=10 must be between 0 and min(n_samples, n_features)=1 with svd_solver=\'full\'")') in model 1874 in generation 25: BasicLinearModel
Model Number: 1875 with model ARDL in generation 25 of 25
Model Number: 1876 with model BasicLinearModel in generation 25 of 25

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1877 with model ARDL in generation 25 of 25
Model Number: 1878 with model AverageValueNaive in generation 25 of 25
Model Number: 1879 with model Ensemble in generation 26 of Ensembles

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1893 with model Ensemble in generation 26 of Ensembles

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1907 with model Ensemble in generation 26 of Ensembles

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1921 with model Ensemble in generation 26 of Ensembles

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1935 with model Ensemble in generation 26 of Ensembles

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1949 with model Ensemble in generation 26 of Ensembles

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1963 with model Ensemble in generation 26 of Ensembles

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1977 with model Ensemble in generation 26 of Ensembles

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 1991 with model Ensemble in generation 26 of Ensembles

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Validation Round: 1
Model Number: 1 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

📈 1 - Ensemble with avg smape 23.76:
2 - Ensemble with avg smape 23.78:
3 - Ensemble with avg smape 24.03:
📈 4 - Ensemble with avg smape 23.67:
📈 5 - Ensemble with avg smape 8.15:
6 - Ensemble with avg smape 117.49:
📈 7 - Ensemble with avg smape 8.01:
8 - Ensemble with avg smape 24.01:
9 - Ensemble with avg smape 23.76:
📈 10 - Ensemble with avg smape 7.51:
11 - Ensemble with avg smape 21.01:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

12 - Ensemble with avg smape 24.23:
13 - Ensemble with avg smape 12.66:
14 - Ensemble with avg smape 15.01:
Model Number: 15 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

15 - Ensemble with avg smape 23.76:
16 - Ensemble with avg smape 23.78:
17 - Ensemble with avg smape 24.03:
18 - Ensemble with avg smape 23.67:
19 - Ensemble with avg smape 8.15:
20 - Ensemble with avg smape 117.49:
21 - Ensemble with avg smape 8.01:
22 - Ensemble with avg smape 24.01:
23 - Ensemble with avg smape 23.76:
24 - Ensemble with avg smape 7.51:
25 - Ensemble with avg smape 21.01:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

26 - Ensemble with avg smape 24.23:
27 - Ensemble with avg smape 12.66:
28 - Ensemble with avg smape 15.01:
Model Number: 29 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

29 - Ensemble with avg smape 23.76:
30 - Ensemble with avg smape 23.78:
31 - Ensemble with avg smape 24.03:
32 - Ensemble with avg smape 23.67:
33 - Ensemble with avg smape 8.15:
34 - Ensemble with avg smape 117.49:
35 - Ensemble with avg smape 8.01:
36 - Ensemble with avg smape 24.01:
37 - Ensemble with avg smape 23.76:
38 - Ensemble with avg smape 7.51:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

39 - Ensemble with avg smape 21.01:
40 - Ensemble with avg smape 24.23:
41 - Ensemble with avg smape 12.66:
42 - Ensemble with avg smape 15.01:
Model Number: 43 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

43 - Ensemble with avg smape 23.76:
44 - Ensemble with avg smape 23.78:
45 - Ensemble with avg smape 24.03:
46 - Ensemble with avg smape 23.67:
47 - Ensemble with avg smape 8.15:
48 - Ensemble with avg smape 117.49:
49 - Ensemble with avg smape 8.01:
50 - Ensemble with avg smape 24.01:
51 - Ensemble with avg smape 23.76:
52 - Ensemble with avg smape 7.51:
53 - Ensemble with avg smape 21.01:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

54 - Ensemble with avg smape 24.23:
55 - Ensemble with avg smape 12.66:
56 - Ensemble with avg smape 15.01:
Model Number: 57 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

57 - Ensemble with avg smape 23.76:
58 - Ensemble with avg smape 23.78:
59 - Ensemble with avg smape 24.03:
60 - Ensemble with avg smape 23.67:
61 - Ensemble with avg smape 8.15:
62 - Ensemble with avg smape 117.49:
63 - Ensemble with avg smape 8.01:
64 - Ensemble with avg smape 24.01:
65 - Ensemble with avg smape 23.76:
66 - Ensemble with avg smape 7.51:
67 - Ensemble with avg smape 21.01:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

68 - Ensemble with avg smape 24.23:
69 - Ensemble with avg smape 12.66:
70 - Ensemble with avg smape 15.01:
Model Number: 71 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

71 - Ensemble with avg smape 18.8:
72 - Ensemble with avg smape 18.79:
73 - Ensemble with avg smape 20.01:
74 - Ensemble with avg smape 18.78:
75 - Ensemble with avg smape 7.55:
76 - Ensemble with avg smape 117.49:
77 - Ensemble with avg smape 9.24:
78 - Ensemble with avg smape 18.39:
79 - Ensemble with avg smape 18.8:
80 - Ensemble with avg smape 7.55:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

81 - Ensemble with avg smape 16.86:
82 - Ensemble with avg smape 19.23:
83 - Ensemble with avg smape 9.77:
84 - Ensemble with avg smape 13.07:
Model Number: 85 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

85 - Ensemble with avg smape 18.8:
86 - Ensemble with avg smape 18.79:
87 - Ensemble with avg smape 20.01:
88 - Ensemble with avg smape 18.78:
89 - Ensemble with avg smape 7.55:
90 - Ensemble with avg smape 117.49:
91 - Ensemble with avg smape 9.24:
92 - Ensemble with avg smape 18.39:
93 - Ensemble with avg smape 18.8:
94 - Ensemble with avg smape 7.55:
95 - Ensemble with avg smape 16.86:
96 - Ensemble with avg smape 19.23:
97 - Ensemble with avg smape 9.77:
98 - Ensemble with avg smape 13.07:
Model Number: 99 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

99 - Ensemble with avg smape 18.8:
100 - Ensemble with avg smape 18.79:
101 - Ensemble with avg smape 20.01:
102 - Ensemble with avg smape 18.78:
103 - Ensemble with avg smape 7.55:
104 - Ensemble with avg smape 117.49:
105 - Ensemble with avg smape 9.24:
106 - Ensemble with avg smape 18.39:
107 - Ensemble with avg smape 18.8:
108 - Ensemble with avg smape 7.55:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

109 - Ensemble with avg smape 16.86:
110 - Ensemble with avg smape 19.23:
111 - Ensemble with avg smape 9.77:
112 - Ensemble with avg smape 13.07:
Model Number: 113 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

113 - Ensemble with avg smape 8.31:
114 - Ensemble with avg smape 8.13:
115 - Ensemble with avg smape 14.63:
116 - Ensemble with avg smape 7.91:
📈 117 - Ensemble with avg smape 6.69:
118 - Ensemble with avg smape 117.49:
119 - Ensemble with avg smape 14.03:
120 - Ensemble with avg smape 7.87:
121 - Ensemble with avg smape 8.31:
122 - Ensemble with avg smape 7.33:
123 - Ensemble with avg smape 11.1:
124 - Ensemble with avg smape 8.7:
📈 125 - Ensemble with avg smape 6.48:
126 - Ensemble with avg smape 10.36:
Model Number: 127 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

127 - Ensemble with avg smape 8.44:
128 - Ensemble with avg smape 8.26:
129 - Ensemble with avg smape 14.62:
130 - Ensemble with avg smape 8.06:
131 - Ensemble with avg smape 6.69:
132 - Ensemble with avg smape 117.49:
133 - Ensemble with avg smape 14.03:
134 - Ensemble with avg smape 8.01:
135 - Ensemble with avg smape 8.44:
136 - Ensemble with avg smape 7.38:
137 - Ensemble with avg smape 11.1:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

138 - Ensemble with avg smape 8.83:
139 - Ensemble with avg smape 6.48:
140 - Ensemble with avg smape 10.36:
Model Number: 141 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

141 - Ensemble with avg smape 10.23:
142 - Ensemble with avg smape 10.16:
143 - Ensemble with avg smape 13.33:
144 - Ensemble with avg smape 10.05:
145 - Ensemble with avg smape 6.55:
146 - Ensemble with avg smape 117.49:
147 - Ensemble with avg smape 11.29:
148 - Ensemble with avg smape 9.78:
149 - Ensemble with avg smape 10.23:
150 - Ensemble with avg smape 7.59:
151 - Ensemble with avg smape 10.1:
152 - Ensemble with avg smape 10.64:
153 - Ensemble with avg smape 6.55:
154 - Ensemble with avg smape 9.77:
Model Number: 155 of 301 with model Cassandra for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

155 - Cassandra with avg smape 19.14:
Model Number: 156 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

156 - Ensemble with avg smape 19.13:
157 - Ensemble with avg smape 19.12:
158 - Ensemble with avg smape 20.32:
159 - Ensemble with avg smape 19.12:
160 - Ensemble with avg smape 7.59:
161 - Ensemble with avg smape 117.49:
162 - Ensemble with avg smape 9.24:
163 - Ensemble with avg smape 18.83:
164 - Ensemble with avg smape 19.13:
165 - Ensemble with avg smape 7.55:
166 - Ensemble with avg smape 17.17:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

167 - Ensemble with avg smape 19.56:
168 - Ensemble with avg smape 9.98:
169 - Ensemble with avg smape 13.22:
Model Number: 170 of 301 with model Cassandra for Validation 1
170 - Cassandra with avg smape 25.15:
Model Number: 171 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

171 - Ensemble with avg smape 19.13:
172 - Ensemble with avg smape 19.12:
173 - Ensemble with avg smape 20.32:
174 - Ensemble with avg smape 19.12:
175 - Ensemble with avg smape 7.59:
176 - Ensemble with avg smape 117.49:
177 - Ensemble with avg smape 9.24:
178 - Ensemble with avg smape 18.83:
179 - Ensemble with avg smape 19.13:
180 - Ensemble with avg smape 7.55:
181 - Ensemble with avg smape 17.17:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

182 - Ensemble with avg smape 19.56:
183 - Ensemble with avg smape 9.98:
184 - Ensemble with avg smape 13.22:
Model Number: 185 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

185 - Ensemble with avg smape 19.13:
186 - Ensemble with avg smape 19.12:
187 - Ensemble with avg smape 20.32:
188 - Ensemble with avg smape 19.12:
189 - Ensemble with avg smape 7.59:
190 - Ensemble with avg smape 117.49:
191 - Ensemble with avg smape 9.24:
192 - Ensemble with avg smape 18.83:
193 - Ensemble with avg smape 19.13:
194 - Ensemble with avg smape 7.55:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

195 - Ensemble with avg smape 17.17:
196 - Ensemble with avg smape 19.56:
197 - Ensemble with avg smape 9.98:
198 - Ensemble with avg smape 13.22:
Model Number: 199 of 301 with model Cassandra for Validation 1
199 - Cassandra with avg smape 12.68:
Model Number: 200 of 301 with model Cassandra for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

200 - Cassandra with avg smape 12.68:
Model Number: 201 of 301 with model Cassandra for Validation 1
201 - Cassandra with avg smape 25.22:
Model Number: 202 of 301 with model Cassandra for Validation 1

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

202 - Cassandra with avg smape 25.22:
Model Number: 203 of 301 with model Cassandra for Validation 1
203 - Cassandra with avg smape 25.22:
Model Number: 204 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

204 - Ensemble with avg smape 10.23:
205 - Ensemble with avg smape 10.16:
206 - Ensemble with avg smape 13.33:
207 - Ensemble with avg smape 10.05:
208 - Ensemble with avg smape 6.55:
209 - Ensemble with avg smape 117.49:
210 - Ensemble with avg smape 11.29:
211 - Ensemble with avg smape 9.78:
212 - Ensemble with avg smape 10.23:
213 - Ensemble with avg smape 7.59:
214 - Ensemble with avg smape 10.1:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

215 - Ensemble with avg smape 10.64:
216 - Ensemble with avg smape 6.55:
217 - Ensemble with avg smape 9.77:
Model Number: 218 of 301 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

218 - Ensemble with avg smape 10.23:
219 - Ensemble with avg smape 10.16:
220 - Ensemble with avg smape 13.33:
221 - Ensemble with avg smape 10.05:
222 - Ensemble with avg smape 6.55:
223 - Ensemble with avg smape 117.49:
224 - Ensemble with avg smape 11.29:
225 - Ensemble with avg smape 9.78:
226 - Ensemble with avg smape 10.23:
227 - Ensemble with avg smape 7.59:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

228 - Ensemble with avg smape 10.1:
229 - Ensemble with avg smape 10.64:
230 - Ensemble with avg smape 6.55:
231 - Ensemble with avg smape 9.77:
Model Number: 232 of 301 with model Cassandra for Validation 1
232 - Cassandra with avg smape 25.22:
Model Number: 233 of 301 with model Cassandra for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

233 - Cassandra with avg smape 25.22:
Model Number: 234 of 301 with model Cassandra for Validation 1
234 - Cassandra with avg smape 25.22:
Model Number: 235 of 301 with model Cassandra for Validation 1

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

235 - Cassandra with avg smape 25.22:
Model Number: 236 of 301 with model Cassandra for Validation 1
236 - Cassandra with avg smape 25.15:
Model Number: 237 of 301 with model Cassandra for Validation 1

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

237 - Cassandra with avg smape 25.15:
Model Number: 238 of 301 with model Cassandra for Validation 1
238 - Cassandra with avg smape 24.38:
Model Number: 239 of 301 with model Cassandra for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

239 - Cassandra with avg smape 24.32:
Model Number: 240 of 301 with model Cassandra for Validation 1
240 - Cassandra with avg smape 24.32:
Model Number: 241 of 301 with model FBProphet for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

📈 241 - FBProphet with avg smape 5.29:
Model Number: 242 of 301 with model AverageValueNaive for Validation 1
242 - AverageValueNaive with avg smape 18.42:
Model Number: 243 of 301 with model AverageValueNaive for Validation 1
243 - AverageValueNaive with avg smape 18.42:
Model Number: 244 of 301 with model AverageValueNaive for Validation 1
244 - AverageValueNaive with avg smape 18.43:
Model Number: 245 of 301 with model BasicLinearModel for Validation 1
245 - BasicLinearModel with avg smape 12.03:
Model Number: 246 of 301 with model AverageValueNaive for Validation 1

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

246 - AverageValueNaive with avg smape 18.44:
Model Number: 247 of 301 with model BasicLinearModel for Validation 1
247 - BasicLinearModel with avg smape 16.69:
Model Number: 248 of 301 with model AverageValueNaive for Validation 1
248 - AverageValueNaive with avg smape 18.44:
Model Number: 249 of 301 with model BasicLinearModel for Validation 1
249 - BasicLinearModel with avg smape 16.55:
Model Number: 250 of 301 with model BasicLinearModel for Validation 1
250 - BasicLinearModel with avg smape 16.55:
Model Number: 251 of 301 with model ARDL for Validation 1
251 - ARDL with avg smape 20.37:
Model Number: 252 of 301 with model ARDL for Validation 1
252 - ARDL with avg smape 20.37:
Model Number: 253 of 301 with model BasicLinearModel for Validation 1
253 - BasicLinearModel with avg smape 28.5:
Model Number: 254 of 301 with model BasicLinearModel for Validation 1
254 - BasicLinearModel with avg smape 21.87:
Model Number: 255 of 301 with model ARDL for Validation 1
255 - ARDL with avg smape 20.05:
Model Number: 256 of 301 with model ARDL for Validation 1
256 - ARDL with avg smape 19.92:
Model Number: 257 of 301 with model ARDL for Validation 1
257 - ARDL with avg smape 19.77:
Model Number: 258 of 301 with model ARDL for Validation 1
258 - ARDL with avg smape 20.33:
Model Number: 259 of 301 with model GLS for Validation 1
259 - GLS with avg smape 18.42:
Model Number: 260 of 301 with model GLS for Validation 1
260 - GLS with avg smape 18.42:
Model Number: 261 of 301 with model GLS for Validation 1
261 - GLS with avg smape 18.42:
Model Number: 262 of 301 with model GLS for Validation 1
262 - GLS with avg smape 18.42:
Model Number: 263 of 301 with model GLS for Validation 1
263 - GLS with avg smape 18.42:
Model Number: 264 of 301 with model GLS for Validation 1
264 - GLS with avg smape 18.42:
Model Number: 265 of 301 with model GLS for Validation 1
265 - GLS with avg smape 18.42:
Model Number: 266 of 301 with model BasicLinearModel for Validation 1
266 - BasicLinearModel with avg smape 16.14:
Model Number: 267 of 301 with model BasicLinearModel for Validation 1
267 - BasicLinearModel with avg smape 20.21:
Model Number: 268 of 301 with model ETS for Validation 1
268 - ETS with avg smape 18.76:
Model Number: 269 of 301 with model ETS for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

269 - ETS with avg smape 18.76:
Model Number: 270 of 301 with model GLS for Validation 1
270 - GLS with avg smape 18.41:
Model Number: 271 of 301 with model GLS for Validation 1
271 - GLS with avg smape 18.41:
Model Number: 272 of 301 with model GLS for Validation 1
272 - GLS with avg smape 18.41:
Model Number: 273 of 301 with model GLS for Validation 1
273 - GLS with avg smape 18.41:
Model Number: 274 of 301 with model ARDL for Validation 1
274 - ARDL with avg smape 28.31:
Model Number: 275 of 301 with model AverageValueNaive for Validation 1
275 - AverageValueNaive with avg smape 18.23:
Model Number: 276 of 301 with model GLS for Validation 1
276 - GLS with avg smape 20.55:
Model Number: 277 of 301 with model GLS for Validation 1

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

277 - GLS with avg smape 20.55:
Model Number: 278 of 301 with model GLS for Validation 1
278 - GLS with avg smape 20.53:
Model Number: 279 of 301 with model GLS for Validation 1
279 - GLS with avg smape 20.55:
Model Number: 280 of 301 with model GLS for Validation 1
280 - GLS with avg smape 20.55:
Model Number: 281 of 301 with model BasicLinearModel for Validation 1
281 - BasicLinearModel with avg smape 11.24:
Model Number: 282 of 301 with model AverageValueNaive for Validation 1
282 - AverageValueNaive with avg smape 18.3:
Model Number: 283 of 301 with model AverageValueNaive for Validation 1
283 - AverageValueNaive with avg smape 18.42:
Model Number: 284 of 301 with model AverageValueNaive for Validation 1
284 - AverageValueNaive with avg smape 18.42:
Model Number: 285 of 301 with model AverageValueNaive for Validation 1
285 - AverageValueNaive with avg smape 18.43:
Model Number: 286 of 301 with model AverageValueNaive for Validation 1
286 - AverageValueNaive with avg smape 18.43:
Model Number: 287 of 301 with model AverageValueNaive for Validation 1
287 - AverageValueNaive with avg smape 18.42:
Model Number: 288 of 301 with model AverageValueNaive for Validation 1
288 - AverageValueNaive with avg smape 18.44:
Model Number: 289 of 301 with model AverageValueNaive for Validation 1
289 - AverageValueNaive with avg smape 18.44:
Model Number: 290 of 301 with model AverageValueNaive for Validation 1
290 - AverageValueNaive with avg smape 14.92:
Model Number: 291 of 301 with model BasicLinearModel for Validation 1
291 - BasicLinearModel with avg smape 26.4:
Model Number: 292 of 301 with model AverageValueNaive for Validation 1
292 - AverageValueNaive with avg smape 18.42:
Model Number: 293 of 301 with model DatepartRegression for Validation 1
📈 293 - DatepartRegression with avg smape 3.87:
Model Number: 294 of 301 with model LastValueNaive for Validation 1
294 - LastValueNaive with avg smape 18.76:
Model Number: 295 of 301 with model LastValueNaive for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.344e+00, tolerance: 1.569e-02

295 - LastValueNaive with avg smape 18.76:
Model Number: 296 of 301 with model LastValueNaive for Validation 1
296 - LastValueNaive with avg smape 18.76:
Model Number: 297 of 301 with model LastValueNaive for Validation 1
297 - LastValueNaive with avg smape 18.76:
Model Number: 298 of 301 with model LastValueNaive for Validation 1
298 - LastValueNaive with avg smape 18.76:
Model Number: 299 of 301 with model LastValueNaive for Validation 1
299 - LastValueNaive with avg smape 18.76:
Model Number: 300 of 301 with model LastValueNaive for Validation 1
300 - LastValueNaive with avg smape 18.76:
Model Number: 301 of 301 with model LastValueNaive for Validation 1
301 - LastValueNaive with avg smape 18.76:
Model Number: 302 of 301 with model LastValueNaive for Validation 1
302 - LastValueNaive with avg smape 18.76:
Model Number: 303 of 301 with model ARDL for Validation 1
303 - ARDL with avg smape 21.7:
Model Number: 304 of 301 with model LastValueNaive for Validation 1
304 - LastValueNaive with avg smape 18.62:
Model Number: 305 of 301 with model LastValueNaive for Validation 1
305 - LastValueNaive with avg smape 18.62:
Model Number: 306 of 301 with model LastValueNaive for Validation 1
306 - LastValueNaive with avg smape 18.62:
Model Number: 307 of 301 with model BasicLinearModel for Validation 1
307 - BasicLinearModel with avg smape 8.0:
Model Number: 308 of 301 with model BasicLinearModel for Validation 1
308 - BasicLinearModel with avg smape 8.6:
Model Number: 309 of 301 with model BasicLinearModel for Validation 1
309 - BasicLinearModel with avg smape 31.89:
Model Number: 310 of 301 with model BasicLinearModel for Validation 1
310 - BasicLinearModel with avg smape 21.66:
Model Number: 311 of 301 with model DatepartRegression for Validation 1
311 - DatepartRegression with avg smape 22.3:
Model Number: 312 of 301 with model BasicLinearModel for Validation 1
312 - BasicLinearModel with avg smape 7.83:
Model Number: 313 of 301 with model BasicLinearModel for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.038e+10, tolerance: 2.405e+06

313 - BasicLinearModel with avg smape 8.6:
Model Number: 314 of 301 with model DatepartRegression for Validation 1
314 - DatepartRegression with avg smape 18.15:
Model Number: 315 of 301 with model DatepartRegression for Validation 1
315 - DatepartRegression with avg smape 22.29:
Model Number: 316 of 301 with model DatepartRegression for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.040e+10, tolerance: 2.414e+06

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.040e+10, tolerance: 2.414e+06

316 - DatepartRegression with avg smape 22.29:
Model Number: 317 of 301 with model LastValueNaive for Validation 1
317 - LastValueNaive with avg smape 13.07:
Model Number: 318 of 301 with model ARDL for Validation 1
318 - ARDL with avg smape 26.63:
Model Number: 319 of 301 with model DatepartRegression for Validation 1
319 - DatepartRegression with avg smape 20.47:
Model Number: 320 of 301 with model DatepartRegression for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.399e+00, tolerance: 1.223e-02

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.727e+00, tolerance: 1.218e-02

320 - DatepartRegression with avg smape 20.48:
Model Number: 321 of 301 with model DatepartRegression for Validation 1
321 - DatepartRegression with avg smape 20.48:
Model Number: 322 of 301 with model DatepartRegression for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.727e+00, tolerance: 1.218e-02

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.497e+09, tolerance: 2.207e+06

322 - DatepartRegression with avg smape 22.29:
Model Number: 323 of 301 with model ETS for Validation 1
323 - ETS with avg smape 13.25:
Model Number: 324 of 301 with model ETS for Validation 1
324 - ETS with avg smape 13.25:
Model Number: 325 of 301 with model ARDL for Validation 1
325 - ARDL with avg smape 28.03:
Model Number: 326 of 301 with model DatepartRegression for Validation 1
326 - DatepartRegression with avg smape 22.28:
Model Number: 327 of 301 with model DatepartRegression for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.517e+09, tolerance: 2.212e+06

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.831e+00, tolerance: 1.219e-02

327 - DatepartRegression with avg smape 20.47:
Model Number: 328 of 301 with model UnivariateMotif for Validation 1
328 - UnivariateMotif with avg smape 9.5:
Model Number: 329 of 301 with model LastValueNaive for Validation 1
329 - LastValueNaive with avg smape 18.48:
Model Number: 330 of 301 with model LastValueNaive for Validation 1
330 - LastValueNaive with avg smape 18.48:
Model Number: 331 of 301 with model LastValueNaive for Validation 1
331 - LastValueNaive with avg smape 18.48:
Model Number: 332 of 301 with model DatepartRegression for Validation 1
Epoch 1/50

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

42/42 ━━━━━━━━━━━━━━━━━━━━ 5s 23ms/step - loss: 0.0558
Epoch 2/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0558
Epoch 3/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0558
Epoch 4/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0558
Epoch 5/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0558
Epoch 6/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0527
Epoch 7/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0367
Epoch 8/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0359
Epoch 9/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0354
Epoch 10/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0348
Epoch 11/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0354
Epoch 12/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0351
Epoch 13/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0352
Epoch 14/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0350
Epoch 15/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0348
Epoch 16/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0351
Epoch 17/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0355
Epoch 18/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0350
Epoch 19/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0350
Epoch 20/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0351
Epoch 21/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0350
Epoch 22/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0350
Epoch 23/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0351
Epoch 24/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0349
Epoch 25/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0347
Epoch 26/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0349
Epoch 27/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0352
Epoch 28/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0349
Epoch 29/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0354
Epoch 30/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0349
Epoch 31/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0349
Epoch 32/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0350
Epoch 33/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0348
Epoch 34/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0346
Epoch 35/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0345
Epoch 36/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0344
Epoch 37/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0346
Epoch 38/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0346
Epoch 39/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0345
Epoch 40/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0343
Epoch 41/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0341
Epoch 42/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0345
Epoch 43/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0341
Epoch 44/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0345
Epoch 45/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0340
Epoch 46/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0339
Epoch 47/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0340
Epoch 48/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0339
Epoch 49/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0336
Epoch 50/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0333
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 411ms/step
332 - DatepartRegression with avg smape 22.11:
Model Number: 333 of 301 with model SeasonalityMotif for Validation 1
333 - SeasonalityMotif with avg smape 15.77:
Model Number: 334 of 301 with model DatepartRegression for Validation 1
334 - DatepartRegression with avg smape 16.63:
Model Number: 335 of 301 with model ARDL for Validation 1
335 - ARDL with avg smape 11.5:
Model Number: 336 of 301 with model FBProphet for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

336 - FBProphet with avg smape 7.59:
Model Number: 337 of 301 with model ARDL for Validation 1
337 - ARDL with avg smape 20.21:
Model Number: 338 of 301 with model MetricMotif for Validation 1
338 - MetricMotif with avg smape 4.42:
Model Number: 339 of 301 with model MetricMotif for Validation 1
339 - MetricMotif with avg smape 4.42:
Model Number: 340 of 301 with model MetricMotif for Validation 1
340 - MetricMotif with avg smape 4.42:
Model Number: 341 of 301 with model MetricMotif for Validation 1
341 - MetricMotif with avg smape 4.42:
Model Number: 342 of 301 with model UnivariateMotif for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

342 - UnivariateMotif with avg smape 15.5:
Model Number: 343 of 301 with model ETS for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

343 - ETS with avg smape 20.5:
Model Number: 344 of 301 with model MetricMotif for Validation 1
344 - MetricMotif with avg smape 14.69:
Model Number: 345 of 301 with model ETS for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

345 - ETS with avg smape 20.38:
Model Number: 346 of 301 with model ARDL for Validation 1
346 - ARDL with avg smape 20.52:
Model Number: 347 of 301 with model MetricMotif for Validation 1
347 - MetricMotif with avg smape 14.97:
Model Number: 348 of 301 with model MetricMotif for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

348 - MetricMotif with avg smape 4.51:
Model Number: 349 of 301 with model UnivariateMotif for Validation 1
349 - UnivariateMotif with avg smape 15.67:
Model Number: 350 of 301 with model MetricMotif for Validation 1
350 - MetricMotif with avg smape 17.98:
Model Number: 351 of 301 with model FBProphet for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

351 - FBProphet with avg smape 6.58:
Model Number: 352 of 301 with model SectionalMotif for Validation 1
📈 352 - SectionalMotif with avg smape 3.81:
Model Number: 353 of 301 with model MetricMotif for Validation 1
353 - MetricMotif with avg smape 4.65:
Model Number: 354 of 301 with model MetricMotif for Validation 1
354 - MetricMotif with avg smape 4.65:
Model Number: 355 of 301 with model ETS for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

355 - ETS with avg smape 19.36:
Model Number: 356 of 301 with model ConstantNaive for Validation 1
356 - ConstantNaive with avg smape 18.42:
Model Number: 357 of 301 with model ConstantNaive for Validation 1
357 - ConstantNaive with avg smape 18.42:
Model Number: 358 of 301 with model SectionalMotif for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.084e+10, tolerance: 2.499e+06

📈 358 - SectionalMotif with avg smape 3.77:
Model Number: 359 of 301 with model DatepartRegression for Validation 1
359 - DatepartRegression with avg smape 22.12:
Model Number: 360 of 301 with model SectionalMotif for Validation 1
360 - SectionalMotif with avg smape 7.11:
Model Number: 361 of 301 with model SectionalMotif for Validation 1
361 - SectionalMotif with avg smape 8.49:
Model Number: 362 of 301 with model MetricMotif for Validation 1
362 - MetricMotif with avg smape 4.73:
Model Number: 363 of 301 with model SectionalMotif for Validation 1
363 - SectionalMotif with avg smape 30.59:
Model Number: 364 of 301 with model MetricMotif for Validation 1
364 - MetricMotif with avg smape 16.83:
Model Number: 365 of 301 with model MetricMotif for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

365 - MetricMotif with avg smape 24.45:
Model Number: 366 of 301 with model UnivariateMotif for Validation 1
📈 366 - UnivariateMotif with avg smape 3.05:
Model Number: 367 of 301 with model SectionalMotif for Validation 1
367 - SectionalMotif with avg smape 4.84:
Model Number: 368 of 301 with model ARDL for Validation 1
368 - ARDL with avg smape 20.63:
Model Number: 369 of 301 with model MetricMotif for Validation 1
369 - MetricMotif with avg smape 5.39:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 370 of 301 with model MetricMotif for Validation 1
370 - MetricMotif with avg smape 5.39:
Model Number: 371 of 301 with model MetricMotif for Validation 1
371 - MetricMotif with avg smape 5.39:
Model Number: 372 of 301 with model SectionalMotif for Validation 1
372 - SectionalMotif with avg smape 4.36:
Model Number: 373 of 301 with model UnivariateMotif for Validation 1
373 - UnivariateMotif with avg smape 3.43:
Model Number: 374 of 301 with model UnivariateMotif for Validation 1
374 - UnivariateMotif with avg smape 3.7:
Model Number: 375 of 301 with model UnivariateMotif for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

375 - UnivariateMotif with avg smape 3.7:
Model Number: 376 of 301 with model UnivariateMotif for Validation 1
376 - UnivariateMotif with avg smape 3.7:
Model Number: 377 of 301 with model UnivariateMotif for Validation 1
377 - UnivariateMotif with avg smape 3.7:
Model Number: 378 of 301 with model SectionalMotif for Validation 1
378 - SectionalMotif with avg smape 3.5:

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 379 of 301 with model UnivariateMotif for Validation 1
📈 379 - UnivariateMotif with avg smape 3.04:
Model Number: 380 of 301 with model UnivariateMotif for Validation 1
380 - UnivariateMotif with avg smape 3.15:
Model Number: 381 of 301 with model SectionalMotif for Validation 1
381 - SectionalMotif with avg smape 3.54:
Model Number: 382 of 301 with model UnivariateMotif for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

382 - UnivariateMotif with avg smape 13.95:
Model Number: 383 of 301 with model FBProphet for Validation 1
383 - FBProphet with avg smape 7.83:
Model Number: 384 of 301 with model SectionalMotif for Validation 1
384 - SectionalMotif with avg smape 10.09:
Model Number: 385 of 301 with model SectionalMotif for Validation 1
385 - SectionalMotif with avg smape 10.09:
Model Number: 386 of 301 with model SectionalMotif for Validation 1
386 - SectionalMotif with avg smape 3.51:
Model Number: 387 of 301 with model UnivariateMotif for Validation 1
387 - UnivariateMotif with avg smape 3.5:

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 388 of 301 with model SectionalMotif for Validation 1
388 - SectionalMotif with avg smape 5.71:
Model Number: 389 of 301 with model SectionalMotif for Validation 1
389 - SectionalMotif with avg smape 3.82:
Model Number: 390 of 301 with model UnivariateMotif for Validation 1
390 - UnivariateMotif with avg smape 3.48:
Model Number: 391 of 301 with model SectionalMotif for Validation 1
📈 391 - SectionalMotif with avg smape 2.98:
Model Number: 392 of 301 with model ETS for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

392 - ETS with avg smape 20.37:
Model Number: 393 of 301 with model UnivariateMotif for Validation 1
393 - UnivariateMotif with avg smape 3.5:
Model Number: 394 of 301 with model SectionalMotif for Validation 1
394 - SectionalMotif with avg smape 3.31:
Model Number: 395 of 301 with model UnivariateMotif for Validation 1
395 - UnivariateMotif with avg smape 3.26:
Model Number: 396 of 301 with model FBProphet for Validation 1

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

396 - FBProphet with avg smape 6.58:
Model Number: 397 of 301 with model FBProphet for Validation 1
No anomalies detected.
397 - FBProphet with avg smape 20.51:
Model Number: 398 of 301 with model DatepartRegression for Validation 1
398 - DatepartRegression with avg smape 21.86:
Model Number: 399 of 301 with model DatepartRegression for Validation 1
399 - DatepartRegression with avg smape 24.29:
Model Number: 400 of 301 with model ETS for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.590e+09, tolerance: 2.226e+06

400 - ETS with avg smape 20.5:
Model Number: 401 of 301 with model ETS for Validation 1
401 - ETS with avg smape 20.5:
Model Number: 402 of 301 with model FBProphet for Validation 1
402 - FBProphet with avg smape 7.8:
Model Number: 403 of 301 with model ETS for Validation 1
403 - ETS with avg smape 20.37:
Model Number: 404 of 301 with model ETS for Validation 1
404 - ETS with avg smape 20.37:
Model Number: 405 of 301 with model ETS for Validation 1
405 - ETS with avg smape 20.37:
Model Number: 406 of 301 with model ARDL for Validation 1
406 - ARDL with avg smape 20.44:
Model Number: 407 of 301 with model FBProphet for Validation 1
407 - FBProphet with avg smape 14.05:
Model Number: 408 of 301 with model ARDL for Validation 1
408 - ARDL with avg smape 27.18:
Model Number: 409 of 301 with model SeasonalityMotif for Validation 1
409 - SeasonalityMotif with avg smape 3.81:
Model Number: 410 of 301 with model SeasonalityMotif for Validation 1
410 - SeasonalityMotif with avg smape 3.81:
Model Number: 411 of 301 with model SeasonalityMotif for Validation 1
411 - SeasonalityMotif with avg smape 3.78:

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 412 of 301 with model SeasonalityMotif for Validation 1
412 - SeasonalityMotif with avg smape 3.78:
Model Number: 413 of 301 with model SeasonalityMotif for Validation 1
413 - SeasonalityMotif with avg smape 4.12:
Model Number: 414 of 301 with model SeasonalityMotif for Validation 1
414 - SeasonalityMotif with avg smape 4.16:
Model Number: 415 of 301 with model SeasonalityMotif for Validation 1

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

415 - SeasonalityMotif with avg smape 4.11:
Model Number: 416 of 301 with model ConstantNaive for Validation 1
416 - ConstantNaive with avg smape 15.52:
Model Number: 417 of 301 with model ConstantNaive for Validation 1
417 - ConstantNaive with avg smape 15.52:
Model Number: 418 of 301 with model ConstantNaive for Validation 1
418 - ConstantNaive with avg smape 15.52:
Model Number: 419 of 301 with model ConstantNaive for Validation 1
419 - ConstantNaive with avg smape 15.52:
Model Number: 420 of 301 with model ConstantNaive for Validation 1
420 - ConstantNaive with avg smape 15.52:
Model Number: 421 of 301 with model ConstantNaive for Validation 1
421 - ConstantNaive with avg smape 15.52:
Model Number: 422 of 301 with model ConstantNaive for Validation 1
422 - ConstantNaive with avg smape 15.52:
Model Number: 423 of 301 with model ConstantNaive for Validation 1
423 - ConstantNaive with avg smape 15.52:
Model Number: 424 of 301 with model SeasonalityMotif for Validation 1
424 - SeasonalityMotif with avg smape 4.34:
Model Number: 425 of 301 with model FBProphet for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

425 - FBProphet with avg smape 4.53:
Model Number: 426 of 301 with model FBProphet for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

426 - FBProphet with avg smape 6.46:
Model Number: 427 of 301 with model ConstantNaive for Validation 1
427 - ConstantNaive with avg smape 14.59:
Model Number: 428 of 301 with model ConstantNaive for Validation 1
428 - ConstantNaive with avg smape 14.59:
Model Number: 429 of 301 with model ConstantNaive for Validation 1
429 - ConstantNaive with avg smape 14.59:
Model Number: 430 of 301 with model SeasonalityMotif for Validation 1
430 - SeasonalityMotif with avg smape 6.97:
Model Number: 431 of 301 with model ConstantNaive for Validation 1
431 - ConstantNaive with avg smape 14.57:
Model Number: 432 of 301 with model ConstantNaive for Validation 1
432 - ConstantNaive with avg smape 14.57:
Model Number: 433 of 301 with model ConstantNaive for Validation 1
433 - ConstantNaive with avg smape 14.57:
Model Number: 434 of 301 with model SeasonalityMotif for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

434 - SeasonalityMotif with avg smape 5.07:
Model Number: 435 of 301 with model FBProphet for Validation 1
📈 435 - FBProphet with avg smape 2.33:
Model Number: 436 of 301 with model SeasonalityMotif for Validation 1
436 - SeasonalityMotif with avg smape 19.62:
Model Number: 437 of 301 with model FBProphet for Validation 1
437 - FBProphet with avg smape 7.98:
Model Number: 438 of 301 with model FBProphet for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

438 - FBProphet with avg smape 5.52:
Model Number: 439 of 301 with model ETS for Validation 1
439 - ETS with avg smape 20.69:
Model Number: 440 of 301 with model SeasonalityMotif for Validation 1
440 - SeasonalityMotif with avg smape 4.43:
Model Number: 441 of 301 with model SeasonalityMotif for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

441 - SeasonalityMotif with avg smape 3.9:
Model Number: 442 of 301 with model SeasonalityMotif for Validation 1
442 - SeasonalityMotif with avg smape 3.9:
Model Number: 443 of 301 with model FBProphet for Validation 1
No anomalies detected.
443 - FBProphet with avg smape 14.36:
Model Number: 444 of 301 with model FBProphet for Validation 1
No anomalies detected.
444 - FBProphet with avg smape 19.13:
Model Number: 445 of 301 with model ETS for Validation 1
445 - ETS with avg smape 20.57:
Model Number: 446 of 301 with model ETS for Validation 1
446 - ETS with avg smape 20.56:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 447 of 301 with model FBProphet for Validation 1
447 - FBProphet with avg smape 3.92:
Model Number: 448 of 301 with model FFT for Validation 1
448 - FFT with avg smape 24.74:
Model Number: 449 of 301 with model SeasonalityMotif for Validation 1
449 - SeasonalityMotif with avg smape 7.8:
Model Number: 450 of 301 with model FFT for Validation 1
450 - FFT with avg smape 20.23:
Model Number: 451 of 301 with model GLM for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

451 - GLM with avg smape 35.66:
Model Number: 452 of 301 with model GLM for Validation 1
452 - GLM with avg smape 35.75:
Model Number: 453 of 301 with model FFT for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

453 - FFT with avg smape 20.13:
Model Number: 454 of 301 with model GLM for Validation 1
454 - GLM with avg smape 75.38:
Model Number: 455 of 301 with model GLM for Validation 1
455 - GLM with avg smape 3.53:
Model Number: 456 of 301 with model GLM for Validation 1
456 - GLM with avg smape 6.2:
Model Number: 457 of 301 with model SeasonalNaive for Validation 1

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

457 - SeasonalNaive with avg smape 5.43:
Model Number: 458 of 301 with model SeasonalNaive for Validation 1
458 - SeasonalNaive with avg smape 5.43:
Model Number: 459 of 301 with model SeasonalNaive for Validation 1
459 - SeasonalNaive with avg smape 14.39:
Model Number: 460 of 301 with model GLM for Validation 1
460 - GLM with avg smape 22.85:
Model Number: 461 of 301 with model GLM for Validation 1
461 - GLM with avg smape 22.85:
Model Number: 462 of 301 with model GLM for Validation 1
462 - GLM with avg smape 22.87:
Model Number: 463 of 301 with model GLM for Validation 1
463 - GLM with avg smape 56.29:
Model Number: 464 of 301 with model SeasonalNaive for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

464 - SeasonalNaive with avg smape 8.29:
Model Number: 465 of 301 with model GLM for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

465 - GLM with avg smape 11.8:
Model Number: 466 of 301 with model SeasonalNaive for Validation 1
466 - SeasonalNaive with avg smape 10.71:
Model Number: 467 of 301 with model SeasonalNaive for Validation 1
467 - SeasonalNaive with avg smape 8.94:
Model Number: 468 of 301 with model GLM for Validation 1

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

468 - GLM with avg smape 7.1:
Model Number: 469 of 301 with model SeasonalNaive for Validation 1
469 - SeasonalNaive with avg smape 5.43:
Model Number: 470 of 301 with model SeasonalNaive for Validation 1
470 - SeasonalNaive with avg smape 5.26:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 471 of 301 with model SeasonalNaive for Validation 1
471 - SeasonalNaive with avg smape 5.26:
Model Number: 472 of 301 with model SeasonalNaive for Validation 1
472 - SeasonalNaive with avg smape 8.81:
Model Number: 473 of 301 with model SeasonalNaive for Validation 1

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

473 - SeasonalNaive with avg smape 8.07:
Model Number: 474 of 301 with model SeasonalNaive for Validation 1
474 - SeasonalNaive with avg smape 5.9:
Model Number: 475 of 301 with model SeasonalNaive for Validation 1
475 - SeasonalNaive with avg smape 5.4:
Model Number: 476 of 301 with model SeasonalNaive for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

476 - SeasonalNaive with avg smape 5.15:
Model Number: 477 of 301 with model SeasonalNaive for Validation 1
477 - SeasonalNaive with avg smape 6.06:
Model Number: 478 of 301 with model FFT for Validation 1
478 - FFT with avg smape 8.14:
Model Number: 479 of 301 with model FFT for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

479 - FFT with avg smape 4.49:
Model Number: 480 of 301 with model SeasonalNaive for Validation 1
480 - SeasonalNaive with avg smape 5.6:
Model Number: 481 of 301 with model FFT for Validation 1
481 - FFT with avg smape 3.85:
Model Number: 482 of 301 with model GLM for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

482 - GLM with avg smape 5.06:
Model Number: 483 of 301 with model RRVAR for Validation 1
483 - RRVAR with avg smape 6.79:
Model Number: 484 of 301 with model RRVAR for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

484 - RRVAR with avg smape 6.79:
Model Number: 485 of 301 with model GLM for Validation 1
485 - GLM with avg smape 15.95:
Model Number: 486 of 301 with model WindowRegression for Validation 1
486 - WindowRegression with avg smape 5.69:
Model Number: 487 of 301 with model GLM for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

487 - GLM with avg smape 5.9:
Model Number: 488 of 301 with model WindowRegression for Validation 1
488 - WindowRegression with avg smape 6.78:
Model Number: 489 of 301 with model FFT for Validation 1
489 - FFT with avg smape 17.68:
Model Number: 490 of 301 with model FFT for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

490 - FFT with avg smape 6.15:
Model Number: 491 of 301 with model FFT for Validation 1
491 - FFT with avg smape 6.15:
Model Number: 492 of 301 with model GLM for Validation 1
492 - GLM with avg smape 7.1:
Model Number: 493 of 301 with model FFT for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.58942e-25): result may not be accurate.

493 - FFT with avg smape 6.47:
Model Number: 494 of 301 with model GLM for Validation 1
494 - GLM with avg smape 7.1:
Model Number: 495 of 301 with model FFT for Validation 1
495 - FFT with avg smape 7.76:
Model Number: 496 of 301 with model FFT for Validation 1
496 - FFT with avg smape 8.17:
Model Number: 497 of 301 with model RRVAR for Validation 1
497 - RRVAR with avg smape 6.45:
Model Number: 498 of 301 with model RRVAR for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

498 - RRVAR with avg smape 6.45:
Model Number: 499 of 301 with model RRVAR for Validation 1
499 - RRVAR with avg smape 6.45:
Model Number: 500 of 301 with model RRVAR for Validation 1
500 - RRVAR with avg smape 4.4:
Model Number: 501 of 301 with model FFT for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

501 - FFT with avg smape 5.68:
Model Number: 502 of 301 with model FFT for Validation 1
502 - FFT with avg smape 10.57:
Model Number: 503 of 301 with model FFT for Validation 1
503 - FFT with avg smape 8.74:
Model Number: 504 of 301 with model RRVAR for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

504 - RRVAR with avg smape 5.49:
Model Number: 505 of 301 with model WindowRegression for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.58942e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

505 - WindowRegression with avg smape 10.94:
Model Number: 506 of 301 with model RRVAR for Validation 1
506 - RRVAR with avg smape 4.75:
Model Number: 507 of 301 with model FFT for Validation 1
507 - FFT with avg smape 5.8:
Model Number: 508 of 301 with model RRVAR for Validation 1

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

508 - RRVAR with avg smape 4.75:
Model Number: 509 of 301 with model RRVAR for Validation 1
509 - RRVAR with avg smape 4.62:

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Validation Round: 2
Model Number: 1 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

📈 1 - Ensemble with avg smape 51.36:
📈 2 - Ensemble with avg smape 51.15:
📈 3 - Ensemble with avg smape 43.69:
4 - Ensemble with avg smape 54.53:
📈 5 - Ensemble with avg smape 10.75:
📈 6 - Ensemble with avg smape 8.25:
📈 7 - Ensemble with avg smape 2.99:
📈 8 - Ensemble with avg smape 2.84:
9 - Ensemble with avg smape 51.36:
10 - Ensemble with avg smape 13.09:
11 - Ensemble with avg smape 22.21:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

12 - Ensemble with avg smape 51.52:
13 - Ensemble with avg smape 36.72:
14 - Ensemble with avg smape 28.61:
Model Number: 15 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

15 - Ensemble with avg smape 51.36:
16 - Ensemble with avg smape 51.15:
17 - Ensemble with avg smape 43.69:
18 - Ensemble with avg smape 54.53:
19 - Ensemble with avg smape 10.75:
20 - Ensemble with avg smape 8.25:
21 - Ensemble with avg smape 2.99:
22 - Ensemble with avg smape 2.84:
23 - Ensemble with avg smape 51.36:
24 - Ensemble with avg smape 13.09:
25 - Ensemble with avg smape 22.21:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

26 - Ensemble with avg smape 51.52:
27 - Ensemble with avg smape 36.72:
28 - Ensemble with avg smape 28.61:
Model Number: 29 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

29 - Ensemble with avg smape 51.36:
30 - Ensemble with avg smape 51.15:
31 - Ensemble with avg smape 43.69:
32 - Ensemble with avg smape 54.53:
33 - Ensemble with avg smape 10.75:
34 - Ensemble with avg smape 8.25:
35 - Ensemble with avg smape 2.99:
36 - Ensemble with avg smape 2.84:
37 - Ensemble with avg smape 51.36:
38 - Ensemble with avg smape 13.09:
39 - Ensemble with avg smape 22.21:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

40 - Ensemble with avg smape 51.52:
41 - Ensemble with avg smape 36.72:
42 - Ensemble with avg smape 28.61:
Model Number: 43 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

43 - Ensemble with avg smape 51.36:
44 - Ensemble with avg smape 51.15:
45 - Ensemble with avg smape 43.69:
46 - Ensemble with avg smape 54.53:
47 - Ensemble with avg smape 10.75:
48 - Ensemble with avg smape 8.25:
49 - Ensemble with avg smape 2.99:
50 - Ensemble with avg smape 2.84:
51 - Ensemble with avg smape 51.36:
52 - Ensemble with avg smape 13.09:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

53 - Ensemble with avg smape 22.21:
54 - Ensemble with avg smape 51.52:
55 - Ensemble with avg smape 36.72:
56 - Ensemble with avg smape 28.61:
Model Number: 57 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

57 - Ensemble with avg smape 51.36:
58 - Ensemble with avg smape 51.15:
59 - Ensemble with avg smape 43.69:
60 - Ensemble with avg smape 54.53:
61 - Ensemble with avg smape 10.75:
62 - Ensemble with avg smape 8.25:
63 - Ensemble with avg smape 2.99:
64 - Ensemble with avg smape 2.84:
65 - Ensemble with avg smape 51.36:
66 - Ensemble with avg smape 13.09:
67 - Ensemble with avg smape 22.21:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

68 - Ensemble with avg smape 51.52:
69 - Ensemble with avg smape 36.72:
70 - Ensemble with avg smape 28.61:
Model Number: 71 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

71 - Ensemble with avg smape 54.13:
72 - Ensemble with avg smape 53.94:
73 - Ensemble with avg smape 46.98:
74 - Ensemble with avg smape 57.27:
75 - Ensemble with avg smape 10.85:
76 - Ensemble with avg smape 8.25:
77 - Ensemble with avg smape 2.99:
78 - Ensemble with avg smape 2.84:
79 - Ensemble with avg smape 54.13:
80 - Ensemble with avg smape 13.09:
81 - Ensemble with avg smape 22.67:
82 - Ensemble with avg smape 54.29:
83 - Ensemble with avg smape 39.16:
84 - Ensemble with avg smape 30.8:
Model Number: 85 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

85 - Ensemble with avg smape 54.13:
86 - Ensemble with avg smape 53.94:
87 - Ensemble with avg smape 46.98:
88 - Ensemble with avg smape 57.27:
89 - Ensemble with avg smape 10.85:
90 - Ensemble with avg smape 8.25:
91 - Ensemble with avg smape 2.99:
92 - Ensemble with avg smape 2.84:
93 - Ensemble with avg smape 54.13:
94 - Ensemble with avg smape 13.09:
95 - Ensemble with avg smape 22.67:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

96 - Ensemble with avg smape 54.29:
97 - Ensemble with avg smape 39.16:
98 - Ensemble with avg smape 30.8:
Model Number: 99 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

99 - Ensemble with avg smape 54.13:
100 - Ensemble with avg smape 53.94:
101 - Ensemble with avg smape 46.98:
102 - Ensemble with avg smape 57.27:
103 - Ensemble with avg smape 10.85:
104 - Ensemble with avg smape 8.25:
105 - Ensemble with avg smape 2.99:
106 - Ensemble with avg smape 2.84:
107 - Ensemble with avg smape 54.13:
108 - Ensemble with avg smape 13.09:
109 - Ensemble with avg smape 22.67:
110 - Ensemble with avg smape 54.29:
111 - Ensemble with avg smape 39.16:
112 - Ensemble with avg smape 30.8:
Model Number: 113 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

113 - Ensemble with avg smape 49.55:
114 - Ensemble with avg smape 49.2:
115 - Ensemble with avg smape 38.77:
116 - Ensemble with avg smape 50.3:
117 - Ensemble with avg smape 10.56:
118 - Ensemble with avg smape 8.25:
119 - Ensemble with avg smape 2.99:
120 - Ensemble with avg smape 2.84:
121 - Ensemble with avg smape 49.55:
122 - Ensemble with avg smape 13.09:
123 - Ensemble with avg smape 18.59:
124 - Ensemble with avg smape 49.71:
125 - Ensemble with avg smape 32.75:
126 - Ensemble with avg smape 24.73:
Model Number: 127 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

127 - Ensemble with avg smape 49.43:
128 - Ensemble with avg smape 49.09:
129 - Ensemble with avg smape 38.79:
130 - Ensemble with avg smape 50.28:
131 - Ensemble with avg smape 10.56:
132 - Ensemble with avg smape 8.25:
133 - Ensemble with avg smape 2.99:
134 - Ensemble with avg smape 2.84:
135 - Ensemble with avg smape 49.43:
136 - Ensemble with avg smape 13.09:
137 - Ensemble with avg smape 18.58:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

138 - Ensemble with avg smape 49.59:
139 - Ensemble with avg smape 32.77:
140 - Ensemble with avg smape 24.77:
Model Number: 141 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

141 - Ensemble with avg smape 47.39:
142 - Ensemble with avg smape 47.13:
143 - Ensemble with avg smape 38.17:
144 - Ensemble with avg smape 49.47:
145 - Ensemble with avg smape 10.57:
146 - Ensemble with avg smape 8.25:
147 - Ensemble with avg smape 2.99:
148 - Ensemble with avg smape 2.84:
149 - Ensemble with avg smape 47.39:
150 - Ensemble with avg smape 13.09:
151 - Ensemble with avg smape 18.7:
152 - Ensemble with avg smape 47.56:
153 - Ensemble with avg smape 32.43:
154 - Ensemble with avg smape 24.67:
Model Number: 155 of 301 with model Cassandra for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

155 - Cassandra with avg smape 50.08:
Model Number: 156 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

156 - Ensemble with avg smape 53.39:
157 - Ensemble with avg smape 53.18:
158 - Ensemble with avg smape 45.86:
159 - Ensemble with avg smape 56.84:
160 - Ensemble with avg smape 10.83:
161 - Ensemble with avg smape 8.25:
162 - Ensemble with avg smape 2.99:
163 - Ensemble with avg smape 2.84:
164 - Ensemble with avg smape 53.39:
165 - Ensemble with avg smape 13.09:
166 - Ensemble with avg smape 23.12:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

167 - Ensemble with avg smape 53.55:
168 - Ensemble with avg smape 38.38:
169 - Ensemble with avg smape 30.09:
Model Number: 170 of 301 with model Cassandra for Validation 2
170 - Cassandra with avg smape 54.87:
Model Number: 171 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

171 - Ensemble with avg smape 53.39:
172 - Ensemble with avg smape 53.18:
173 - Ensemble with avg smape 45.86:
174 - Ensemble with avg smape 56.84:
175 - Ensemble with avg smape 10.83:
176 - Ensemble with avg smape 8.25:
177 - Ensemble with avg smape 2.99:
178 - Ensemble with avg smape 2.84:
179 - Ensemble with avg smape 53.39:
180 - Ensemble with avg smape 13.09:
181 - Ensemble with avg smape 23.12:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

182 - Ensemble with avg smape 53.55:
183 - Ensemble with avg smape 38.38:
184 - Ensemble with avg smape 30.09:
Model Number: 185 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

185 - Ensemble with avg smape 53.39:
186 - Ensemble with avg smape 53.18:
187 - Ensemble with avg smape 45.86:
188 - Ensemble with avg smape 56.84:
189 - Ensemble with avg smape 10.83:
190 - Ensemble with avg smape 8.25:
191 - Ensemble with avg smape 2.99:
192 - Ensemble with avg smape 2.84:
193 - Ensemble with avg smape 53.39:
194 - Ensemble with avg smape 13.09:
195 - Ensemble with avg smape 23.12:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

196 - Ensemble with avg smape 53.55:
197 - Ensemble with avg smape 38.38:
198 - Ensemble with avg smape 30.09:
Model Number: 199 of 301 with model Cassandra for Validation 2
199 - Cassandra with avg smape 57.04:
Model Number: 200 of 301 with model Cassandra for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

200 - Cassandra with avg smape 57.04:
Model Number: 201 of 301 with model Cassandra for Validation 2
201 - Cassandra with avg smape 48.14:
Model Number: 202 of 301 with model Cassandra for Validation 2

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

202 - Cassandra with avg smape 48.14:
Model Number: 203 of 301 with model Cassandra for Validation 2
203 - Cassandra with avg smape 48.14:
Model Number: 204 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

204 - Ensemble with avg smape 47.39:
205 - Ensemble with avg smape 47.13:
206 - Ensemble with avg smape 38.17:
207 - Ensemble with avg smape 49.47:
208 - Ensemble with avg smape 10.57:
209 - Ensemble with avg smape 8.25:
210 - Ensemble with avg smape 2.99:
211 - Ensemble with avg smape 2.84:
212 - Ensemble with avg smape 47.39:
213 - Ensemble with avg smape 13.09:
214 - Ensemble with avg smape 18.7:
215 - Ensemble with avg smape 47.56:
216 - Ensemble with avg smape 32.43:
217 - Ensemble with avg smape 24.67:
Model Number: 218 of 301 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

218 - Ensemble with avg smape 47.39:
219 - Ensemble with avg smape 47.13:
220 - Ensemble with avg smape 38.17:
221 - Ensemble with avg smape 49.47:
222 - Ensemble with avg smape 10.57:
223 - Ensemble with avg smape 8.25:
224 - Ensemble with avg smape 2.99:
225 - Ensemble with avg smape 2.84:
226 - Ensemble with avg smape 47.39:
227 - Ensemble with avg smape 13.09:
228 - Ensemble with avg smape 18.7:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

229 - Ensemble with avg smape 47.56:
230 - Ensemble with avg smape 32.43:
231 - Ensemble with avg smape 24.67:
Model Number: 232 of 301 with model Cassandra for Validation 2
232 - Cassandra with avg smape 48.14:
Model Number: 233 of 301 with model Cassandra for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

233 - Cassandra with avg smape 48.14:
Model Number: 234 of 301 with model Cassandra for Validation 2
234 - Cassandra with avg smape 48.14:
Model Number: 235 of 301 with model Cassandra for Validation 2

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

235 - Cassandra with avg smape 48.14:
Model Number: 236 of 301 with model Cassandra for Validation 2
236 - Cassandra with avg smape 54.87:
Model Number: 237 of 301 with model Cassandra for Validation 2

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

237 - Cassandra with avg smape 54.87:
Model Number: 238 of 301 with model Cassandra for Validation 2
238 - Cassandra with avg smape 48.1:
Model Number: 239 of 301 with model Cassandra for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

239 - Cassandra with avg smape 54.8:
Model Number: 240 of 301 with model Cassandra for Validation 2
240 - Cassandra with avg smape 54.8:
Model Number: 241 of 301 with model FBProphet for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

241 - FBProphet with avg smape 42.23:
Model Number: 242 of 301 with model AverageValueNaive for Validation 2
242 - AverageValueNaive with avg smape 49.46:
Model Number: 243 of 301 with model AverageValueNaive for Validation 2
243 - AverageValueNaive with avg smape 49.43:
Model Number: 244 of 301 with model AverageValueNaive for Validation 2
244 - AverageValueNaive with avg smape 49.38:
Model Number: 245 of 301 with model BasicLinearModel for Validation 2
245 - BasicLinearModel with avg smape 55.58:
Model Number: 246 of 301 with model AverageValueNaive for Validation 2

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

246 - AverageValueNaive with avg smape 49.28:
Model Number: 247 of 301 with model BasicLinearModel for Validation 2
247 - BasicLinearModel with avg smape 47.25:
Model Number: 248 of 301 with model AverageValueNaive for Validation 2
248 - AverageValueNaive with avg smape 49.46:
Model Number: 249 of 301 with model BasicLinearModel for Validation 2
249 - BasicLinearModel with avg smape 48.41:
Model Number: 250 of 301 with model BasicLinearModel for Validation 2
250 - BasicLinearModel with avg smape 48.41:
Model Number: 251 of 301 with model ARDL for Validation 2
251 - ARDL with avg smape 49.3:
Model Number: 252 of 301 with model ARDL for Validation 2
252 - ARDL with avg smape 49.3:
Model Number: 253 of 301 with model BasicLinearModel for Validation 2
253 - BasicLinearModel with avg smape 45.27:
Model Number: 254 of 301 with model BasicLinearModel for Validation 2
254 - BasicLinearModel with avg smape 47.67:
Model Number: 255 of 301 with model ARDL for Validation 2
255 - ARDL with avg smape 49.49:
Model Number: 256 of 301 with model ARDL for Validation 2
256 - ARDL with avg smape 49.48:
Model Number: 257 of 301 with model ARDL for Validation 2
257 - ARDL with avg smape 49.26:
Model Number: 258 of 301 with model ARDL for Validation 2
258 - ARDL with avg smape 49.36:
Model Number: 259 of 301 with model GLS for Validation 2
259 - GLS with avg smape 49.46:
Model Number: 260 of 301 with model GLS for Validation 2
260 - GLS with avg smape 49.46:
Model Number: 261 of 301 with model GLS for Validation 2
261 - GLS with avg smape 49.46:
Model Number: 262 of 301 with model GLS for Validation 2
262 - GLS with avg smape 49.46:
Model Number: 263 of 301 with model GLS for Validation 2
263 - GLS with avg smape 49.46:
Model Number: 264 of 301 with model GLS for Validation 2
264 - GLS with avg smape 49.46:
Model Number: 265 of 301 with model GLS for Validation 2
265 - GLS with avg smape 49.46:
Model Number: 266 of 301 with model BasicLinearModel for Validation 2
266 - BasicLinearModel with avg smape 45.3:
Model Number: 267 of 301 with model BasicLinearModel for Validation 2
267 - BasicLinearModel with avg smape 45.28:
Model Number: 268 of 301 with model ETS for Validation 2
268 - ETS with avg smape 46.39:
Model Number: 269 of 301 with model ETS for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

269 - ETS with avg smape 46.39:
Model Number: 270 of 301 with model GLS for Validation 2
270 - GLS with avg smape 49.5:
Model Number: 271 of 301 with model GLS for Validation 2
271 - GLS with avg smape 49.5:
Model Number: 272 of 301 with model GLS for Validation 2
272 - GLS with avg smape 49.5:
Model Number: 273 of 301 with model GLS for Validation 2
273 - GLS with avg smape 49.5:
Model Number: 274 of 301 with model ARDL for Validation 2
274 - ARDL with avg smape 55.62:
Model Number: 275 of 301 with model AverageValueNaive for Validation 2
275 - AverageValueNaive with avg smape 49.38:
Model Number: 276 of 301 with model GLS for Validation 2

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

276 - GLS with avg smape 48.01:
Model Number: 277 of 301 with model GLS for Validation 2
277 - GLS with avg smape 48.01:
Model Number: 278 of 301 with model GLS for Validation 2
278 - GLS with avg smape 48.01:
Model Number: 279 of 301 with model GLS for Validation 2
279 - GLS with avg smape 48.02:
Model Number: 280 of 301 with model GLS for Validation 2
280 - GLS with avg smape 48.02:
Model Number: 281 of 301 with model BasicLinearModel for Validation 2
281 - BasicLinearModel with avg smape 57.96:
Model Number: 282 of 301 with model AverageValueNaive for Validation 2
282 - AverageValueNaive with avg smape 49.14:
Model Number: 283 of 301 with model AverageValueNaive for Validation 2
283 - AverageValueNaive with avg smape 49.47:
Model Number: 284 of 301 with model AverageValueNaive for Validation 2
284 - AverageValueNaive with avg smape 49.47:
Model Number: 285 of 301 with model AverageValueNaive for Validation 2
285 - AverageValueNaive with avg smape 49.46:
Model Number: 286 of 301 with model AverageValueNaive for Validation 2
286 - AverageValueNaive with avg smape 49.46:
Model Number: 287 of 301 with model AverageValueNaive for Validation 2
287 - AverageValueNaive with avg smape 49.46:
Model Number: 288 of 301 with model AverageValueNaive for Validation 2
288 - AverageValueNaive with avg smape 49.45:
Model Number: 289 of 301 with model AverageValueNaive for Validation 2
289 - AverageValueNaive with avg smape 49.45:
Model Number: 290 of 301 with model AverageValueNaive for Validation 2
290 - AverageValueNaive with avg smape 59.25:
Model Number: 291 of 301 with model BasicLinearModel for Validation 2
291 - BasicLinearModel with avg smape 48.97:
Model Number: 292 of 301 with model AverageValueNaive for Validation 2
292 - AverageValueNaive with avg smape 49.47:
Model Number: 293 of 301 with model DatepartRegression for Validation 2
293 - DatepartRegression with avg smape 15.04:
Model Number: 294 of 301 with model LastValueNaive for Validation 2
294 - LastValueNaive with avg smape 46.43:
Model Number: 295 of 301 with model LastValueNaive for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.134e+00, tolerance: 1.290e-02

295 - LastValueNaive with avg smape 46.39:
Model Number: 296 of 301 with model LastValueNaive for Validation 2
296 - LastValueNaive with avg smape 46.39:
Model Number: 297 of 301 with model LastValueNaive for Validation 2
297 - LastValueNaive with avg smape 46.39:
Model Number: 298 of 301 with model LastValueNaive for Validation 2
298 - LastValueNaive with avg smape 46.39:
Model Number: 299 of 301 with model LastValueNaive for Validation 2
299 - LastValueNaive with avg smape 46.39:
Model Number: 300 of 301 with model LastValueNaive for Validation 2
300 - LastValueNaive with avg smape 46.39:
Model Number: 301 of 301 with model LastValueNaive for Validation 2
301 - LastValueNaive with avg smape 46.39:
Model Number: 302 of 301 with model LastValueNaive for Validation 2
302 - LastValueNaive with avg smape 46.39:
Model Number: 303 of 301 with model ARDL for Validation 2
303 - ARDL with avg smape 49.76:
Model Number: 304 of 301 with model LastValueNaive for Validation 2
304 - LastValueNaive with avg smape 47.59:
Model Number: 305 of 301 with model LastValueNaive for Validation 2
305 - LastValueNaive with avg smape 47.59:
Model Number: 306 of 301 with model LastValueNaive for Validation 2
306 - LastValueNaive with avg smape 47.59:
Model Number: 307 of 301 with model BasicLinearModel for Validation 2
307 - BasicLinearModel with avg smape 56.13:
Model Number: 308 of 301 with model BasicLinearModel for Validation 2
308 - BasicLinearModel with avg smape 55.92:
Model Number: 309 of 301 with model BasicLinearModel for Validation 2
309 - BasicLinearModel with avg smape 45.48:
Model Number: 310 of 301 with model BasicLinearModel for Validation 2
310 - BasicLinearModel with avg smape 57.73:
Model Number: 311 of 301 with model DatepartRegression for Validation 2
311 - DatepartRegression with avg smape 46.31:
Model Number: 312 of 301 with model BasicLinearModel for Validation 2
312 - BasicLinearModel with avg smape 56.42:
Model Number: 313 of 301 with model BasicLinearModel for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.446e+09, tolerance: 2.067e+06

313 - BasicLinearModel with avg smape 55.98:
Model Number: 314 of 301 with model DatepartRegression for Validation 2
314 - DatepartRegression with avg smape 49.26:
Model Number: 315 of 301 with model DatepartRegression for Validation 2
315 - DatepartRegression with avg smape 46.32:
Model Number: 316 of 301 with model DatepartRegression for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.456e+09, tolerance: 2.070e+06

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.456e+09, tolerance: 2.070e+06

316 - DatepartRegression with avg smape 46.32:
Model Number: 317 of 301 with model LastValueNaive for Validation 2
317 - LastValueNaive with avg smape 52.7:
Model Number: 318 of 301 with model ARDL for Validation 2
318 - ARDL with avg smape 49.19:
Model Number: 319 of 301 with model DatepartRegression for Validation 2
319 - DatepartRegression with avg smape 47.32:
Model Number: 320 of 301 with model DatepartRegression for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.189e+00, tolerance: 8.869e-03

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.957e+00, tolerance: 8.855e-03

320 - DatepartRegression with avg smape 47.31:
Model Number: 321 of 301 with model DatepartRegression for Validation 2
321 - DatepartRegression with avg smape 47.31:
Model Number: 322 of 301 with model DatepartRegression for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.957e+00, tolerance: 8.855e-03

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.334e+09, tolerance: 1.818e+06

322 - DatepartRegression with avg smape 46.48:
Model Number: 323 of 301 with model ETS for Validation 2
323 - ETS with avg smape 54.78:
Model Number: 324 of 301 with model ETS for Validation 2
324 - ETS with avg smape 54.78:
Model Number: 325 of 301 with model ARDL for Validation 2
325 - ARDL with avg smape 55.79:
Model Number: 326 of 301 with model DatepartRegression for Validation 2
326 - DatepartRegression with avg smape 46.47:
Model Number: 327 of 301 with model DatepartRegression for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.338e+09, tolerance: 1.820e+06

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.268e+00, tolerance: 9.889e-03

327 - DatepartRegression with avg smape 47.32:
Model Number: 328 of 301 with model UnivariateMotif for Validation 2
328 - UnivariateMotif with avg smape 51.17:
Model Number: 329 of 301 with model LastValueNaive for Validation 2
329 - LastValueNaive with avg smape 47.31:
Model Number: 330 of 301 with model LastValueNaive for Validation 2
330 - LastValueNaive with avg smape 47.31:
Model Number: 331 of 301 with model LastValueNaive for Validation 2
331 - LastValueNaive with avg smape 47.28:
Model Number: 332 of 301 with model DatepartRegression for Validation 2
Epoch 1/50

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

41/41 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - loss: 0.0682
Epoch 2/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0566
Epoch 3/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0565
Epoch 4/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0574
Epoch 5/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0551
Epoch 6/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0556
Epoch 7/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0544
Epoch 8/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0538
Epoch 9/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0527
Epoch 10/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0534
Epoch 11/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0531
Epoch 12/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0522
Epoch 13/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0534
Epoch 14/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0522
Epoch 15/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0536
Epoch 16/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0529
Epoch 17/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0531
Epoch 18/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0531
Epoch 19/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0529
Epoch 20/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0535
Epoch 21/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0535
Epoch 22/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0533
Epoch 23/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0525
Epoch 24/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0536
Epoch 25/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0523
Epoch 26/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0515
Epoch 27/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0529
Epoch 28/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0543
Epoch 29/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0523
Epoch 30/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0509
Epoch 31/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0503
Epoch 32/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0507
Epoch 33/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0518
Epoch 34/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0514
Epoch 35/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0504
Epoch 36/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0491
Epoch 37/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0501
Epoch 38/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0497
Epoch 39/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0474
Epoch 40/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0495
Epoch 41/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0478
Epoch 42/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0505
Epoch 43/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0476
Epoch 44/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0494
Epoch 45/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0471
Epoch 46/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0451
Epoch 47/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0454
Epoch 48/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0477
Epoch 49/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0465
Epoch 50/50
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0477
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 408ms/step
332 - DatepartRegression with avg smape 48.79:
Model Number: 333 of 301 with model SeasonalityMotif for Validation 2
333 - SeasonalityMotif with avg smape 55.34:
Model Number: 334 of 301 with model DatepartRegression for Validation 2
334 - DatepartRegression with avg smape 50.16:
Model Number: 335 of 301 with model ARDL for Validation 2
335 - ARDL with avg smape 18.85:
Model Number: 336 of 301 with model FBProphet for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

336 - FBProphet with avg smape 45.65:
Model Number: 337 of 301 with model ARDL for Validation 2
337 - ARDL with avg smape 49.18:
Model Number: 338 of 301 with model MetricMotif for Validation 2
338 - MetricMotif with avg smape 34.51:
Model Number: 339 of 301 with model MetricMotif for Validation 2
339 - MetricMotif with avg smape 34.51:
Model Number: 340 of 301 with model MetricMotif for Validation 2
340 - MetricMotif with avg smape 34.51:
Model Number: 341 of 301 with model MetricMotif for Validation 2
341 - MetricMotif with avg smape 34.51:
Model Number: 342 of 301 with model UnivariateMotif for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

342 - UnivariateMotif with avg smape 44.04:
Model Number: 343 of 301 with model ETS for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

343 - ETS with avg smape 56.0:
Model Number: 344 of 301 with model MetricMotif for Validation 2
344 - MetricMotif with avg smape 49.49:
Model Number: 345 of 301 with model ETS for Validation 2
345 - ETS with avg smape 49.07:
Model Number: 346 of 301 with model ARDL for Validation 2
346 - ARDL with avg smape 48.99:
Model Number: 347 of 301 with model MetricMotif for Validation 2
347 - MetricMotif with avg smape 50.21:
Model Number: 348 of 301 with model MetricMotif for Validation 2
348 - MetricMotif with avg smape 23.86:
Model Number: 349 of 301 with model UnivariateMotif for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

349 - UnivariateMotif with avg smape 43.64:
Model Number: 350 of 301 with model MetricMotif for Validation 2
350 - MetricMotif with avg smape 53.04:
Model Number: 351 of 301 with model FBProphet for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

351 - FBProphet with avg smape 56.73:
Model Number: 352 of 301 with model SectionalMotif for Validation 2
352 - SectionalMotif with avg smape 39.01:
Model Number: 353 of 301 with model MetricMotif for Validation 2
353 - MetricMotif with avg smape 34.45:
Model Number: 354 of 301 with model MetricMotif for Validation 2
354 - MetricMotif with avg smape 34.45:
Model Number: 355 of 301 with model ETS for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

355 - ETS with avg smape 48.46:
Model Number: 356 of 301 with model ConstantNaive for Validation 2
356 - ConstantNaive with avg smape 49.46:
Model Number: 357 of 301 with model ConstantNaive for Validation 2
357 - ConstantNaive with avg smape 49.46:
Model Number: 358 of 301 with model SectionalMotif for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.071e+10, tolerance: 2.527e+06

358 - SectionalMotif with avg smape 30.88:
Model Number: 359 of 301 with model DatepartRegression for Validation 2
359 - DatepartRegression with avg smape 45.64:
Model Number: 360 of 301 with model SectionalMotif for Validation 2
360 - SectionalMotif with avg smape 43.47:
Model Number: 361 of 301 with model SectionalMotif for Validation 2
361 - SectionalMotif with avg smape 41.82:
Model Number: 362 of 301 with model MetricMotif for Validation 2
362 - MetricMotif with avg smape 35.54:
Model Number: 363 of 301 with model SectionalMotif for Validation 2
363 - SectionalMotif with avg smape 30.98:
Model Number: 364 of 301 with model MetricMotif for Validation 2
364 - MetricMotif with avg smape 53.27:
Model Number: 365 of 301 with model MetricMotif for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

365 - MetricMotif with avg smape 48.43:
Model Number: 366 of 301 with model UnivariateMotif for Validation 2
366 - UnivariateMotif with avg smape 17.13:
Model Number: 367 of 301 with model SectionalMotif for Validation 2
367 - SectionalMotif with avg smape 39.88:
Model Number: 368 of 301 with model ARDL for Validation 2
368 - ARDL with avg smape 56.17:
Model Number: 369 of 301 with model MetricMotif for Validation 2
369 - MetricMotif with avg smape 8.55:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 370 of 301 with model MetricMotif for Validation 2
370 - MetricMotif with avg smape 8.55:
Model Number: 371 of 301 with model MetricMotif for Validation 2
371 - MetricMotif with avg smape 8.55:
Model Number: 372 of 301 with model SectionalMotif for Validation 2
372 - SectionalMotif with avg smape 39.61:
Model Number: 373 of 301 with model UnivariateMotif for Validation 2
373 - UnivariateMotif with avg smape 30.8:
Model Number: 374 of 301 with model UnivariateMotif for Validation 2
374 - UnivariateMotif with avg smape 23.96:
Model Number: 375 of 301 with model UnivariateMotif for Validation 2

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

375 - UnivariateMotif with avg smape 30.09:
Model Number: 376 of 301 with model UnivariateMotif for Validation 2
376 - UnivariateMotif with avg smape 23.96:
Model Number: 377 of 301 with model UnivariateMotif for Validation 2
377 - UnivariateMotif with avg smape 23.96:
Model Number: 378 of 301 with model SectionalMotif for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

378 - SectionalMotif with avg smape 39.49:
Model Number: 379 of 301 with model UnivariateMotif for Validation 2
379 - UnivariateMotif with avg smape 20.29:
Model Number: 380 of 301 with model UnivariateMotif for Validation 2
380 - UnivariateMotif with avg smape 35.91:
Model Number: 381 of 301 with model SectionalMotif for Validation 2
381 - SectionalMotif with avg smape 40.8:
Model Number: 382 of 301 with model UnivariateMotif for Validation 2
382 - UnivariateMotif with avg smape 53.0:

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 383 of 301 with model FBProphet for Validation 2
383 - FBProphet with avg smape 45.72:
Model Number: 384 of 301 with model SectionalMotif for Validation 2
384 - SectionalMotif with avg smape 38.69:
Model Number: 385 of 301 with model SectionalMotif for Validation 2
385 - SectionalMotif with avg smape 38.69:
Model Number: 386 of 301 with model SectionalMotif for Validation 2
386 - SectionalMotif with avg smape 20.22:
Model Number: 387 of 301 with model UnivariateMotif for Validation 2
387 - UnivariateMotif with avg smape 16.0:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 388 of 301 with model SectionalMotif for Validation 2
388 - SectionalMotif with avg smape 38.67:
Model Number: 389 of 301 with model SectionalMotif for Validation 2
389 - SectionalMotif with avg smape 37.75:
Model Number: 390 of 301 with model UnivariateMotif for Validation 2
390 - UnivariateMotif with avg smape 26.7:
Model Number: 391 of 301 with model SectionalMotif for Validation 2
391 - SectionalMotif with avg smape 22.79:
Model Number: 392 of 301 with model ETS for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

392 - ETS with avg smape 49.19:
Model Number: 393 of 301 with model UnivariateMotif for Validation 2
393 - UnivariateMotif with avg smape 34.3:
Model Number: 394 of 301 with model SectionalMotif for Validation 2
394 - SectionalMotif with avg smape 38.23:
Model Number: 395 of 301 with model UnivariateMotif for Validation 2
395 - UnivariateMotif with avg smape 22.42:
Model Number: 396 of 301 with model FBProphet for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

396 - FBProphet with avg smape 56.78:
Model Number: 397 of 301 with model FBProphet for Validation 2
No anomalies detected.
397 - FBProphet with avg smape 56.16:
Model Number: 398 of 301 with model DatepartRegression for Validation 2
398 - DatepartRegression with avg smape 56.69:
Model Number: 399 of 301 with model DatepartRegression for Validation 2
399 - DatepartRegression with avg smape 46.16:
Model Number: 400 of 301 with model ETS for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.512e+09, tolerance: 1.858e+06

400 - ETS with avg smape 56.27:
Model Number: 401 of 301 with model ETS for Validation 2
401 - ETS with avg smape 56.27:
Model Number: 402 of 301 with model FBProphet for Validation 2
402 - FBProphet with avg smape 45.72:
Model Number: 403 of 301 with model ETS for Validation 2
403 - ETS with avg smape 49.19:
Model Number: 404 of 301 with model ETS for Validation 2
404 - ETS with avg smape 49.19:
Model Number: 405 of 301 with model ETS for Validation 2
405 - ETS with avg smape 49.19:
Model Number: 406 of 301 with model ARDL for Validation 2
406 - ARDL with avg smape 55.3:
Model Number: 407 of 301 with model FBProphet for Validation 2
407 - FBProphet with avg smape 51.93:
Model Number: 408 of 301 with model ARDL for Validation 2
408 - ARDL with avg smape 47.35:
Model Number: 409 of 301 with model SeasonalityMotif for Validation 2
409 - SeasonalityMotif with avg smape 6.07:
Model Number: 410 of 301 with model SeasonalityMotif for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

410 - SeasonalityMotif with avg smape 6.07:
Model Number: 411 of 301 with model SeasonalityMotif for Validation 2
411 - SeasonalityMotif with avg smape 4.97:
Model Number: 412 of 301 with model SeasonalityMotif for Validation 2
412 - SeasonalityMotif with avg smape 4.97:
Model Number: 413 of 301 with model SeasonalityMotif for Validation 2

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

413 - SeasonalityMotif with avg smape 33.45:
Model Number: 414 of 301 with model SeasonalityMotif for Validation 2
414 - SeasonalityMotif with avg smape 32.84:
Model Number: 415 of 301 with model SeasonalityMotif for Validation 2
415 - SeasonalityMotif with avg smape 11.78:
Model Number: 416 of 301 with model ConstantNaive for Validation 2
416 - ConstantNaive with avg smape 30.97:
Model Number: 417 of 301 with model ConstantNaive for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

417 - ConstantNaive with avg smape 30.97:
Model Number: 418 of 301 with model ConstantNaive for Validation 2
418 - ConstantNaive with avg smape 30.97:
Model Number: 419 of 301 with model ConstantNaive for Validation 2
419 - ConstantNaive with avg smape 30.97:
Model Number: 420 of 301 with model ConstantNaive for Validation 2
420 - ConstantNaive with avg smape 30.97:
Model Number: 421 of 301 with model ConstantNaive for Validation 2
421 - ConstantNaive with avg smape 30.97:
Model Number: 422 of 301 with model ConstantNaive for Validation 2
422 - ConstantNaive with avg smape 30.97:
Model Number: 423 of 301 with model ConstantNaive for Validation 2
423 - ConstantNaive with avg smape 30.97:
Model Number: 424 of 301 with model SeasonalityMotif for Validation 2
424 - SeasonalityMotif with avg smape 10.34:
Model Number: 425 of 301 with model FBProphet for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

425 - FBProphet with avg smape 23.82:
Model Number: 426 of 301 with model FBProphet for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

426 - FBProphet with avg smape 35.69:
Model Number: 427 of 301 with model ConstantNaive for Validation 2
427 - ConstantNaive with avg smape 31.38:
Model Number: 428 of 301 with model ConstantNaive for Validation 2
428 - ConstantNaive with avg smape 31.38:
Model Number: 429 of 301 with model ConstantNaive for Validation 2
429 - ConstantNaive with avg smape 31.38:
Model Number: 430 of 301 with model SeasonalityMotif for Validation 2
430 - SeasonalityMotif with avg smape 2.99:
Model Number: 431 of 301 with model ConstantNaive for Validation 2
431 - ConstantNaive with avg smape 31.36:
Model Number: 432 of 301 with model ConstantNaive for Validation 2
432 - ConstantNaive with avg smape 31.36:
Model Number: 433 of 301 with model ConstantNaive for Validation 2
433 - ConstantNaive with avg smape 31.36:
Model Number: 434 of 301 with model SeasonalityMotif for Validation 2
434 - SeasonalityMotif with avg smape 13.25:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 435 of 301 with model FBProphet for Validation 2
435 - FBProphet with avg smape 7.99:
Model Number: 436 of 301 with model SeasonalityMotif for Validation 2
436 - SeasonalityMotif with avg smape 51.39:
Model Number: 437 of 301 with model FBProphet for Validation 2
437 - FBProphet with avg smape 61.9:
Model Number: 438 of 301 with model FBProphet for Validation 2
📈 438 - FBProphet with avg smape 2.76:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 439 of 301 with model ETS for Validation 2
439 - ETS with avg smape 52.63:
Model Number: 440 of 301 with model SeasonalityMotif for Validation 2
440 - SeasonalityMotif with avg smape 34.53:
Model Number: 441 of 301 with model SeasonalityMotif for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

441 - SeasonalityMotif with avg smape 16.24:
Model Number: 442 of 301 with model SeasonalityMotif for Validation 2
442 - SeasonalityMotif with avg smape 16.93:
Model Number: 443 of 301 with model FBProphet for Validation 2
No anomalies detected.

13:40:59 - cmdstanpy - ERROR - Chain [1] error: error during processing Operation not permitted

443 - FBProphet with avg smape 56.28:
Model Number: 444 of 301 with model FBProphet for Validation 2
No anomalies detected.
444 - FBProphet with avg smape 48.59:
Model Number: 445 of 301 with model ETS for Validation 2
445 - ETS with avg smape 45.93:
Model Number: 446 of 301 with model ETS for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

446 - ETS with avg smape 45.96:
Model Number: 447 of 301 with model FBProphet for Validation 2
447 - FBProphet with avg smape 24.33:
Model Number: 448 of 301 with model FFT for Validation 2
448 - FFT with avg smape 47.43:
Model Number: 449 of 301 with model SeasonalityMotif for Validation 2
449 - SeasonalityMotif with avg smape 11.94:
Model Number: 450 of 301 with model FFT for Validation 2
450 - FFT with avg smape 43.04:
Model Number: 451 of 301 with model GLM for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

451 - GLM with avg smape 39.76:
Model Number: 452 of 301 with model GLM for Validation 2
452 - GLM with avg smape 40.8:
Model Number: 453 of 301 with model FFT for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

453 - FFT with avg smape 46.59:
Model Number: 454 of 301 with model GLM for Validation 2
454 - GLM with avg smape 36.68:
Model Number: 455 of 301 with model GLM for Validation 2
455 - GLM with avg smape 3.62:
Model Number: 456 of 301 with model GLM for Validation 2
📈 456 - GLM with avg smape 2.73:
Model Number: 457 of 301 with model SeasonalNaive for Validation 2
457 - SeasonalNaive with avg smape 10.82:
Model Number: 458 of 301 with model SeasonalNaive for Validation 2
458 - SeasonalNaive with avg smape 10.82:

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 459 of 301 with model SeasonalNaive for Validation 2
459 - SeasonalNaive with avg smape 17.22:
Model Number: 460 of 301 with model GLM for Validation 2
460 - GLM with avg smape 33.5:
Model Number: 461 of 301 with model GLM for Validation 2
461 - GLM with avg smape 33.5:
Model Number: 462 of 301 with model GLM for Validation 2
462 - GLM with avg smape 33.5:
Model Number: 463 of 301 with model GLM for Validation 2
463 - GLM with avg smape 32.92:
Model Number: 464 of 301 with model SeasonalNaive for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

464 - SeasonalNaive with avg smape 8.45:
Model Number: 465 of 301 with model GLM for Validation 2

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

465 - GLM with avg smape 15.78:
Model Number: 466 of 301 with model SeasonalNaive for Validation 2
466 - SeasonalNaive with avg smape 13.77:
Model Number: 467 of 301 with model SeasonalNaive for Validation 2
467 - SeasonalNaive with avg smape 10.0:
Model Number: 468 of 301 with model GLM for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

468 - GLM with avg smape 2.99:
Model Number: 469 of 301 with model SeasonalNaive for Validation 2
469 - SeasonalNaive with avg smape 5.48:
Model Number: 470 of 301 with model SeasonalNaive for Validation 2
470 - SeasonalNaive with avg smape 5.04:
Model Number: 471 of 301 with model SeasonalNaive for Validation 2
471 - SeasonalNaive with avg smape 5.04:
Model Number: 472 of 301 with model SeasonalNaive for Validation 2
472 - SeasonalNaive with avg smape 8.39:
Model Number: 473 of 301 with model SeasonalNaive for Validation 2
473 - SeasonalNaive with avg smape 2.99:
Model Number: 474 of 301 with model SeasonalNaive for Validation 2
474 - SeasonalNaive with avg smape 5.28:
Model Number: 475 of 301 with model SeasonalNaive for Validation 2
475 - SeasonalNaive with avg smape 9.95:
Model Number: 476 of 301 with model SeasonalNaive for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

476 - SeasonalNaive with avg smape 5.34:
Model Number: 477 of 301 with model SeasonalNaive for Validation 2
477 - SeasonalNaive with avg smape 13.71:
Model Number: 478 of 301 with model FFT for Validation 2
478 - FFT with avg smape 15.91:
Model Number: 479 of 301 with model FFT for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

479 - FFT with avg smape 13.92:
Model Number: 480 of 301 with model SeasonalNaive for Validation 2
480 - SeasonalNaive with avg smape 12.04:
Model Number: 481 of 301 with model FFT for Validation 2
481 - FFT with avg smape 6.8:
Model Number: 482 of 301 with model GLM for Validation 2
482 - GLM with avg smape 7.14:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 483 of 301 with model RRVAR for Validation 2
483 - RRVAR with avg smape 2.91:
Model Number: 484 of 301 with model RRVAR for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

484 - RRVAR with avg smape 2.91:
Model Number: 485 of 301 with model GLM for Validation 2
485 - GLM with avg smape 66.55:
Model Number: 486 of 301 with model WindowRegression for Validation 2
486 - WindowRegression with avg smape 38.74:
Model Number: 487 of 301 with model GLM for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

487 - GLM with avg smape 3.02:
Model Number: 488 of 301 with model WindowRegression for Validation 2
488 - WindowRegression with avg smape 32.98:
Model Number: 489 of 301 with model FFT for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

489 - FFT with avg smape 21.37:
Model Number: 490 of 301 with model FFT for Validation 2
490 - FFT with avg smape 3.17:
Model Number: 491 of 301 with model FFT for Validation 2
491 - FFT with avg smape 3.17:
Model Number: 492 of 301 with model GLM for Validation 2
492 - GLM with avg smape 71.81:
Model Number: 493 of 301 with model FFT for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.66384e-25): result may not be accurate.

493 - FFT with avg smape 3.15:
Model Number: 494 of 301 with model GLM for Validation 2
494 - GLM with avg smape 2.99:
Model Number: 495 of 301 with model FFT for Validation 2
495 - FFT with avg smape 2.91:
Model Number: 496 of 301 with model FFT for Validation 2
496 - FFT with avg smape 2.75:
Model Number: 497 of 301 with model RRVAR for Validation 2
497 - RRVAR with avg smape 3.21:
Model Number: 498 of 301 with model RRVAR for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

498 - RRVAR with avg smape 3.21:
Model Number: 499 of 301 with model RRVAR for Validation 2
499 - RRVAR with avg smape 3.21:
Model Number: 500 of 301 with model RRVAR for Validation 2
500 - RRVAR with avg smape 7.93:
Model Number: 501 of 301 with model FFT for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

501 - FFT with avg smape 4.39:
Model Number: 502 of 301 with model FFT for Validation 2
502 - FFT with avg smape 4.19:
Model Number: 503 of 301 with model FFT for Validation 2
503 - FFT with avg smape 4.12:
Model Number: 504 of 301 with model RRVAR for Validation 2
504 - RRVAR with avg smape 3.61:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 505 of 301 with model WindowRegression for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.66384e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

505 - WindowRegression with avg smape 34.44:
Model Number: 506 of 301 with model RRVAR for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

506 - RRVAR with avg smape 3.69:
Model Number: 507 of 301 with model FFT for Validation 2
507 - FFT with avg smape 3.87:
Model Number: 508 of 301 with model RRVAR for Validation 2

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

508 - RRVAR with avg smape 3.69:
Model Number: 509 of 301 with model RRVAR for Validation 2
509 - RRVAR with avg smape 3.74:

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Validation Round: 3
Model Number: 1 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

📈 1 - Ensemble with avg smape 8.86:
📈 2 - Ensemble with avg smape 8.61:
📈 3 - Ensemble with avg smape 4.31:
4 - Ensemble with avg smape 10.4:
5 - Ensemble with avg smape 23.41:
6 - Ensemble with avg smape 22.52:
7 - Ensemble with avg smape 11.77:
8 - Ensemble with avg smape 19.35:
9 - Ensemble with avg smape 8.86:
10 - Ensemble with avg smape 21.99:
11 - Ensemble with avg smape 5.48:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

12 - Ensemble with avg smape 8.87:
13 - Ensemble with avg smape 9.94:
14 - Ensemble with avg smape 10.05:
Model Number: 15 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

15 - Ensemble with avg smape 8.86:
16 - Ensemble with avg smape 8.61:
17 - Ensemble with avg smape 4.31:
18 - Ensemble with avg smape 10.4:
19 - Ensemble with avg smape 23.41:
20 - Ensemble with avg smape 22.52:
21 - Ensemble with avg smape 11.77:
22 - Ensemble with avg smape 19.35:
23 - Ensemble with avg smape 8.86:
24 - Ensemble with avg smape 21.99:
25 - Ensemble with avg smape 5.48:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

26 - Ensemble with avg smape 8.87:
27 - Ensemble with avg smape 9.94:
28 - Ensemble with avg smape 10.05:
Model Number: 29 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

29 - Ensemble with avg smape 8.86:
30 - Ensemble with avg smape 8.61:
31 - Ensemble with avg smape 4.31:
32 - Ensemble with avg smape 10.4:
33 - Ensemble with avg smape 23.41:
34 - Ensemble with avg smape 22.52:
35 - Ensemble with avg smape 11.77:
36 - Ensemble with avg smape 19.35:
37 - Ensemble with avg smape 8.86:
38 - Ensemble with avg smape 21.99:
39 - Ensemble with avg smape 5.48:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

40 - Ensemble with avg smape 8.87:
41 - Ensemble with avg smape 9.94:
42 - Ensemble with avg smape 10.05:
Model Number: 43 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

43 - Ensemble with avg smape 8.86:
44 - Ensemble with avg smape 8.61:
45 - Ensemble with avg smape 4.31:
46 - Ensemble with avg smape 10.4:
47 - Ensemble with avg smape 23.41:
48 - Ensemble with avg smape 22.52:
49 - Ensemble with avg smape 11.77:
50 - Ensemble with avg smape 19.35:
51 - Ensemble with avg smape 8.86:
52 - Ensemble with avg smape 21.99:
53 - Ensemble with avg smape 5.48:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

54 - Ensemble with avg smape 8.87:
55 - Ensemble with avg smape 9.94:
56 - Ensemble with avg smape 10.05:
Model Number: 57 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

57 - Ensemble with avg smape 8.86:
58 - Ensemble with avg smape 8.61:
59 - Ensemble with avg smape 4.31:
60 - Ensemble with avg smape 10.4:
61 - Ensemble with avg smape 23.41:
62 - Ensemble with avg smape 22.52:
63 - Ensemble with avg smape 11.77:
64 - Ensemble with avg smape 19.35:
65 - Ensemble with avg smape 8.86:
66 - Ensemble with avg smape 21.99:
67 - Ensemble with avg smape 5.48:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

68 - Ensemble with avg smape 8.87:
69 - Ensemble with avg smape 9.94:
70 - Ensemble with avg smape 10.05:
Model Number: 71 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

71 - Ensemble with avg smape 32.7:
72 - Ensemble with avg smape 32.67:
73 - Ensemble with avg smape 32.35:
74 - Ensemble with avg smape 27.23:
75 - Ensemble with avg smape 23.13:
76 - Ensemble with avg smape 22.52:
77 - Ensemble with avg smape 27.99:
78 - Ensemble with avg smape 32.66:
79 - Ensemble with avg smape 32.7:
80 - Ensemble with avg smape 31.04:
81 - Ensemble with avg smape 35.44:
82 - Ensemble with avg smape 32.73:
83 - Ensemble with avg smape 27.34:
84 - Ensemble with avg smape 24.09:
Model Number: 85 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

85 - Ensemble with avg smape 32.7:
86 - Ensemble with avg smape 32.67:
87 - Ensemble with avg smape 32.35:
88 - Ensemble with avg smape 27.23:
89 - Ensemble with avg smape 23.13:
90 - Ensemble with avg smape 22.52:
91 - Ensemble with avg smape 27.99:
92 - Ensemble with avg smape 32.66:
93 - Ensemble with avg smape 32.7:
94 - Ensemble with avg smape 31.04:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

95 - Ensemble with avg smape 35.44:
96 - Ensemble with avg smape 32.73:
97 - Ensemble with avg smape 27.34:
98 - Ensemble with avg smape 24.09:
Model Number: 99 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

99 - Ensemble with avg smape 32.7:
100 - Ensemble with avg smape 32.67:
101 - Ensemble with avg smape 32.35:
102 - Ensemble with avg smape 27.23:
103 - Ensemble with avg smape 23.13:
104 - Ensemble with avg smape 22.52:
105 - Ensemble with avg smape 27.99:
106 - Ensemble with avg smape 32.66:
107 - Ensemble with avg smape 32.7:
108 - Ensemble with avg smape 31.04:
109 - Ensemble with avg smape 35.44:
110 - Ensemble with avg smape 32.73:
111 - Ensemble with avg smape 27.34:
112 - Ensemble with avg smape 24.09:
Model Number: 113 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

113 - Ensemble with avg smape 19.75:
114 - Ensemble with avg smape 19.46:
115 - Ensemble with avg smape 11.57:
116 - Ensemble with avg smape 21.06:
117 - Ensemble with avg smape 23.53:
118 - Ensemble with avg smape 22.52:
119 - Ensemble with avg smape 20.66:
120 - Ensemble with avg smape 18.04:
121 - Ensemble with avg smape 19.75:
122 - Ensemble with avg smape 21.41:
123 - Ensemble with avg smape 6.59:
124 - Ensemble with avg smape 19.75:
125 - Ensemble with avg smape 4.65:
126 - Ensemble with avg smape 4.34:
Model Number: 127 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

127 - Ensemble with avg smape 19.75:
128 - Ensemble with avg smape 19.46:
129 - Ensemble with avg smape 11.66:
130 - Ensemble with avg smape 21.07:
131 - Ensemble with avg smape 23.54:
132 - Ensemble with avg smape 22.52:
133 - Ensemble with avg smape 20.66:
134 - Ensemble with avg smape 18.04:
135 - Ensemble with avg smape 19.75:
136 - Ensemble with avg smape 21.41:
137 - Ensemble with avg smape 6.67:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

138 - Ensemble with avg smape 19.75:
139 - Ensemble with avg smape 4.65:
140 - Ensemble with avg smape 4.33:
Model Number: 141 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

141 - Ensemble with avg smape 18.06:
142 - Ensemble with avg smape 17.82:
143 - Ensemble with avg smape 11.0:
144 - Ensemble with avg smape 19.37:
145 - Ensemble with avg smape 23.53:
146 - Ensemble with avg smape 22.52:
147 - Ensemble with avg smape 20.66:
148 - Ensemble with avg smape 18.04:
149 - Ensemble with avg smape 18.06:
150 - Ensemble with avg smape 21.41:
151 - Ensemble with avg smape 6.49:
152 - Ensemble with avg smape 18.06:
153 - Ensemble with avg smape 4.67:
154 - Ensemble with avg smape 4.38:
Model Number: 155 of 301 with model Cassandra for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

155 - Cassandra with avg smape 18.97:
Model Number: 156 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

156 - Ensemble with avg smape 70.81:
157 - Ensemble with avg smape 70.82:
158 - Ensemble with avg smape 71.85:
159 - Ensemble with avg smape 62.74:
160 - Ensemble with avg smape 22.88:
161 - Ensemble with avg smape 22.52:
162 - Ensemble with avg smape 32.26:
163 - Ensemble with avg smape 68.72:
164 - Ensemble with avg smape 60.2:
165 - Ensemble with avg smape 34.11:
166 - Ensemble with avg smape 74.03:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

167 - Ensemble with avg smape 70.89:
168 - Ensemble with avg smape 48.4:
169 - Ensemble with avg smape 40.08:
Model Number: 170 of 301 with model Cassandra for Validation 3
170 - Cassandra with avg smape 71.19:
Model Number: 171 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

171 - Ensemble with avg smape 70.81:
172 - Ensemble with avg smape 70.82:
173 - Ensemble with avg smape 71.85:
174 - Ensemble with avg smape 62.74:
175 - Ensemble with avg smape 22.88:
176 - Ensemble with avg smape 22.52:
177 - Ensemble with avg smape 32.26:
178 - Ensemble with avg smape 68.72:
179 - Ensemble with avg smape 60.2:
180 - Ensemble with avg smape 34.11:
181 - Ensemble with avg smape 74.03:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

182 - Ensemble with avg smape 70.89:
183 - Ensemble with avg smape 48.4:
184 - Ensemble with avg smape 40.08:
Model Number: 185 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

185 - Ensemble with avg smape 70.81:
186 - Ensemble with avg smape 70.82:
187 - Ensemble with avg smape 71.85:
188 - Ensemble with avg smape 62.74:
189 - Ensemble with avg smape 22.88:
190 - Ensemble with avg smape 22.52:
191 - Ensemble with avg smape 32.26:
192 - Ensemble with avg smape 68.72:
193 - Ensemble with avg smape 60.2:
194 - Ensemble with avg smape 34.11:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

195 - Ensemble with avg smape 74.03:
196 - Ensemble with avg smape 70.89:
197 - Ensemble with avg smape 48.4:
198 - Ensemble with avg smape 40.08:
Model Number: 199 of 301 with model Cassandra for Validation 3
199 - Cassandra with avg smape 81.16:
Model Number: 200 of 301 with model Cassandra for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

200 - Cassandra with avg smape 81.16:
Model Number: 201 of 301 with model Cassandra for Validation 3
201 - Cassandra with avg smape 15.29:
Model Number: 202 of 301 with model Cassandra for Validation 3

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

202 - Cassandra with avg smape 15.29:
Model Number: 203 of 301 with model Cassandra for Validation 3
203 - Cassandra with avg smape 15.29:
Model Number: 204 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

204 - Ensemble with avg smape 18.06:
205 - Ensemble with avg smape 17.82:
206 - Ensemble with avg smape 11.0:
207 - Ensemble with avg smape 19.37:
208 - Ensemble with avg smape 23.53:
209 - Ensemble with avg smape 22.52:
210 - Ensemble with avg smape 20.66:
211 - Ensemble with avg smape 18.04:
212 - Ensemble with avg smape 18.06:
213 - Ensemble with avg smape 21.41:
214 - Ensemble with avg smape 6.49:
215 - Ensemble with avg smape 18.06:
216 - Ensemble with avg smape 4.67:
217 - Ensemble with avg smape 4.38:
Model Number: 218 of 301 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

218 - Ensemble with avg smape 18.06:
219 - Ensemble with avg smape 17.82:
220 - Ensemble with avg smape 11.0:
221 - Ensemble with avg smape 19.37:
222 - Ensemble with avg smape 23.53:
223 - Ensemble with avg smape 22.52:
224 - Ensemble with avg smape 20.66:
225 - Ensemble with avg smape 18.04:
226 - Ensemble with avg smape 18.06:
227 - Ensemble with avg smape 21.41:
228 - Ensemble with avg smape 6.49:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

229 - Ensemble with avg smape 18.06:
230 - Ensemble with avg smape 4.67:
231 - Ensemble with avg smape 4.38:
Model Number: 232 of 301 with model Cassandra for Validation 3
232 - Cassandra with avg smape 15.29:
Model Number: 233 of 301 with model Cassandra for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

233 - Cassandra with avg smape 15.29:
Model Number: 234 of 301 with model Cassandra for Validation 3
234 - Cassandra with avg smape 15.29:
Model Number: 235 of 301 with model Cassandra for Validation 3

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

235 - Cassandra with avg smape 15.29:
Model Number: 236 of 301 with model Cassandra for Validation 3
236 - Cassandra with avg smape 72.12:
Model Number: 237 of 301 with model Cassandra for Validation 3

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

237 - Cassandra with avg smape 72.12:
Model Number: 238 of 301 with model Cassandra for Validation 3
238 - Cassandra with avg smape 14.69:
Model Number: 239 of 301 with model Cassandra for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

239 - Cassandra with avg smape 72.73:
Model Number: 240 of 301 with model Cassandra for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

240 - Cassandra with avg smape 72.73:
Model Number: 241 of 301 with model FBProphet for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

241 - FBProphet with avg smape 21.4:
Model Number: 242 of 301 with model AverageValueNaive for Validation 3
242 - AverageValueNaive with avg smape 13.61:
Model Number: 243 of 301 with model AverageValueNaive for Validation 3
243 - AverageValueNaive with avg smape 13.6:
Model Number: 244 of 301 with model AverageValueNaive for Validation 3
244 - AverageValueNaive with avg smape 13.58:
Model Number: 245 of 301 with model BasicLinearModel for Validation 3
245 - BasicLinearModel with avg smape 18.83:
Model Number: 246 of 301 with model AverageValueNaive for Validation 3

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

246 - AverageValueNaive with avg smape 13.54:
Model Number: 247 of 301 with model BasicLinearModel for Validation 3
247 - BasicLinearModel with avg smape 13.91:
Model Number: 248 of 301 with model AverageValueNaive for Validation 3
248 - AverageValueNaive with avg smape 13.64:
Model Number: 249 of 301 with model BasicLinearModel for Validation 3
249 - BasicLinearModel with avg smape 14.74:
Model Number: 250 of 301 with model BasicLinearModel for Validation 3
250 - BasicLinearModel with avg smape 14.74:
Model Number: 251 of 301 with model ARDL for Validation 3
251 - ARDL with avg smape 15.93:
Model Number: 252 of 301 with model ARDL for Validation 3
252 - ARDL with avg smape 15.93:
Model Number: 253 of 301 with model BasicLinearModel for Validation 3
253 - BasicLinearModel with avg smape 10.71:
Model Number: 254 of 301 with model BasicLinearModel for Validation 3
254 - BasicLinearModel with avg smape 10.19:
Model Number: 255 of 301 with model ARDL for Validation 3
255 - ARDL with avg smape 15.95:
Model Number: 256 of 301 with model ARDL for Validation 3
256 - ARDL with avg smape 16.0:
Model Number: 257 of 301 with model ARDL for Validation 3
257 - ARDL with avg smape 15.91:
Model Number: 258 of 301 with model ARDL for Validation 3
258 - ARDL with avg smape 15.85:
Model Number: 259 of 301 with model GLS for Validation 3
259 - GLS with avg smape 13.65:
Model Number: 260 of 301 with model GLS for Validation 3
260 - GLS with avg smape 13.65:
Model Number: 261 of 301 with model GLS for Validation 3
261 - GLS with avg smape 13.65:
Model Number: 262 of 301 with model GLS for Validation 3
262 - GLS with avg smape 13.65:
Model Number: 263 of 301 with model GLS for Validation 3
263 - GLS with avg smape 13.65:
Model Number: 264 of 301 with model GLS for Validation 3
264 - GLS with avg smape 13.65:
Model Number: 265 of 301 with model GLS for Validation 3
265 - GLS with avg smape 13.65:
Model Number: 266 of 301 with model BasicLinearModel for Validation 3
266 - BasicLinearModel with avg smape 10.69:
Model Number: 267 of 301 with model BasicLinearModel for Validation 3
267 - BasicLinearModel with avg smape 10.7:
Model Number: 268 of 301 with model ETS for Validation 3
268 - ETS with avg smape 11.49:
Model Number: 269 of 301 with model ETS for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

269 - ETS with avg smape 11.49:
Model Number: 270 of 301 with model GLS for Validation 3
270 - GLS with avg smape 13.68:
Model Number: 271 of 301 with model GLS for Validation 3
271 - GLS with avg smape 13.68:
Model Number: 272 of 301 with model GLS for Validation 3
272 - GLS with avg smape 13.68:
Model Number: 273 of 301 with model GLS for Validation 3
273 - GLS with avg smape 13.68:
Model Number: 274 of 301 with model ARDL for Validation 3
274 - ARDL with avg smape 95.08:
Model Number: 275 of 301 with model AverageValueNaive for Validation 3
275 - AverageValueNaive with avg smape 13.63:
Model Number: 276 of 301 with model GLS for Validation 3
276 - GLS with avg smape 11.66:

/usr/local/lib/python3.10/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

Model Number: 277 of 301 with model GLS for Validation 3
277 - GLS with avg smape 11.66:
Model Number: 278 of 301 with model GLS for Validation 3
278 - GLS with avg smape 11.65:
Model Number: 279 of 301 with model GLS for Validation 3
279 - GLS with avg smape 11.67:
Model Number: 280 of 301 with model GLS for Validation 3
280 - GLS with avg smape 11.67:
Model Number: 281 of 301 with model BasicLinearModel for Validation 3
281 - BasicLinearModel with avg smape 28.84:
Model Number: 282 of 301 with model AverageValueNaive for Validation 3
282 - AverageValueNaive with avg smape 13.49:
Model Number: 283 of 301 with model AverageValueNaive for Validation 3
283 - AverageValueNaive with avg smape 13.66:
Model Number: 284 of 301 with model AverageValueNaive for Validation 3
284 - AverageValueNaive with avg smape 13.66:
Model Number: 285 of 301 with model AverageValueNaive for Validation 3
285 - AverageValueNaive with avg smape 13.64:
Model Number: 286 of 301 with model AverageValueNaive for Validation 3
286 - AverageValueNaive with avg smape 13.64:
Model Number: 287 of 301 with model AverageValueNaive for Validation 3
287 - AverageValueNaive with avg smape 13.65:
Model Number: 288 of 301 with model AverageValueNaive for Validation 3
288 - AverageValueNaive with avg smape 13.63:
Model Number: 289 of 301 with model AverageValueNaive for Validation 3
289 - AverageValueNaive with avg smape 13.63:
Model Number: 290 of 301 with model AverageValueNaive for Validation 3
290 - AverageValueNaive with avg smape 82.09:
Model Number: 291 of 301 with model BasicLinearModel for Validation 3
291 - BasicLinearModel with avg smape 15.19:
Model Number: 292 of 301 with model AverageValueNaive for Validation 3
292 - AverageValueNaive with avg smape 13.66:
Model Number: 293 of 301 with model DatepartRegression for Validation 3
293 - DatepartRegression with avg smape 5.43:
Model Number: 294 of 301 with model LastValueNaive for Validation 3
294 - LastValueNaive with avg smape 11.51:
Model Number: 295 of 301 with model LastValueNaive for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.041e+00, tolerance: 1.171e-02

295 - LastValueNaive with avg smape 11.49:
Model Number: 296 of 301 with model LastValueNaive for Validation 3
296 - LastValueNaive with avg smape 11.49:
Model Number: 297 of 301 with model LastValueNaive for Validation 3
297 - LastValueNaive with avg smape 11.49:
Model Number: 298 of 301 with model LastValueNaive for Validation 3
298 - LastValueNaive with avg smape 11.49:
Model Number: 299 of 301 with model LastValueNaive for Validation 3
299 - LastValueNaive with avg smape 11.49:
Model Number: 300 of 301 with model LastValueNaive for Validation 3
300 - LastValueNaive with avg smape 11.49:
Model Number: 301 of 301 with model LastValueNaive for Validation 3
301 - LastValueNaive with avg smape 11.49:
Model Number: 302 of 301 with model LastValueNaive for Validation 3
302 - LastValueNaive with avg smape 11.49:
Model Number: 303 of 301 with model ARDL for Validation 3
303 - ARDL with avg smape 16.48:
Model Number: 304 of 301 with model LastValueNaive for Validation 3
304 - LastValueNaive with avg smape 12.36:
Model Number: 305 of 301 with model LastValueNaive for Validation 3
305 - LastValueNaive with avg smape 12.36:
Model Number: 306 of 301 with model LastValueNaive for Validation 3
306 - LastValueNaive with avg smape 12.36:
Model Number: 307 of 301 with model BasicLinearModel for Validation 3
307 - BasicLinearModel with avg smape 21.94:
Model Number: 308 of 301 with model BasicLinearModel for Validation 3
308 - BasicLinearModel with avg smape 21.49:
Model Number: 309 of 301 with model BasicLinearModel for Validation 3
309 - BasicLinearModel with avg smape 11.0:
Model Number: 310 of 301 with model BasicLinearModel for Validation 3
310 - BasicLinearModel with avg smape 17.84:
Model Number: 311 of 301 with model DatepartRegression for Validation 3
311 - DatepartRegression with avg smape 10.35:
Model Number: 312 of 301 with model BasicLinearModel for Validation 3
312 - BasicLinearModel with avg smape 25.35:
Model Number: 313 of 301 with model BasicLinearModel for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.827e+09, tolerance: 1.500e+06

313 - BasicLinearModel with avg smape 21.51:
Model Number: 314 of 301 with model DatepartRegression for Validation 3
314 - DatepartRegression with avg smape 13.29:
Model Number: 315 of 301 with model DatepartRegression for Validation 3
315 - DatepartRegression with avg smape 10.36:
Model Number: 316 of 301 with model DatepartRegression for Validation 3
316 - DatepartRegression with avg smape 10.36:
Model Number: 317 of 301 with model LastValueNaive for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.839e+09, tolerance: 1.504e+06

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.839e+09, tolerance: 1.504e+06

317 - LastValueNaive with avg smape 14.73:
Model Number: 318 of 301 with model ARDL for Validation 3
318 - ARDL with avg smape 14.23:
Model Number: 319 of 301 with model DatepartRegression for Validation 3
319 - DatepartRegression with avg smape 11.2:
Model Number: 320 of 301 with model DatepartRegression for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.612e-01, tolerance: 9.025e-03

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.847e-01, tolerance: 8.997e-03

320 - DatepartRegression with avg smape 11.18:
Model Number: 321 of 301 with model DatepartRegression for Validation 3
321 - DatepartRegression with avg smape 11.18:
Model Number: 322 of 301 with model DatepartRegression for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.847e-01, tolerance: 8.997e-03

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.126e+09, tolerance: 1.347e+06

322 - DatepartRegression with avg smape 10.43:
Model Number: 323 of 301 with model ETS for Validation 3
323 - ETS with avg smape 22.26:
Model Number: 324 of 301 with model ETS for Validation 3
324 - ETS with avg smape 22.26:
Model Number: 325 of 301 with model ARDL for Validation 3
325 - ARDL with avg smape 94.0:
Model Number: 326 of 301 with model DatepartRegression for Validation 3
326 - DatepartRegression with avg smape 10.43:
Model Number: 327 of 301 with model DatepartRegression for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.127e+09, tolerance: 1.347e+06

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.064e-01, tolerance: 9.244e-03

327 - DatepartRegression with avg smape 11.18:
Model Number: 328 of 301 with model UnivariateMotif for Validation 3
328 - UnivariateMotif with avg smape 23.01:
Model Number: 329 of 301 with model LastValueNaive for Validation 3
329 - LastValueNaive with avg smape 12.55:
Model Number: 330 of 301 with model LastValueNaive for Validation 3
330 - LastValueNaive with avg smape 12.55:
Model Number: 331 of 301 with model LastValueNaive for Validation 3
331 - LastValueNaive with avg smape 12.53:
Model Number: 332 of 301 with model DatepartRegression for Validation 3
Epoch 1/50

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

39/39 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - loss: 0.0509
Epoch 2/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0429
Epoch 3/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0428
Epoch 4/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0432
Epoch 5/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0429
Epoch 6/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0427
Epoch 7/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0426
Epoch 8/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0426
Epoch 9/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0424
Epoch 10/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0421
Epoch 11/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0417
Epoch 12/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0413
Epoch 13/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0413
Epoch 14/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0412
Epoch 15/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0405
Epoch 16/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0409
Epoch 17/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0405
Epoch 18/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0403
Epoch 19/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0392
Epoch 20/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0387
Epoch 21/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0390
Epoch 22/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0389
Epoch 23/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0384
Epoch 24/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0373
Epoch 25/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0382
Epoch 26/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0388
Epoch 27/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0375
Epoch 28/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0381
Epoch 29/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0367
Epoch 30/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0375
Epoch 31/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0366
Epoch 32/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0381
Epoch 33/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0375
Epoch 34/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0368
Epoch 35/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0373
Epoch 36/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0366
Epoch 37/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0365
Epoch 38/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0368
Epoch 39/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0374
Epoch 40/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0365
Epoch 41/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0365
Epoch 42/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0367
Epoch 43/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0360
Epoch 44/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0366
Epoch 45/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0352
Epoch 46/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0361
Epoch 47/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0353
Epoch 48/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0354
Epoch 49/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0349
Epoch 50/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0345
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 404ms/step
332 - DatepartRegression with avg smape 13.89:
Model Number: 333 of 301 with model SeasonalityMotif for Validation 3
333 - SeasonalityMotif with avg smape 22.37:
Model Number: 334 of 301 with model DatepartRegression for Validation 3
334 - DatepartRegression with avg smape 10.83:
Model Number: 335 of 301 with model ARDL for Validation 3
335 - ARDL with avg smape 27.49:
Model Number: 336 of 301 with model FBProphet for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

336 - FBProphet with avg smape 12.58:
Model Number: 337 of 301 with model ARDL for Validation 3
337 - ARDL with avg smape 19.84:
Model Number: 338 of 301 with model MetricMotif for Validation 3
338 - MetricMotif with avg smape 27.04:
Model Number: 339 of 301 with model MetricMotif for Validation 3
339 - MetricMotif with avg smape 27.04:
Model Number: 340 of 301 with model MetricMotif for Validation 3
340 - MetricMotif with avg smape 27.04:
Model Number: 341 of 301 with model MetricMotif for Validation 3
341 - MetricMotif with avg smape 27.02:
Model Number: 342 of 301 with model UnivariateMotif for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

342 - UnivariateMotif with avg smape 17.26:
Model Number: 343 of 301 with model ETS for Validation 3
343 - ETS with avg smape 114.18:
Model Number: 344 of 301 with model MetricMotif for Validation 3
344 - MetricMotif with avg smape 12.49:
Model Number: 345 of 301 with model ETS for Validation 3
345 - ETS with avg smape 19.95:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 346 of 301 with model ARDL for Validation 3
346 - ARDL with avg smape 19.82:
Model Number: 347 of 301 with model MetricMotif for Validation 3
347 - MetricMotif with avg smape 12.7:
Model Number: 348 of 301 with model MetricMotif for Validation 3
348 - MetricMotif with avg smape 32.51:
Model Number: 349 of 301 with model UnivariateMotif for Validation 3
349 - UnivariateMotif with avg smape 18.34:
Model Number: 350 of 301 with model MetricMotif for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

350 - MetricMotif with avg smape 13.77:
Model Number: 351 of 301 with model FBProphet for Validation 3
351 - FBProphet with avg smape 23.56:
Model Number: 352 of 301 with model SectionalMotif for Validation 3
352 - SectionalMotif with avg smape 26.69:
Model Number: 353 of 301 with model MetricMotif for Validation 3
353 - MetricMotif with avg smape 26.26:
Model Number: 354 of 301 with model MetricMotif for Validation 3
354 - MetricMotif with avg smape 26.26:
Model Number: 355 of 301 with model ETS for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

355 - ETS with avg smape 17.62:
Model Number: 356 of 301 with model ConstantNaive for Validation 3
356 - ConstantNaive with avg smape 13.65:
Model Number: 357 of 301 with model ConstantNaive for Validation 3
357 - ConstantNaive with avg smape 13.65:
Model Number: 358 of 301 with model SectionalMotif for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.617e+09, tolerance: 1.662e+06

358 - SectionalMotif with avg smape 33.07:
Model Number: 359 of 301 with model DatepartRegression for Validation 3
359 - DatepartRegression with avg smape 16.6:
Model Number: 360 of 301 with model SectionalMotif for Validation 3
360 - SectionalMotif with avg smape 28.64:
Model Number: 361 of 301 with model SectionalMotif for Validation 3
361 - SectionalMotif with avg smape 29.86:
Model Number: 362 of 301 with model MetricMotif for Validation 3
362 - MetricMotif with avg smape 26.25:
Model Number: 363 of 301 with model SectionalMotif for Validation 3
363 - SectionalMotif with avg smape 28.1:
Model Number: 364 of 301 with model MetricMotif for Validation 3
364 - MetricMotif with avg smape 12.42:
Model Number: 365 of 301 with model MetricMotif for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

365 - MetricMotif with avg smape 15.0:
Model Number: 366 of 301 with model UnivariateMotif for Validation 3
366 - UnivariateMotif with avg smape 31.54:
Model Number: 367 of 301 with model SectionalMotif for Validation 3
367 - SectionalMotif with avg smape 27.87:
Model Number: 368 of 301 with model ARDL for Validation 3

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

368 - ARDL with avg smape 93.65:
Model Number: 369 of 301 with model MetricMotif for Validation 3
369 - MetricMotif with avg smape 25.89:
Model Number: 370 of 301 with model MetricMotif for Validation 3
370 - MetricMotif with avg smape 25.89:
Model Number: 371 of 301 with model MetricMotif for Validation 3
371 - MetricMotif with avg smape 33.8:
Model Number: 372 of 301 with model SectionalMotif for Validation 3
372 - SectionalMotif with avg smape 26.19:
Model Number: 373 of 301 with model UnivariateMotif for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

373 - UnivariateMotif with avg smape 24.52:
Model Number: 374 of 301 with model UnivariateMotif for Validation 3
374 - UnivariateMotif with avg smape 31.97:
Model Number: 375 of 301 with model UnivariateMotif for Validation 3
375 - UnivariateMotif with avg smape 24.63:
Model Number: 376 of 301 with model UnivariateMotif for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

376 - UnivariateMotif with avg smape 31.97:
Model Number: 377 of 301 with model UnivariateMotif for Validation 3
377 - UnivariateMotif with avg smape 31.97:
Model Number: 378 of 301 with model SectionalMotif for Validation 3
378 - SectionalMotif with avg smape 26.77:
Model Number: 379 of 301 with model UnivariateMotif for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

379 - UnivariateMotif with avg smape 33.91:
Model Number: 380 of 301 with model UnivariateMotif for Validation 3
380 - UnivariateMotif with avg smape 26.15:
Model Number: 381 of 301 with model SectionalMotif for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

381 - SectionalMotif with avg smape 28.17:
Model Number: 382 of 301 with model UnivariateMotif for Validation 3
382 - UnivariateMotif with avg smape 23.3:
Model Number: 383 of 301 with model FBProphet for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

383 - FBProphet with avg smape 12.72:
Model Number: 384 of 301 with model SectionalMotif for Validation 3
384 - SectionalMotif with avg smape 32.97:
Model Number: 385 of 301 with model SectionalMotif for Validation 3
385 - SectionalMotif with avg smape 32.97:
Model Number: 386 of 301 with model SectionalMotif for Validation 3
386 - SectionalMotif with avg smape 31.92:
Model Number: 387 of 301 with model UnivariateMotif for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

387 - UnivariateMotif with avg smape 34.28:
Model Number: 388 of 301 with model SectionalMotif for Validation 3
388 - SectionalMotif with avg smape 27.26:
Model Number: 389 of 301 with model SectionalMotif for Validation 3
389 - SectionalMotif with avg smape 26.39:
Model Number: 390 of 301 with model UnivariateMotif for Validation 3
390 - UnivariateMotif with avg smape 26.01:
Model Number: 391 of 301 with model SectionalMotif for Validation 3
391 - SectionalMotif with avg smape 28.13:
Model Number: 392 of 301 with model ETS for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

392 - ETS with avg smape 19.44:
Model Number: 393 of 301 with model UnivariateMotif for Validation 3
393 - UnivariateMotif with avg smape 26.41:
Model Number: 394 of 301 with model SectionalMotif for Validation 3
394 - SectionalMotif with avg smape 26.25:
Model Number: 395 of 301 with model UnivariateMotif for Validation 3
395 - UnivariateMotif with avg smape 32.01:
Model Number: 396 of 301 with model FBProphet for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

396 - FBProphet with avg smape 23.61:
Model Number: 397 of 301 with model FBProphet for Validation 3
No anomalies detected.
397 - FBProphet with avg smape 83.44:
Model Number: 398 of 301 with model DatepartRegression for Validation 3
398 - DatepartRegression with avg smape 82.15:
Model Number: 399 of 301 with model DatepartRegression for Validation 3
399 - DatepartRegression with avg smape 16.37:
Model Number: 400 of 301 with model ETS for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.167e+09, tolerance: 1.358e+06

400 - ETS with avg smape 83.12:
Model Number: 401 of 301 with model ETS for Validation 3
401 - ETS with avg smape 83.12:
Model Number: 402 of 301 with model FBProphet for Validation 3
402 - FBProphet with avg smape 12.73:
Model Number: 403 of 301 with model ETS for Validation 3
403 - ETS with avg smape 19.44:
Model Number: 404 of 301 with model ETS for Validation 3
404 - ETS with avg smape 19.44:
Model Number: 405 of 301 with model ETS for Validation 3
405 - ETS with avg smape 19.44:
Model Number: 406 of 301 with model ARDL for Validation 3
406 - ARDL with avg smape 74.23:
Model Number: 407 of 301 with model FBProphet for Validation 3
407 - FBProphet with avg smape 26.01:
Model Number: 408 of 301 with model ARDL for Validation 3
408 - ARDL with avg smape 12.29:
Model Number: 409 of 301 with model SeasonalityMotif for Validation 3
409 - SeasonalityMotif with avg smape 25.33:
Model Number: 410 of 301 with model SeasonalityMotif for Validation 3
410 - SeasonalityMotif with avg smape 25.33:
Model Number: 411 of 301 with model SeasonalityMotif for Validation 3
411 - SeasonalityMotif with avg smape 25.3:
Model Number: 412 of 301 with model SeasonalityMotif for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

412 - SeasonalityMotif with avg smape 25.3:
Model Number: 413 of 301 with model SeasonalityMotif for Validation 3
413 - SeasonalityMotif with avg smape 31.4:
Model Number: 414 of 301 with model SeasonalityMotif for Validation 3
414 - SeasonalityMotif with avg smape 31.36:
Model Number: 415 of 301 with model SeasonalityMotif for Validation 3
415 - SeasonalityMotif with avg smape 31.43:
Model Number: 416 of 301 with model ConstantNaive for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

416 - ConstantNaive with avg smape 31.83:
Model Number: 417 of 301 with model ConstantNaive for Validation 3
417 - ConstantNaive with avg smape 31.83:
Model Number: 418 of 301 with model ConstantNaive for Validation 3
418 - ConstantNaive with avg smape 31.83:
Model Number: 419 of 301 with model ConstantNaive for Validation 3
419 - ConstantNaive with avg smape 31.83:
Model Number: 420 of 301 with model ConstantNaive for Validation 3
420 - ConstantNaive with avg smape 31.83:
Model Number: 421 of 301 with model ConstantNaive for Validation 3
421 - ConstantNaive with avg smape 31.83:
Model Number: 422 of 301 with model ConstantNaive for Validation 3
422 - ConstantNaive with avg smape 31.83:
Model Number: 423 of 301 with model ConstantNaive for Validation 3
423 - ConstantNaive with avg smape 31.83:
Model Number: 424 of 301 with model SeasonalityMotif for Validation 3
424 - SeasonalityMotif with avg smape 31.28:
Model Number: 425 of 301 with model FBProphet for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

425 - FBProphet with avg smape 28.36:
Model Number: 426 of 301 with model FBProphet for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

426 - FBProphet with avg smape 16.53:
Model Number: 427 of 301 with model ConstantNaive for Validation 3
427 - ConstantNaive with avg smape 33.28:
Model Number: 428 of 301 with model ConstantNaive for Validation 3
428 - ConstantNaive with avg smape 33.28:
Model Number: 429 of 301 with model ConstantNaive for Validation 3
429 - ConstantNaive with avg smape 33.28:
Model Number: 430 of 301 with model SeasonalityMotif for Validation 3
430 - SeasonalityMotif with avg smape 23.54:
Model Number: 431 of 301 with model ConstantNaive for Validation 3
431 - ConstantNaive with avg smape 33.26:
Model Number: 432 of 301 with model ConstantNaive for Validation 3
432 - ConstantNaive with avg smape 33.26:
Model Number: 433 of 301 with model ConstantNaive for Validation 3
433 - ConstantNaive with avg smape 33.26:
Model Number: 434 of 301 with model SeasonalityMotif for Validation 3
434 - SeasonalityMotif with avg smape 33.36:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 435 of 301 with model FBProphet for Validation 3
435 - FBProphet with avg smape 18.58:
Model Number: 436 of 301 with model SeasonalityMotif for Validation 3
436 - SeasonalityMotif with avg smape 19.59:
Model Number: 437 of 301 with model FBProphet for Validation 3
437 - FBProphet with avg smape 71.9:
Model Number: 438 of 301 with model FBProphet for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

438 - FBProphet with avg smape 18.24:
Model Number: 439 of 301 with model ETS for Validation 3
439 - ETS with avg smape 54.91:
Model Number: 440 of 301 with model SeasonalityMotif for Validation 3
440 - SeasonalityMotif with avg smape 34.26:
Model Number: 441 of 301 with model SeasonalityMotif for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

441 - SeasonalityMotif with avg smape 26.93:
Model Number: 442 of 301 with model SeasonalityMotif for Validation 3
442 - SeasonalityMotif with avg smape 27.54:
Model Number: 443 of 301 with model FBProphet for Validation 3
No anomalies detected.

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

13:42:33 - cmdstanpy - ERROR - Chain [1] error: error during processing Operation not permitted

443 - FBProphet with avg smape 86.08:
Model Number: 444 of 301 with model FBProphet for Validation 3
No anomalies detected.
444 - FBProphet with avg smape 18.1:
Model Number: 445 of 301 with model ETS for Validation 3
445 - ETS with avg smape 15.86:
Model Number: 446 of 301 with model ETS for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

446 - ETS with avg smape 16.2:
Model Number: 447 of 301 with model FBProphet for Validation 3
447 - FBProphet with avg smape 28.43:
Model Number: 448 of 301 with model FFT for Validation 3
448 - FFT with avg smape 15.72:
Model Number: 449 of 301 with model SeasonalityMotif for Validation 3
449 - SeasonalityMotif with avg smape 20.69:
Model Number: 450 of 301 with model FFT for Validation 3
450 - FFT with avg smape 14.27:
Model Number: 451 of 301 with model GLM for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

451 - GLM with avg smape 30.85:
Model Number: 452 of 301 with model GLM for Validation 3
452 - GLM with avg smape 31.12:
Model Number: 453 of 301 with model FFT for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

453 - FFT with avg smape 16.63:
Model Number: 454 of 301 with model GLM for Validation 3
454 - GLM with avg smape 28.91:
Model Number: 455 of 301 with model GLM for Validation 3
455 - GLM with avg smape 22.18:
Model Number: 456 of 301 with model GLM for Validation 3
456 - GLM with avg smape 18.74:
Model Number: 457 of 301 with model SeasonalNaive for Validation 3

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

457 - SeasonalNaive with avg smape 26.63:
Model Number: 458 of 301 with model SeasonalNaive for Validation 3
458 - SeasonalNaive with avg smape 26.63:
Model Number: 459 of 301 with model SeasonalNaive for Validation 3
459 - SeasonalNaive with avg smape 26.7:
Model Number: 460 of 301 with model GLM for Validation 3
460 - GLM with avg smape 22.67:
Model Number: 461 of 301 with model GLM for Validation 3
461 - GLM with avg smape 22.67:
Model Number: 462 of 301 with model GLM for Validation 3
462 - GLM with avg smape 22.67:
Model Number: 463 of 301 with model GLM for Validation 3
463 - GLM with avg smape 29.68:
Model Number: 464 of 301 with model SeasonalNaive for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

464 - SeasonalNaive with avg smape 25.11:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

Model Number: 465 of 301 with model GLM for Validation 3
465 - GLM with avg smape 20.53:
Model Number: 466 of 301 with model SeasonalNaive for Validation 3
466 - SeasonalNaive with avg smape 25.29:
Model Number: 467 of 301 with model SeasonalNaive for Validation 3
467 - SeasonalNaive with avg smape 15.89:
Model Number: 468 of 301 with model GLM for Validation 3

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

468 - GLM with avg smape 20.66:
Model Number: 469 of 301 with model SeasonalNaive for Validation 3
469 - SeasonalNaive with avg smape 26.63:
Model Number: 470 of 301 with model SeasonalNaive for Validation 3
470 - SeasonalNaive with avg smape 23.45:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 471 of 301 with model SeasonalNaive for Validation 3
471 - SeasonalNaive with avg smape 23.45:
Model Number: 472 of 301 with model SeasonalNaive for Validation 3
472 - SeasonalNaive with avg smape 25.14:
Model Number: 473 of 301 with model SeasonalNaive for Validation 3

/usr/local/lib/python3.10/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

473 - SeasonalNaive with avg smape 20.49:
Model Number: 474 of 301 with model SeasonalNaive for Validation 3
474 - SeasonalNaive with avg smape 26.55:
Model Number: 475 of 301 with model SeasonalNaive for Validation 3
475 - SeasonalNaive with avg smape 26.59:
Model Number: 476 of 301 with model SeasonalNaive for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

476 - SeasonalNaive with avg smape 23.41:
Model Number: 477 of 301 with model SeasonalNaive for Validation 3
477 - SeasonalNaive with avg smape 26.76:
Model Number: 478 of 301 with model FFT for Validation 3
478 - FFT with avg smape 13.29:
Model Number: 479 of 301 with model FFT for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

479 - FFT with avg smape 15.39:
Model Number: 480 of 301 with model SeasonalNaive for Validation 3
480 - SeasonalNaive with avg smape 26.54:
Model Number: 481 of 301 with model FFT for Validation 3
481 - FFT with avg smape 14.29:
Model Number: 482 of 301 with model GLM for Validation 3
482 - GLM with avg smape 16.93:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 483 of 301 with model RRVAR for Validation 3
483 - RRVAR with avg smape 21.37:
Model Number: 484 of 301 with model RRVAR for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

484 - RRVAR with avg smape 21.37:
Model Number: 485 of 301 with model GLM for Validation 3
485 - GLM with avg smape 19.66:
Model Number: 486 of 301 with model WindowRegression for Validation 3
486 - WindowRegression with avg smape 26.12:
Model Number: 487 of 301 with model GLM for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

487 - GLM with avg smape 19.67:
Model Number: 488 of 301 with model WindowRegression for Validation 3
488 - WindowRegression with avg smape 26.05:
Model Number: 489 of 301 with model FFT for Validation 3
489 - FFT with avg smape 21.03:
Model Number: 490 of 301 with model FFT for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

490 - FFT with avg smape 16.42:
Model Number: 491 of 301 with model FFT for Validation 3
491 - FFT with avg smape 16.42:
Model Number: 492 of 301 with model GLM for Validation 3
492 - GLM with avg smape 20.66:
Model Number: 493 of 301 with model FFT for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.7456e-25): result may not be accurate.

493 - FFT with avg smape 16.55:
Model Number: 494 of 301 with model GLM for Validation 3
494 - GLM with avg smape 20.66:
Model Number: 495 of 301 with model FFT for Validation 3
495 - FFT with avg smape 15.18:
Model Number: 496 of 301 with model FFT for Validation 3
496 - FFT with avg smape 15.31:
Model Number: 497 of 301 with model RRVAR for Validation 3
497 - RRVAR with avg smape 21.62:
Model Number: 498 of 301 with model RRVAR for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

498 - RRVAR with avg smape 21.62:
Model Number: 499 of 301 with model RRVAR for Validation 3
499 - RRVAR with avg smape 21.62:
Model Number: 500 of 301 with model RRVAR for Validation 3
500 - RRVAR with avg smape 20.94:
Model Number: 501 of 301 with model FFT for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/scipy/stats/_distn_infrastructure.py:2157: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

501 - FFT with avg smape 18.52:
Model Number: 502 of 301 with model FFT for Validation 3
502 - FFT with avg smape 12.95:
Model Number: 503 of 301 with model FFT for Validation 3
503 - FFT with avg smape 24.97:
Model Number: 504 of 301 with model RRVAR for Validation 3
504 - RRVAR with avg smape 20.29:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

Model Number: 505 of 301 with model WindowRegression for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning:

Ill-conditioned matrix (rcond=1.7456e-25): result may not be accurate.

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

505 - WindowRegression with avg smape 37.37:
Model Number: 506 of 301 with model RRVAR for Validation 3
506 - RRVAR with avg smape 19.06:
Model Number: 507 of 301 with model FFT for Validation 3
507 - FFT with avg smape 15.98:
Model Number: 508 of 301 with model RRVAR for Validation 3

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

508 - RRVAR with avg smape 19.06:
Model Number: 509 of 301 with model RRVAR for Validation 3
509 - RRVAR with avg smape 18.98:

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.10/dist-packages/autots/evaluator/auto_model.py:3041: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 3532 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.633e+00, tolerance: 1.547e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 3546 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.633e+00, tolerance: 1.547e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 3560 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.633e+00, tolerance: 1.547e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 3574 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.633e+00, tolerance: 1.547e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 3588 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.633e+00, tolerance: 1.547e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 3602 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.633e+00, tolerance: 1.547e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 3616 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.633e+00, tolerance: 1.547e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 3630 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.633e+00, tolerance: 1.547e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Model Number: 3644 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.633e+00, tolerance: 1.547e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

Validation Round: 1
Model Number: 1 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.344e+00, tolerance: 1.569e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

📈 1 - Ensemble with avg smape 2.33:
📈 2 - Ensemble with avg smape 2.28:
3 - Ensemble with avg smape 2.68:
4 - Ensemble with avg smape 3.55:
5 - Ensemble with avg smape 4.88:
6 - Ensemble with avg smape 117.49:
7 - Ensemble with avg smape 2.95:
8 - Ensemble with avg smape 3.66:
9 - Ensemble with avg smape 2.33:
10 - Ensemble with avg smape 3.3:
11 - Ensemble with avg smape 2.54:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

12 - Ensemble with avg smape 2.36:
13 - Ensemble with avg smape 4.02:
14 - Ensemble with avg smape 4.07:
Model Number: 15 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.344e+00, tolerance: 1.569e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

15 - Ensemble with avg smape 2.32:
16 - Ensemble with avg smape 2.3:
17 - Ensemble with avg smape 2.5:
18 - Ensemble with avg smape 3.55:
19 - Ensemble with avg smape 4.83:
20 - Ensemble with avg smape 117.49:
21 - Ensemble with avg smape 2.72:
22 - Ensemble with avg smape 3.66:
23 - Ensemble with avg smape 2.32:
24 - Ensemble with avg smape 3.28:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

25 - Ensemble with avg smape 2.72:
26 - Ensemble with avg smape 2.36:
27 - Ensemble with avg smape 4.11:
28 - Ensemble with avg smape 3.9:
Model Number: 29 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.344e+00, tolerance: 1.569e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

29 - Ensemble with avg smape 2.49:
30 - Ensemble with avg smape 2.44:
31 - Ensemble with avg smape 3.13:
32 - Ensemble with avg smape 3.58:
33 - Ensemble with avg smape 4.98:
34 - Ensemble with avg smape 117.49:
35 - Ensemble with avg smape 3.8:
36 - Ensemble with avg smape 3.68:
37 - Ensemble with avg smape 2.49:
38 - Ensemble with avg smape 3.37:
39 - Ensemble with avg smape 2.53:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

40 - Ensemble with avg smape 2.67:
41 - Ensemble with avg smape 4.04:
42 - Ensemble with avg smape 4.34:
Model Number: 43 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.344e+00, tolerance: 1.569e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

43 - Ensemble with avg smape 5.57:
44 - Ensemble with avg smape 5.57:
45 - Ensemble with avg smape 4.82:
46 - Ensemble with avg smape 5.08:
47 - Ensemble with avg smape 5.26:
48 - Ensemble with avg smape 117.49:
49 - Ensemble with avg smape 5.56:
50 - Ensemble with avg smape 5.66:
51 - Ensemble with avg smape 5.57:
52 - Ensemble with avg smape 5.58:
53 - Ensemble with avg smape 3.1:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

54 - Ensemble with avg smape 5.88:
55 - Ensemble with avg smape 4.13:
56 - Ensemble with avg smape 5.48:
Model Number: 57 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.344e+00, tolerance: 1.569e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

57 - Ensemble with avg smape 3.36:
58 - Ensemble with avg smape 3.35:
59 - Ensemble with avg smape 3.89:
60 - Ensemble with avg smape 3.98:
61 - Ensemble with avg smape 5.12:
62 - Ensemble with avg smape 117.49:
63 - Ensemble with avg smape 4.5:
64 - Ensemble with avg smape 4.03:
65 - Ensemble with avg smape 3.36:
66 - Ensemble with avg smape 3.41:
67 - Ensemble with avg smape 2.65:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

68 - Ensemble with avg smape 3.67:
69 - Ensemble with avg smape 3.97:
70 - Ensemble with avg smape 4.86:
Model Number: 71 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.344e+00, tolerance: 1.569e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

71 - Ensemble with avg smape 2.33:
72 - Ensemble with avg smape 2.28:
73 - Ensemble with avg smape 2.68:
74 - Ensemble with avg smape 3.55:
75 - Ensemble with avg smape 4.88:
76 - Ensemble with avg smape 117.49:
77 - Ensemble with avg smape 2.95:
78 - Ensemble with avg smape 3.66:
79 - Ensemble with avg smape 2.33:
80 - Ensemble with avg smape 3.3:
81 - Ensemble with avg smape 2.54:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

82 - Ensemble with avg smape 2.36:
83 - Ensemble with avg smape 4.02:
84 - Ensemble with avg smape 4.07:
Model Number: 85 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.344e+00, tolerance: 1.569e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

85 - Ensemble with avg smape 3.53:
86 - Ensemble with avg smape 3.53:
87 - Ensemble with avg smape 4.02:
88 - Ensemble with avg smape 4.12:
89 - Ensemble with avg smape 5.14:
90 - Ensemble with avg smape 117.49:
91 - Ensemble with avg smape 4.5:
92 - Ensemble with avg smape 4.16:
93 - Ensemble with avg smape 3.53:
94 - Ensemble with avg smape 3.51:
95 - Ensemble with avg smape 2.7:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

96 - Ensemble with avg smape 3.85:
97 - Ensemble with avg smape 3.95:
98 - Ensemble with avg smape 4.96:
Model Number: 99 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.344e+00, tolerance: 1.569e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

99 - Ensemble with avg smape 2.69:
100 - Ensemble with avg smape 2.69:
101 - Ensemble with avg smape 2.44:
102 - Ensemble with avg smape 3.53:
103 - Ensemble with avg smape 4.6:
104 - Ensemble with avg smape 117.49:
105 - Ensemble with avg smape 2.49:
106 - Ensemble with avg smape 3.69:
107 - Ensemble with avg smape 2.69:
108 - Ensemble with avg smape 3.34:
109 - Ensemble with avg smape 3.92:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

110 - Ensemble with avg smape 2.47:
111 - Ensemble with avg smape 4.69:
112 - Ensemble with avg smape 3.26:
Model Number: 113 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.344e+00, tolerance: 1.569e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

113 - Ensemble with avg smape 2.68:
114 - Ensemble with avg smape 2.7:
115 - Ensemble with avg smape 2.83:
116 - Ensemble with avg smape 3.73:
117 - Ensemble with avg smape 4.9:
118 - Ensemble with avg smape 117.49:
119 - Ensemble with avg smape 3.12:
120 - Ensemble with avg smape 3.84:
121 - Ensemble with avg smape 2.68:
122 - Ensemble with avg smape 3.25:
123 - Ensemble with avg smape 2.48:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

124 - Ensemble with avg smape 2.89:
125 - Ensemble with avg smape 3.81:
126 - Ensemble with avg smape 4.16:
Validation Round: 2
Model Number: 1 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.134e+00, tolerance: 1.290e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

📈 1 - Ensemble with avg smape 7.87:
📈 2 - Ensemble with avg smape 7.51:
📈 3 - Ensemble with avg smape 7.07:
4 - Ensemble with avg smape 8.6:
5 - Ensemble with avg smape 9.85:
6 - Ensemble with avg smape 8.25:
📈 7 - Ensemble with avg smape 6.32:
📈 8 - Ensemble with avg smape 3.47:
9 - Ensemble with avg smape 7.87:
10 - Ensemble with avg smape 13.09:
11 - Ensemble with avg smape 22.64:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

12 - Ensemble with avg smape 7.79:
13 - Ensemble with avg smape 7.84:
14 - Ensemble with avg smape 5.95:
Model Number: 15 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.134e+00, tolerance: 1.290e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

15 - Ensemble with avg smape 5.16:
16 - Ensemble with avg smape 4.93:
17 - Ensemble with avg smape 4.55:
📈 18 - Ensemble with avg smape 3.41:
19 - Ensemble with avg smape 9.7:
20 - Ensemble with avg smape 8.25:
21 - Ensemble with avg smape 3.77:
22 - Ensemble with avg smape 4.31:
23 - Ensemble with avg smape 5.16:
24 - Ensemble with avg smape 13.09:
25 - Ensemble with avg smape 30.05:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

26 - Ensemble with avg smape 5.0:
27 - Ensemble with avg smape 4.27:
📈 28 - Ensemble with avg smape 3.17:
Model Number: 29 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.134e+00, tolerance: 1.290e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

29 - Ensemble with avg smape 6.04:
30 - Ensemble with avg smape 5.91:
31 - Ensemble with avg smape 6.2:
32 - Ensemble with avg smape 7.34:
33 - Ensemble with avg smape 9.79:
34 - Ensemble with avg smape 8.25:
35 - Ensemble with avg smape 4.15:
📈 36 - Ensemble with avg smape 2.72:
37 - Ensemble with avg smape 6.04:
38 - Ensemble with avg smape 13.09:
39 - Ensemble with avg smape 25.48:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

40 - Ensemble with avg smape 6.02:
41 - Ensemble with avg smape 7.02:
42 - Ensemble with avg smape 4.98:
Model Number: 43 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.134e+00, tolerance: 1.290e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

43 - Ensemble with avg smape 2.84:
44 - Ensemble with avg smape 2.84:
45 - Ensemble with avg smape 6.04:
46 - Ensemble with avg smape 2.82:
47 - Ensemble with avg smape 9.65:
48 - Ensemble with avg smape 8.25:
49 - Ensemble with avg smape 2.84:
50 - Ensemble with avg smape 2.74:
51 - Ensemble with avg smape 2.84:
52 - Ensemble with avg smape 13.09:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

53 - Ensemble with avg smape 32.95:
54 - Ensemble with avg smape 2.88:
55 - Ensemble with avg smape 3.66:
56 - Ensemble with avg smape 2.91:
Model Number: 57 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.134e+00, tolerance: 1.290e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

57 - Ensemble with avg smape 4.51:
58 - Ensemble with avg smape 4.43:
59 - Ensemble with avg smape 5.13:
60 - Ensemble with avg smape 4.65:
61 - Ensemble with avg smape 9.72:
62 - Ensemble with avg smape 8.25:
63 - Ensemble with avg smape 3.14:
64 - Ensemble with avg smape 2.73:
65 - Ensemble with avg smape 4.51:
66 - Ensemble with avg smape 13.09:
67 - Ensemble with avg smape 29.04:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

68 - Ensemble with avg smape 4.48:
69 - Ensemble with avg smape 5.22:
70 - Ensemble with avg smape 3.93:
Model Number: 71 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.134e+00, tolerance: 1.290e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

71 - Ensemble with avg smape 7.87:
72 - Ensemble with avg smape 7.51:
73 - Ensemble with avg smape 7.07:
74 - Ensemble with avg smape 8.6:
75 - Ensemble with avg smape 9.85:
76 - Ensemble with avg smape 8.25:
77 - Ensemble with avg smape 6.32:
78 - Ensemble with avg smape 3.47:
79 - Ensemble with avg smape 7.87:
80 - Ensemble with avg smape 13.09:
81 - Ensemble with avg smape 22.64:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

82 - Ensemble with avg smape 7.79:
83 - Ensemble with avg smape 7.84:
84 - Ensemble with avg smape 5.95:
Model Number: 85 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.134e+00, tolerance: 1.290e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

85 - Ensemble with avg smape 4.96:
86 - Ensemble with avg smape 4.78:
87 - Ensemble with avg smape 5.06:
88 - Ensemble with avg smape 3.04:
89 - Ensemble with avg smape 9.68:
90 - Ensemble with avg smape 8.25:
91 - Ensemble with avg smape 3.46:
92 - Ensemble with avg smape 4.13:
93 - Ensemble with avg smape 4.96:
94 - Ensemble with avg smape 13.09:
95 - Ensemble with avg smape 31.12:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

96 - Ensemble with avg smape 4.82:
97 - Ensemble with avg smape 4.15:
98 - Ensemble with avg smape 3.26:
Model Number: 99 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.134e+00, tolerance: 1.290e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

99 - Ensemble with avg smape 9.68:
100 - Ensemble with avg smape 9.26:
101 - Ensemble with avg smape 9.94:
102 - Ensemble with avg smape 12.57:
103 - Ensemble with avg smape 9.94:
104 - Ensemble with avg smape 8.25:
105 - Ensemble with avg smape 6.73:
106 - Ensemble with avg smape 3.23:
107 - Ensemble with avg smape 9.68:
108 - Ensemble with avg smape 13.14:
109 - Ensemble with avg smape 18.38:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

110 - Ensemble with avg smape 9.6:
111 - Ensemble with avg smape 10.72:
112 - Ensemble with avg smape 8.06:
Model Number: 113 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.134e+00, tolerance: 1.290e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

113 - Ensemble with avg smape 7.32:
114 - Ensemble with avg smape 7.04:
115 - Ensemble with avg smape 6.92:
116 - Ensemble with avg smape 8.32:
117 - Ensemble with avg smape 9.83:
118 - Ensemble with avg smape 8.25:
119 - Ensemble with avg smape 5.79:
120 - Ensemble with avg smape 3.01:
121 - Ensemble with avg smape 7.32:
122 - Ensemble with avg smape 13.09:
123 - Ensemble with avg smape 23.5:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

124 - Ensemble with avg smape 7.25:
125 - Ensemble with avg smape 7.63:
126 - Ensemble with avg smape 5.67:
Validation Round: 3
Model Number: 1 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.041e+00, tolerance: 1.171e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

📈 1 - Ensemble with avg smape 12.28:
2 - Ensemble with avg smape 12.3:
3 - Ensemble with avg smape 13.15:
4 - Ensemble with avg smape 13.59:
5 - Ensemble with avg smape 23.3:
6 - Ensemble with avg smape 22.52:
7 - Ensemble with avg smape 16.66:
8 - Ensemble with avg smape 18.56:
9 - Ensemble with avg smape 12.28:
10 - Ensemble with avg smape 21.42:
11 - Ensemble with avg smape 16.08:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

12 - Ensemble with avg smape 12.35:
13 - Ensemble with avg smape 15.84:
14 - Ensemble with avg smape 15.2:
Model Number: 15 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.041e+00, tolerance: 1.171e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

15 - Ensemble with avg smape 15.82:
16 - Ensemble with avg smape 15.82:
17 - Ensemble with avg smape 17.61:
18 - Ensemble with avg smape 15.65:
19 - Ensemble with avg smape 23.25:
20 - Ensemble with avg smape 22.52:
21 - Ensemble with avg smape 17.85:
22 - Ensemble with avg smape 18.51:
23 - Ensemble with avg smape 15.82:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

24 - Ensemble with avg smape 21.41:
25 - Ensemble with avg smape 20.74:
26 - Ensemble with avg smape 15.89:
27 - Ensemble with avg smape 18.59:
28 - Ensemble with avg smape 17.46:
Model Number: 29 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.041e+00, tolerance: 1.171e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

📈 29 - Ensemble with avg smape 11.13:
30 - Ensemble with avg smape 11.14:
31 - Ensemble with avg smape 12.41:
32 - Ensemble with avg smape 13.18:
33 - Ensemble with avg smape 23.3:
34 - Ensemble with avg smape 22.52:
35 - Ensemble with avg smape 17.8:
36 - Ensemble with avg smape 18.28:
37 - Ensemble with avg smape 11.13:
38 - Ensemble with avg smape 21.41:
39 - Ensemble with avg smape 15.23:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

40 - Ensemble with avg smape 11.19:
41 - Ensemble with avg smape 15.37:
42 - Ensemble with avg smape 14.88:
Model Number: 43 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.041e+00, tolerance: 1.171e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

43 - Ensemble with avg smape 15.82:
44 - Ensemble with avg smape 15.82:
45 - Ensemble with avg smape 17.61:
46 - Ensemble with avg smape 15.64:
47 - Ensemble with avg smape 23.25:
48 - Ensemble with avg smape 22.52:
49 - Ensemble with avg smape 17.85:
50 - Ensemble with avg smape 18.5:
51 - Ensemble with avg smape 15.82:
52 - Ensemble with avg smape 21.41:
53 - Ensemble with avg smape 20.73:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

54 - Ensemble with avg smape 15.9:
55 - Ensemble with avg smape 18.59:
56 - Ensemble with avg smape 17.47:
Model Number: 57 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.041e+00, tolerance: 1.171e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

57 - Ensemble with avg smape 13.22:
58 - Ensemble with avg smape 13.23:
59 - Ensemble with avg smape 14.71:
60 - Ensemble with avg smape 14.19:
61 - Ensemble with avg smape 23.28:
62 - Ensemble with avg smape 22.52:
63 - Ensemble with avg smape 17.69:
64 - Ensemble with avg smape 18.35:
65 - Ensemble with avg smape 13.22:
66 - Ensemble with avg smape 21.41:
67 - Ensemble with avg smape 17.65:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

68 - Ensemble with avg smape 13.29:
69 - Ensemble with avg smape 16.81:
70 - Ensemble with avg smape 16.04:
Model Number: 71 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.041e+00, tolerance: 1.171e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

71 - Ensemble with avg smape 12.28:
72 - Ensemble with avg smape 12.3:
73 - Ensemble with avg smape 13.15:
74 - Ensemble with avg smape 13.59:
75 - Ensemble with avg smape 23.3:
76 - Ensemble with avg smape 22.52:
77 - Ensemble with avg smape 16.66:
78 - Ensemble with avg smape 18.56:
79 - Ensemble with avg smape 12.28:
80 - Ensemble with avg smape 21.42:
81 - Ensemble with avg smape 16.08:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

82 - Ensemble with avg smape 12.35:
83 - Ensemble with avg smape 15.84:
84 - Ensemble with avg smape 15.2:
Model Number: 85 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.041e+00, tolerance: 1.171e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in greater

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

85 - Ensemble with avg smape 15.0:
86 - Ensemble with avg smape 15.01:
87 - Ensemble with avg smape 16.63:
88 - Ensemble with avg smape 15.03:
89 - Ensemble with avg smape 23.26:
90 - Ensemble with avg smape 22.52:
91 - Ensemble with avg smape 17.91:
92 - Ensemble with avg smape 18.41:
93 - Ensemble with avg smape 15.0:
94 - Ensemble with avg smape 21.41:
95 - Ensemble with avg smape 19.61:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

96 - Ensemble with avg smape 15.08:
97 - Ensemble with avg smape 18.01:
98 - Ensemble with avg smape 16.99:
Model Number: 99 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.041e+00, tolerance: 1.171e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

99 - Ensemble with avg smape 11.26:
100 - Ensemble with avg smape 11.22:
📈 101 - Ensemble with avg smape 10.88:
102 - Ensemble with avg smape 12.71:
103 - Ensemble with avg smape 23.32:
104 - Ensemble with avg smape 22.52:
105 - Ensemble with avg smape 15.65:
106 - Ensemble with avg smape 18.75:
107 - Ensemble with avg smape 11.26:
108 - Ensemble with avg smape 21.52:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

109 - Ensemble with avg smape 13.55:
110 - Ensemble with avg smape 11.32:
111 - Ensemble with avg smape 14.43:
112 - Ensemble with avg smape 13.97:
Model Number: 113 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.041e+00, tolerance: 1.171e-02

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

113 - Ensemble with avg smape 11.27:
114 - Ensemble with avg smape 11.27:
115 - Ensemble with avg smape 11.57:
116 - Ensemble with avg smape 12.9:
117 - Ensemble with avg smape 23.31:
118 - Ensemble with avg smape 22.52:
119 - Ensemble with avg smape 16.73:
120 - Ensemble with avg smape 18.44:
121 - Ensemble with avg smape 11.27:
122 - Ensemble with avg smape 21.43:
123 - Ensemble with avg smape 14.21:

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning:

invalid value encountered in less_equal

124 - Ensemble with avg smape 11.34:
125 - Ensemble with avg smape 14.89:
126 - Ensemble with avg smape 14.4:

/usr/local/lib/python3.10/dist-packages/autots/evaluator/auto_model.py:3041: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/autots/evaluator/auto_model.py:3041: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.556e+00, tolerance: 1.570e-02

                            close
2025-03-01 13:27:00  80685.062500
2025-03-02 13:27:00  87288.966029
2025-03-03 13:27:00  86295.944866
2025-03-04 13:27:00  85297.552671
2025-03-05 13:27:00  84255.529397
2025-03-06 13:27:00  83228.347613
2025-03-07 13:27:00  82186.836816
2025-03-08 13:27:00  81134.009210
2025-03-09 13:27:00  80127.052656
2025-03-10 13:27:00  79145.468168
2025-03-11 13:27:00  78197.904139
2025-03-12 13:27:00  77249.162161
2025-03-13 13:27:00  76351.013505
2025-03-14 13:27:00  75473.958779
2025-03-15 13:27:00  74617.505328
2025-03-16 13:27:00  73830.018863
2025-03-17 13:27:00  73092.657383
2025-03-18 13:27:00  72402.918069
2025-03-19 13:27:00  71726.736643
2025-03-20 13:27:00  71107.878158
2025-03-21 13:27:00  70515.834673
2025-03-22 13:27:00  69946.542212
2025-03-23 13:27:00  69440.065026
2025-03-24 13:27:00  68980.287085
2025-03-25 13:27:00  68555.121389
2025-03-26 13:27:00  68133.642877
2025-03-27 13:27:00  67753.985724
2025-03-28 13:27:00  67387.305395
2025-03-29 13:27:00  67028.857801
2025-03-30 13:27:00  66713.437276